window.ARITH = window.ARITH || {};

ARITH["eng-phrases"] = {
  title: "Phrases",
  short: "Noun, verb, adjective, adverb and prepositional phrases: heads, nesting and the tests that find them",
  grade: "College ENGL 1xx · grammar",
  hours: 5,
  voice: "plain",
  eyebrow: "Grammar & Usage · phrase structure",
  hero: `<span class="c1">[the <span class="c3">[very <b>old</b>]</span> <b>sailor</b> <span class="c5">[<b>at</b> <span class="c1">[the <b>gate</b>]</span>]</span>]</span>`,
  lede: `Words in a sentence group into phrases, and phrases nest inside phrases. Every phrase is built around one word, its head, and the head's part of speech gives the phrase its name.`,
  plain: `<p>A sentence is not a string of words read one at a time. The words come in groups. In <i>The very old sailor at the gate waved</i>, the first seven words belong together: you can replace all of them with <i>he</i> (<i>He waved</i>), and you cannot replace <i>old sailor at</i> with anything. A group that works as a unit like this is a <b>phrase</b>. A phrase has no subject and finite verb of its own. A group that does (<i>the sailor waved</i>) is a <b>clause</b>.</p>
<p>Each phrase is built around one word, its <b>head</b>; the other words fill in details about it. <i>The very old sailor at the gate</i> is about a <i>sailor</i>, so it is a <b>noun phrase</b>. <i>Very old</i> is built on the adjective <i>old</i>: an <b>adjective phrase</b>. <i>At the gate</i> is built on the preposition <i>at</i>: a <b>prepositional phrase</b>. There are five main types, one per head: noun phrase (NP), <b>verb phrase</b> (VP), adjective phrase (AjP), <b>adverb phrase</b> (AvP: <i>remarkably quickly</i>) and prepositional phrase (PP). Phrases nest: the PP <i>at the gate</i> holds the NP <i>the gate</i>, and the whole PP sits inside the bigger NP, describing <i>sailor</i>.</p>
<p>Two more names describe what a phrase is doing rather than what it is built on. An <b>appositive</b> is a noun phrase that renames the one next to it: <i>Our captain, <u>a man of great courage</u>, nodded.</i> An <b>absolute phrase</b> is a noun plus a participle that comments on the whole sentence: <i><u>Its sails torn</u>, the ship limped home.</i> To find phrases you do not need to guess. Use the <b>constituency tests</b>: a phrase can usually be replaced by one word (<i>he, it, there, then, do so</i>), moved as a block, or given as the answer to a question.</p>`,
  formal: `<p>A <b>phrase</b> is a <b>constituent</b> (a word or group of words that functions as a unit in the structure of a sentence) built around a <b>head</b>, the one word that determines its category and its distribution. Words that complete the head are its <b>complements</b>; words that add optional detail are <b>modifiers</b> (pre-modifiers before the head, post-modifiers after it). A phrase lacks the subject–finite verb pairing that defines a <b>clause</b>. Handbooks define a phrase as "a group of related words"; linguistics also counts a single word as a phrase when it fills a phrase's slot (<i>She</i> is a one-word NP, the subject of <i>She waved</i>).</p>
<div class="display"><span class="c1">NP</span> = (determiner) (pre-modifiers) <b>noun</b> (post-modifiers): <i>[the [very old] <b>sailor</b> [at the gate]]</i>. A pronoun or proper noun is an NP alone.<br><span class="c2">VP</span> = (auxiliaries) <b>main verb</b> (objects, complements, adverbials): <i>[has <b>mended</b> [his nets] [on the beach]]</i>.<br><span class="c3">AjP</span> = (degree modifier) <b>adjective</b> (complement): <i>[much too <b>cold</b> [for swimming]]</i>, <i>[<b>fond</b> [of his lamp]]</i>.<br><span class="c4">AvP</span> = (degree modifier) <b>adverb</b> (complement): <i>[remarkably <b>quickly</b>]</i>, <i>[as <b>well</b> as she could]</i>.<br><span class="c5">PP</span> = <b>preposition</b> + object (an NP, pronoun or gerund phrase): <i>[<b>at</b> [the gate]]</i>, <i>[<b>for</b> [swimming]]</i>.</div>
<p>A PP functions <b>adjectivally</b> when it modifies a noun (<i>the gate <u>of the churchyard</u></i>) and <b>adverbially</b> when it modifies a verb, adjective or clause (<i>waited <u>at the gate</u></i>). An <b>appositive</b> is an NP (less often another phrase) that renames an adjacent NP; nonrestrictive appositives take commas. An <b>absolute phrase</b> is an NP followed by a participle (or an adjective or PP) that modifies the whole clause: <i>[<u>its sails</u> <u>torn</u>], the ship limped home</i>. Four <b>constituency tests</b> find phrases: <b>substitution</b> by a pro-form (<i>he, it, there, then, so, do so</i>); <b>movement</b> (fronting, or a cleft: <i>It was the old sailor who …</i>); the <b>fragment answer</b> to a question (<i>Who waved? The old sailor.</i>); and <b>coordination</b> with a phrase of the same type (<i>at the gate and on the path</i>). A string that passes is a constituent; a string that fails (<i>old sailor at</i>) is not. The tests also decide attachment: in <i>saw a ship with torn sails</i>, <i>saw it</i> replaces <i>a ship with torn sails</i>, so the PP is inside the object NP.</p>
<p>Two senses of "verb phrase" are in use. Handbooks (and the Verbs node) use it for the main verb with its auxiliaries, <i>has been mending</i>. Grammars of phrase structure use VP for the verb together with its objects, complements and adverbials, which is the complete predicate: <i>[has been mending his nets on the beach]</i>, the unit that <i>do so</i> replaces. Inquire brackets the larger VP and calls the verb string its head. Modern grammars revise other traditional points too. Huddleston and Pullum's <i>Cambridge Grammar of the English Language</i> (2002) treats articles and words like <i>my, this, some</i> as <b>determiners</b>, a function inside the NP, not adjectives. It analyses most traditional subordinating conjunctions as prepositions, so <i>until the tide turned</i> is a PP whose complement is a clause (handbooks call it an adverb clause). And it treats absolute phrases as <b>non-finite</b> or <b>verbless clauses</b> with their own subject. Inquire uses the traditional names and notes these where they matter.</p>`,
  legend: [
    { c: "c1", sym: `NP`, name: "Noun phrase", desc: "Head: a noun or pronoun. <i>[the old <b>sailor</b> at the gate]</i>, <i>[<b>she</b>]</i>. Subjects, objects and appositives are noun phrases." },
    { c: "c2", sym: `VP`, name: "Verb phrase", desc: "Head: the main verb, with its auxiliaries. The larger VP takes in the verb's objects and adverbials: the complete predicate." },
    { c: "c3", sym: `AjP`, name: "Adjective phrase", desc: "Head: an adjective. <i>[much too <b>cold</b> for swimming]</i>. In the story panels pink also marks a noun phrase's determiner and other pre-modifiers." },
    { c: "c4", sym: `AvP`, name: "Adverb phrase", desc: "Head: an adverb. <i>[remarkably <b>quickly</b>]</i>, <i>[<b>suddenly</b>]</i>. Answers how, when, where or to what degree." },
    { c: "c5", sym: `PP`, name: "Prepositional phrase", desc: "Head: a preposition, followed by its object. <i>[<b>at</b> the gate]</i>. Adjectival after a noun, adverbial after a verb. Green also marks post-modifiers." }
  ],
  steps: { title: "How to bracket the phrases of a sentence", items: [
    `Find the <b>finite verb</b> and its subject. The subject is a <span class="c1">noun phrase</span>; the verb with everything after it is the <span class="c2">verb phrase</span> (the predicate).`,
    `Find the smallest groups first: each <span class="c5">preposition</span> with its object, each adjective or adverb with the <i>very</i>, <i>too</i> or <i>quite</i> in front of it.`,
    `Name each group by its <b>head</b>: the one word you cannot delete without changing what kind of thing the group is. <i>Very old</i> without <i>very</i> is still <i>old</i>; without <i>old</i> it is nothing.`,
    `Build outward. Put each small phrase inside the phrase whose head it modifies: a PP after a noun goes inside that noun's NP; a PP that says where, when or how goes inside the VP.`,
    `Test every bracket. Replace it with a pro-form (<i>he, it, there, then, do so</i>), move it, or ask a question it answers. If the string fails every test, it is not a phrase: redraw the brackets.`,
    `Check for clauses inside. A group with its own subject and finite verb (<i>until the tide turned</i>, <i>which indent the shore</i>) is a clause, not a phrase, even when a phrase contains it.`
  ] },
  example: {
    prompt: `Bracket the phrases and name each head: <i>The keeper of the lighthouse saw a ship with torn sails.</i> Prove where <i>with torn sails</i> belongs.`,
    lines: [
      { math: `The keeper of the <br>lighthouse | <span class="c2"><b>saw</b></span> …`, note: "The finite verb is saw (it changes tense: sees, saw). Everything before it is the subject; saw and what follows is the predicate." },
      { math: `<span class="c1">[The <b>keeper</b> <br><span class="c5">[<b>of</b> <span class="c1">[the <b>lighthouse</b>]</span>]</span>]</span> <br>→ <span class="c1">He</span> saw …`, note: "Pronoun test: He replaces all five words, so they form one NP. Its head is keeper; of the lighthouse is a PP post-modifier, adjectival because it describes the keeper." },
      { math: `<span class="c5">[<b>with</b> <span class="c1">[<span class="c3">[<b>torn</b>]</span> <b>sails</b>]</span>]</span>`, note: "The smallest groups: torn is an adjective phrase (a participial adjective) modifying sails; the preposition with takes the NP torn sails as its object." },
      { math: `saw <span class="c1">it</span> ✓ · <br>saw <span class="c1">it</span> with torn sails ✗`, note: "Substitution decides the attachment. It replaces a ship with torn sails, and the sails belong to the ship, not to the seeing. So the PP is inside the object NP, an adjectival post-modifier of ship." },
      { math: `<span class="c2">[<b>saw</b> <span class="c1">[a <b>ship</b> <br><span class="c5">[with torn sails]</span>]</span>]</span>`, note: "The VP: head saw, with the NP a ship with torn sails as its direct object." },
      { math: `saw a ship <br><span class="c5">[with a telescope]</span> <br>→ saw <span class="c1">it</span> <br><span class="c5">with a telescope</span>`, note: "Contrast: here it replaces only a ship, and the PP stays outside. With a telescope is adverbial, inside the VP but not inside the NP." }
    ],
    answer: `<span class="c1">[The <b>keeper</b> <span class="c5">[<b>of</b> [the <b>lighthouse</b>]]</span>]</span> <span class="c2">[<b>saw</b> <span class="c1">[a <b>ship</b> <span class="c5">[<b>with</b> [<span class="c3">torn</span> <b>sails</b>]]</span>]</span>]</span>. Heads: <i>keeper</i> (NP), <i>of</i> (PP), <i>lighthouse</i> (NP), <i>saw</i> (VP), <i>ship</i> (NP), <i>with</i> (PP), <i>sails</i> (NP), <i>torn</i> (AjP). <i>With torn sails</i> is adjectival, inside the NP headed by <i>ship</i>.`
  },
  why: `<p>Phrases are the level at which most sentence problems actually happen. Agreement is decided by the head of the subject NP, not the nearest noun (<i>the box <u>of chocolates</u> is</i>). A misplaced modifier is a phrase attached to the wrong head. A fragment is very often a phrase punctuated as a sentence (<i>After the storm.</i>), and commas around appositives, absolute phrases and introductory phrases follow from knowing where a phrase begins and ends. Writers who can see phrases can move them, expand them and cut them on purpose.</p>
<p>Phrases are also where style lives. Irving delays his main clause behind a chain of prepositional phrases; Dickens piles seven modifiers in front of one noun; Douglass states a whole injustice in two plain noun phrases. Reading closely means noticing these choices. In linguistics, phrase structure is the core of syntax, and the constituency tests here are the same ones used to argue for every tree in a syntax textbook and in the parsers that machine translation and grammar checkers rely on.</p>`,
  careers: [
    { role: "Copy editor", use: "Fixes agreement errors by finding the head of a long subject NP, and moves misplaced phrases to sit next to the word they modify." },
    { role: "Technical writer", use: "Breaks long noun phrases such as 'emergency backup generator fuel valve inspection procedure' into clearer phrases with prepositions." },
    { role: "Computational linguist", use: "Builds and evaluates constituency parsers and treebanks (such as the Penn Treebank), which label every NP, VP and PP in a corpus." },
    { role: "Lawyer or contract drafter", use: "Argues over the scope of a modifying phrase, for example whether a PP at the end of a list attaches to every item or only the last." },
    { role: "ESL instructor", use: "Teaches English noun-phrase order (determiner before adjectives before the noun, PPs after it), which differs from many learners' languages." },
    { role: "Speech-language pathologist", use: "Measures a child's syntactic development by the length and complexity of the noun and verb phrases the child produces." }
  ],
  life: [
    "Finding the real subject in a long sentence so the verb agrees with it.",
    "Rewriting an ambiguous sentence like 'I saw the man with the binoculars' so it says only one thing.",
    "Reading a dense legal or technical sentence by first bracketing its prepositional phrases.",
    "Writing a résumé line or headline as a tight noun phrase ('Lead designer of the city's new transit map')."
  ],
  fields: [
    { name: "Linguistics", use: "Phrase structure and constituency tests are the foundation of syntax, from immediate-constituent analysis to modern X-bar theory." },
    { name: "Computer science (natural language processing)", use: "Constituency parsing assigns phrase brackets to sentences; prepositional-phrase attachment is a classic hard problem." },
    { name: "Law", use: "Statutory interpretation turns on which noun a modifying phrase attaches to, discussed in courts under the 'last antecedent' rule." },
    { name: "Foreign language study", use: "Word order inside the noun phrase (adjectives before or after the noun) and case marking after prepositions are learned phrase by phrase." }
  ],
  prereqWhy: {
    "eng-subject-predicate": "The first cut in any sentence is subject and predicate: the subject is a noun phrase and the complete predicate is the verb phrase.",
    "eng-modifiers": "Adjectives and adverbs are the heads of adjective and adverb phrases, and the degree words in front of them (<i>very, too, quite</i>) are their modifiers.",
    "eng-function-words": "A prepositional phrase is a preposition with its object, and telling a preposition from a particle or a conjunction decides where a PP begins."
  },
  unlocksWhy: {
    "eng-clauses": "A clause is a subject NP plus a finite VP; telling a phrase from a clause, and seeing clauses inside phrases, starts here.",
    "eng-verbals": "Gerund, participial and infinitive phrases are phrases headed by verb forms; they take objects and modifiers just as the phrases here do."
  },
  beyond: [
    { field: "Composition I", why: "Revising sentences means combining, moving and trimming phrases: expanding a noun phrase, fronting a prepositional phrase, cutting a chain of of-phrases." },
    { field: "Introduction to English Linguistics", why: "Syntax builds trees from phrase-structure rules (S → NP VP, NP → Det N PP) and defends each bracket with constituency tests." },
    { field: "Advanced Composition & Rhetoric", why: "Cumulative and periodic sentences, appositives and absolute phrases are the tools of sentence style." },
    { field: "Introduction to Literature", why: "Close reading of style looks at how a writer builds phrases: heavy noun phrases, chains of prepositions, delayed main clauses." }
  ],
  mistakes: [
    { wrong: `"The box of chocolates <u>are</u> on the table": the verb agrees with <i>chocolates</i>, the nearest noun.`, fix: `The head of the subject NP is <i>box</i>; <i>of chocolates</i> is a PP post-modifier inside it. The verb agrees with the head: <i>The box of chocolates <b>is</b> on the table.</i>` },
    { wrong: `"<i>After the storm passed</i> is a prepositional phrase, because it starts with a preposition."`, fix: `It has a subject (<i>the storm</i>) and a finite verb (<i>passed</i>), so handbooks call it a dependent (adverb) clause. Modern grammars call <i>after</i> a preposition with a clause as its complement, but they still count <i>the storm passed</i> as a clause.` },
    { wrong: `"A phrase must have at least two words, so <i>she</i> in <i>She waved</i> is not a phrase."`, fix: `A single word can fill a phrase's slot. <i>She</i> passes the same tests as <i>the old sailor</i> (it is the subject; it answers <i>Who waved?</i>), so it is a one-word noun phrase.` },
    { wrong: `"A prepositional phrase always describes the noun right before it": in <i>She waited at the gate after dinner</i>, <i>after dinner</i> describes the gate.`, fix: `Position does not decide attachment; the tests do. <i>She waited there after dinner</i> replaces only <i>at the gate</i>, and <i>after dinner</i> can move (<i>After dinner, she waited at the gate</i>). It is adverbial, modifying <i>waited</i>.` }
  ],
  practice: [
    { q: `Name the type and the head of each phrase: (a) <i>the tall trees by the river</i> (b) <i>extremely proud of her daughter</i> (c) <i>very carefully</i> (d) <i>under the old bridge</i> (e) <i>has been sleeping</i>`,
      a: `(a) noun phrase, head <i>trees</i> (<i>by the river</i> is a PP post-modifier); (b) adjective phrase, head <i>proud</i> (<i>extremely</i> modifies it; <i>of her daughter</i> is its complement); (c) adverb phrase, head <i>carefully</i>; (d) prepositional phrase, head <i>under</i>, with the NP <i>the old bridge</i> as its object; (e) verb phrase; its head is the verb string <i>has been sleeping</i> (main verb <i>sleeping</i> with the auxiliaries <i>has been</i>).` },
    { q: `Find each prepositional phrase and say whether it is adjectival or adverbial: <i>The house on the hill burned in the night.</i> Give a test.`,
      a: `<i>On the hill</i> is adjectival: it modifies the noun <i>house</i> and sits inside the subject NP (<i>It burned in the night</i>: <i>it</i> replaces <i>the house on the hill</i>). <i>In the night</i> is adverbial: it modifies the verb <i>burned</i>, tells when, and can move (<i>In the night, the house on the hill burned</i>).` },
    { q: `Name each italicised group and say whether it is a phrase or a clause: (a) <i>The storm having passed</i>, the crew went below. (b) Our mate, <i>a man of few words</i>, shrugged. (c) The crew went below <i>after the storm passed</i>. (d) The crew went below <i>after the storm</i>.`,
      a: `(a) absolute phrase: the noun phrase <i>the storm</i> plus the participle <i>having passed</i>, with no finite verb; it modifies the whole clause. (b) appositive noun phrase: it renames <i>our mate</i> and is set off by commas. (c) clause: it has a subject (<i>the storm</i>) and a finite verb (<i>passed</i>); handbooks call it a dependent adverb clause introduced by the subordinating conjunction <i>after</i>. (d) phrase: an adverbial prepositional phrase, <i>after</i> plus the NP <i>the storm</i>.` },
    { q: `<i>She hit the man with the umbrella.</i> Give the two bracketings of the verb phrase, say what each means, and use a test to separate them.`,
      a: `(1) <span class="c2">[hit <span class="c1">[the man]</span> <span class="c5">[with the umbrella]</span>]</span>: the PP is adverbial, and the umbrella is what she hit him with. (2) <span class="c2">[hit <span class="c1">[the man <span class="c5">[with the umbrella]</span>]</span>]</span>: the PP is adjectival, inside the object NP, and identifies which man. Pronoun test: in (1) <i>him</i> replaces only <i>the man</i> (<i>She hit him with the umbrella</i>); in (2) <i>him</i> replaces <i>the man with the umbrella</i> (<i>She hit him</i>). Movement: <i>With the umbrella, she hit the man</i> has only meaning (1), because a PP inside the object NP cannot be moved away from its noun.` }
  ],
  stories: [
    { title: "In the Bosom of One of Those Spacious Coves", book: "The Legend of Sleepy Hollow", author: "Washington Irving", year: 1820, kind: "Short story", where: "Opening sentence", scene: "sleepy-hollow", focus: ["ph", "oh"],
      tags: { ph: { name: "Preposition (head of a PP)", c: "c5", test: "The head of a prepositional phrase: it takes a noun phrase as its object." }, oh: { name: "Head of the object NP", c: "c1", test: "The noun or pronoun at the centre of the preposition's object." } },
      tokens: `In_ph the bosom_oh of_ph one_oh#one of_ph#of2 those spacious coves_oh which indent the eastern shore of_ph#of3 the Hudson_oh , at_ph that broad expansion_oh of_ph#of4 the river_oh denominated by_ph the ancient Dutch navigators_oh the Tappan Zee , and where they always prudently shortened sail and implored the protection of_ph#of5 St._oh#nicholas Nicholas_oh when they crossed , there lies a small market town or rural port , which by_ph#by2 some_oh is called Greensburgh , but which is more generally and properly known by_ph#by3 the name_oh of_ph#of6 Tarry_oh#tarry Town_oh#tarry .`,
      notes: { in: "The first preposition. Its object is everything up to Hudson: the bosom of one of those spacious coves which indent the eastern shore of the Hudson, a single PP of seventeen words.", bosom: "Head of the object of in. The NP the bosom … Hudson contains every phrase that follows it.", of: "A PP inside the NP headed by bosom: an adjectival post-modifier, which bosom?", one: "A pronoun as the head of an NP: one of those spacious coves. Pronouns head noun phrases too.", of2: "A third level of nesting. Of those spacious coves completes one: which one?", coves: "Head of the NP those spacious coves which indent …; the relative clause which indent the eastern shore of the Hudson is a post-modifier inside it.", of3: "Inside the relative clause: shore of the Hudson.", at: "A second place phrase, parallel to the first: it narrows the location from the coves to one broad stretch of the river.", expansion: "Head of an NP with a determiner (that), an adjective (broad) and two post-modifiers (of the river, and the participial phrase denominated … the Tappan Zee).", by: "The by-phrase of a passive participle: denominated by the ancient Dutch navigators names who gave the name.", navigators: "Head noun after three pre-modifiers: the, ancient, Dutch.", of5: "Inside the where-clause: the protection of St. Nicholas.", nicholas: "St. Nicholas, a proper name, is the object of of; Irving keeps the abbreviation St. with its period.", by2: "Placed before the verb for rhythm: which by some is called = which is called Greensburgh by some.", some: "A pronoun meaning “some people”, the object of by.", by3: "Adverbial: it tells how the port is known.", name: "Head of the NP the name of Tarry Town.", of6: "The last preposition in the sentence.", tarry: "Tarry Town, a two-word proper name, heads the last object." },
      note: `Irving makes the reader travel through eleven prepositional phrases before he names the town. The first PP, <i>in the bosom of one of those spacious coves which indent the eastern shore of the Hudson</i>, is seventeen words long, because each object holds another PP: <i>in</i> [<i>the bosom</i> [<i>of one</i> [<i>of those spacious coves</i> …]]]. A second place phrase follows (<i>at that broad expansion of the river</i>), then a <i>where</i>-clause, and only at the fifty-first word does the main clause arrive: <i>there lies a small market town or rural port</i>. The phrases are a zoom lens, from river to cove to town. Green marks each preposition, the head of its PP; amber marks the head of each object.` },
    { title: "No Accurate Knowledge of My Age", book: "Narrative of the Life of Frederick Douglass, an American Slave", author: "Frederick Douglass", year: 1845, kind: "Autobiography", where: "Chapter I", scene: "tidewater", focus: ["dt", "pm", "hd", "po"],
      tags: { dt: { name: "Determiner", c: "c3", test: "Comes first in the noun phrase and limits the noun: the, a, no, any, my." }, pm: { name: "Pre-modifier", c: "c3", test: "An adjective (or adjective phrase) between the determiner and the head." }, hd: { name: "Head noun", c: "c1", test: "The noun the whole phrase is about; delete it and the phrase collapses." }, po: { name: "Post-modifier", c: "c5", test: "A phrase after the head that modifies it: a PP, a participial phrase or a relative clause." } },
      tokens: `I have no_dt accurate_pm knowledge_hd of_po my_po age_po , never having seen any_dt#any authentic_pm#authentic record_hd#record containing_po#containing it_po#it .`,
      notes: { no: "A negative determiner: it makes the whole NP negative. I have no knowledge = I do not have any knowledge.", accurate: "An adjective pre-modifier. Douglass does not say he has no knowledge of his age; he says he has none that is accurate.", knowledge: "The head noun, the object of have. Everything from no to age is one NP.", of: "Of my age is a PP post-modifier: knowledge of what?", my: "Inside the PP sits another NP, my age, with my as its determiner. Noun phrases nest inside prepositional phrases.", age: "Head of the smaller NP my age, the object of of.", any: "A determiner. After never, any carries the negation through the phrase.", authentic: "An adjective pre-modifier: no record that is genuine.", record: "Head noun, the object of the participle seen.", containing: "A participial phrase as post-modifier, equivalent to the relative clause that contained it.", it: "The object of containing; it refers back to my age." },
      note: `Douglass's second sentence is built from two noun phrases with the same anatomy: determiner, adjective, <b>head noun</b>, post-modifier. <i>No accurate knowledge of my age</i> and <i>any authentic record containing it</i>. Each pre-modifier narrows the claim (not just knowledge but <i>accurate</i> knowledge, not just a record but an <i>authentic</i> one), and each post-modifier ties the noun to his own life. The first post-modifier is a prepositional phrase (<i>of my age</i>) with another NP inside it; the second is a participial phrase (<i>containing it</i>). Between them, <i>never having seen …</i> is a participial phrase too, attached to <i>I</i>: it gives the reason he has no knowledge.` },
    { title: "Very Sleepy and Stupid", book: "Alice's Adventures in Wonderland", author: "Lewis Carroll", year: 1865, kind: "Novel", where: "Chapter I, Down the Rabbit-Hole", scene: "rabbit-hole", focus: ["ajp", "avp"],
      tags: { ajp: { name: "Adjective phrase", c: "c3", test: "Built on an adjective: it can follow very or a linking verb (was very sleepy)." }, avp: { name: "Adverb phrase", c: "c4", test: "Built on an adverb: it tells how, when, where or how much, and can often move." } },
      tokens: `So she was considering in her own_ajp mind ( as_avp well_avp as_avp#as2 she_avp could_avp , for the hot_ajp day made her feel very_ajp#very sleepy_ajp and_ajp stupid_ajp ) , whether the pleasure of making a daisy-chain would be worth_ajp the_ajp#the trouble_ajp of_ajp getting_ajp up_ajp and_ajp#and2 picking_ajp the_ajp#the2 daisies_ajp , when suddenly_avp a White Rabbit with pink_ajp eyes ran close_avp by_avp#by her_avp .`,
      notes: { own: "A one-word adjective phrase inside the NP her own mind.", as: "As well as she could is an adverb phrase headed by well; as … as she could compares how well she was thinking with how well she was able to.", well: "The head adverb: considering well (or not very well).", as2: "The second as introduces the comparison, as she could.", hot: "A one-word adjective phrase, a pre-modifier of day.", very: "An adverb phrase inside the adjective phrase: very modifies sleepy (and perhaps stupid as well).", sleepy: "Head of the adjective phrase very sleepy and stupid, which describes her after the verb feel.", and: "Joins two adjectives into one coordinated adjective phrase.", stupid: "Here stupid means dull and slow, in the older sense.", worth: "The head of the adjective phrase worth the trouble of getting up and picking the daisies. Worth is unusual: it takes a noun phrase as its complement, which is why some dictionaries class it as a preposition.", trouble: "Head of the NP the trouble of getting up and picking the daisies, the complement of worth.", suddenly: "A one-word adverb phrase modifying ran. Carroll puts it before the subject for surprise.", pink: "A one-word adjective phrase inside the PP with pink eyes, which itself modifies Rabbit.", close: "Head of the adverb phrase close by her, which tells where the Rabbit ran; the PP by her completes it." },
      note: `This long sentence hangs on adjective and adverb phrases. <span class="c3">Very sleepy and stupid</span> describes Alice, with the adverb <i>very</i> as a degree modifier inside it. <span class="c3">Worth the trouble of getting up and picking the daisies</span> is an adjective phrase ten words long, because its head, <i>worth</i>, takes a whole noun phrase as complement. The adverb phrases tell how and where: <span class="c4">as well as she could</span> (how she was thinking), <span class="c4">suddenly</span> and <span class="c4">close by her</span> (how and where the Rabbit ran). The one-word phrases count too: <i>own</i>, <i>hot</i> and <i>pink</i> fill an adjective phrase's slot by themselves.` },
    { title: "A Squeezing, Wrenching, Grasping Old Sinner", book: "A Christmas Carol", author: "Charles Dickens", year: 1843, kind: "Novella", where: "Stave One", scene: "counting-house", focus: ["np", "app", "ajp"],
      tags: { np: { name: "Noun phrase", c: "c1", test: "Built on a noun or pronoun; replaceable by a pronoun." }, app: { name: "Appositive noun phrase", c: "c1", test: "A noun phrase that renames the noun phrase beside it." }, ajp: { name: "Adjective phrase", c: "c3", test: "Built on an adjective; it describes a noun." } },
      tokens: `Oh ! But he_np was a_np tight-fisted_np hand_np at_np the_np grind-stone_np , Scrooge_np#scrooge ! a_app squeezing_app , wrenching_app , grasping_app , scraping_app , clutching_app , covetous_app , old_app sinner_app ! Hard_ajp#hard and_ajp sharp_ajp as_ajp flint_ajp , from_ajp which_ajp no_ajp steel_ajp had_ajp ever_ajp struck_ajp out_ajp generous_ajp fire_ajp ; secret_ajp#secret , and_ajp#and2 self-contained_ajp , and_ajp#and3 solitary_ajp as_ajp#as2 an_ajp oyster_ajp .`,
      notes: { he: "A pronoun as a one-word NP, the subject. Dickens names him only at the end of the clause.", hand: "Head of the NP a tight-fisted hand at the grind-stone (a stingy, hard-driving worker); at the grind-stone is a PP post-modifier.", scrooge: "A proper noun, a one-word NP that repeats he and names him.", sinner: "The head noun, after seven pre-modifiers: five participial adjectives (squeezing, wrenching, grasping, scraping, clutching) and two adjectives (covetous, old).", hard: "Hard and sharp is a coordinated adjective phrase; as flint completes the comparison.", flint: "The relative clause from which no steel had ever struck out generous fire modifies flint, so it sits inside the adjective phrase.", secret: "The second adjective phrase: three coordinated adjectives, the last with its own comparison, solitary as an oyster.", as2: "As an oyster completes solitary: as solitary as an oyster, with the first as left out." },
      note: `Dickens describes Scrooge in phrases, not clauses. After <i>he was <span class="c1">a tight-fisted hand at the grind-stone</span></i>, the name arrives and a second noun phrase renames it: <span class="c1">a squeezing, wrenching, grasping, scraping, clutching, covetous, old sinner</span>, an appositive with seven pre-modifiers stacked in front of one head noun, <i>sinner</i>. Then come two adjective phrases with no verb at all: <span class="c3">hard and sharp as flint …</span> and <span class="c3">secret, and self-contained, and solitary as an oyster</span>. They are fragments by handbook standards, and they are deliberate: each one is a single phrase that adds to the portrait of the man named by <i>he</i>.` }
  ],
  origin: `School grammar first drew phrase structure as pictures: Alonzo Reed and Brainerd Kellogg's <i>Higher Lessons in English</i> (1877) taught the sentence diagrams still known by their names. Leonard Bloomfield's <i>Language</i> (1933) gave linguistics the idea of <b>immediate constituents</b>, the nested groups a sentence divides into, and Noam Chomsky's <i>Syntactic Structures</i> (1957) stated them as phrase-structure rules such as S → NP VP. The idea that every phrase has a head of the same category, X-bar theory, was proposed by Chomsky in 1970 and developed by Ray Jackendoff in <i>X-bar Syntax</i> (1977).`
};
