window.ARITH = window.ARITH || {};

ARITH["eng-clauses"] = {
  title: "Independent & Dependent Clauses",
  short: "Subject plus finite verb: main clauses that stand alone, subordinate clauses that can’t, and the marker words that decide",
  grade: "College ENGL 1xx · grammar",
  hours: 4,
  voice: "plain",
  eyebrow: "Grammar & Usage · clauses",
  hero: `<span class="c1">[The <span class="c4">river</span> <span class="c5">rose</span>]</span> <span class="c2">[<span class="c3">when</span> <span class="c4">night</span> <span class="c5">fell</span>]</span>`,
  lede: `A clause is a group of words with its own subject and its own finite verb. Some clauses can stand alone as sentences; others begin with a marker word that ties them to another clause, so they cannot.`,
  plain: `<p>Look for verbs that show tense: <i>rose</i>, <i>fell</i>, <i>is</i>, <i>had built</i>. Each one comes with its own subject (<i>the river rose</i>, <i>night fell</i>), and each subject–verb pair, with the words that go with it, is a <b>clause</b>. <i>The river rose when night fell</i> has two verbs that show tense, so it has two clauses.</p>
<p>Read each clause on its own, as if it ended with a period. <i>The river rose.</i> That works: it is an <b>independent</b> (main) clause. <i>When night fell.</i> That leaves you waiting for the rest; it is a <b>dependent</b> (subordinate) clause. The only difference is the first word. <i>When</i> is a <b>marker</b>: it tells you this clause is part of another one. Take it away and <i>Night fell</i> is a sentence again.</p>
<p>Markers come in a few families: words like <i>because, if, although, when, until</i>; the relative words <i>who, which, that, whose</i>; question words such as <i>what, where, whether</i>; and plain <i>that</i> (<i>I knew <u>that</u> it leaked</i>). Sometimes the marker is left out (<i>I knew it leaked</i>), but the clause is still dependent. Groups built on <i>to</i>-verbs or <i>-ing</i> forms (<i>to live deliberately</i>, <i>hoping for rain</i>) have no tense and no subject of their own, so they are phrases, not clauses.</p>`,
  formal: `<p>A <b>clause</b> is a construction containing a subject and a predicate whose verb is <b>finite</b>: marked for tense (past or present) and, where English shows it, for agreement with the subject (<i>she walks</i>, <i>they walk</i>). Modal auxiliaries (<i>can, must, should</i>) and imperatives also count as finite. An <b>independent (main) clause</b> is not grammatically subordinate to any other clause and can be punctuated as a sentence. A <b>dependent (subordinate) clause</b> functions as a constituent of another clause: as a noun (subject, object, complement, appositive), as an adjective modifying a noun, or as an adverb modifying a verb, adjective, adverb or the whole clause. It is usually introduced by a <b>subordinator</b>, which signals that dependence.</p>
<div class="display"><span class="c1">clause</span> = <span class="c4">subject</span> + <span class="c5">finite verb</span> (+ rest of predicate)<br><span class="c2">dependent</span> = <span class="c3">marker</span> + subject + finite verb …<br><span class="c3">Subordinating conjunctions</span>: after, although,<br>as, because, before, if, once, since, so that,<br>than, though, unless, until, when, where,<br>whereas, while<br><span class="c3">Relative words</span>: who, whom, whose, which,<br>that; when, where, why<br><span class="c3">Noun-clause markers</span>: that, whether, if;<br>who, what, which, when, where, why, how<br><span class="c3">Zero marker</span>: I knew [<u>(that)</u> it leaked]</div>
<p>Coordinating conjunctions (<i>and, but, or, nor, for, so, yet</i>) and conjunctive adverbs (<i>however, therefore, meanwhile</i>) join or link clauses without making either one dependent, which is why <i>But that ain’t no matter</i> is still independent. Dependent clauses can be <b>embedded</b> inside other dependent clauses to any depth: <i>I think [that the man [who sold us the raft] knew [that it leaked]]</i>. Handbooks treat the main clause as the whole sentence minus its removable modifier clauses; a noun clause that fills a required slot (<i>I think …</i>) stays inside the main clause, because <i>I think</i> alone is incomplete. Infinitives, gerunds and participles are <b>non-finite</b>, so traditional grammar classes <i>to live deliberately</i> or <i>hoping for rain</i> as verbal phrases.</p>
<p>Modern grammars draw the lines differently. Huddleston and Pullum’s <i>Cambridge Grammar of the English Language</i> (2002) counts <i>to live deliberately</i> and <i>hoping for rain</i> as <b>non-finite clauses</b> (clauses whose subject is understood), so for them a clause is defined by its predicate, not by a finite verb. They also reserve the term subordinator for <i>that, whether, if</i> (and infinitival <i>for</i>), and analyse <i>before, after, since, until, because</i> as prepositions taking a clause as complement. In their terms the main clause always contains its subordinate clauses (<i>matrix clause</i> is another name). Inquire follows the handbook definitions and notes the modern analysis where it matters.</p>`,
  legend: [
    { c: "c1", sym: `[IC]`, name: "Independent clause", desc: "Subject + finite verb, no marker: it can stand alone as a sentence. <i>[the river rose]</i>." },
    { c: "c2", sym: `[DC]`, name: "Dependent clause", desc: "Subject + finite verb, but tied to another clause by a marker or by its job. <i>[when night fell]</i>." },
    { c: "c3", sym: `MK`, name: "Marker", desc: "The subordinator, relative pronoun or question word that opens a dependent clause: <i>when, because, who, which, that, whether</i>." },
    { c: "c4", sym: `S`, name: "Clause subject", desc: "The (simple) subject of each clause. Ask <i>who</i> or <i>what</i> + the verb. Imperatives have an understood <i>you</i>." },
    { c: "c5", sym: `V`, name: "Finite verb", desc: "The verb that shows tense, with its auxiliaries: <i>rose, is, had built, must be</i>. One finite verb (or verb string) per clause." }
  ],
  steps: { title: "How to find and classify clauses", items: [
    `Find every <span class="c5">finite verb</span>: a verb that shows tense or is a modal or imperative (<i>rose, is, had built, must be</i>). Each finite verb string heads its own clause. Skip <i>to</i>-infinitives, <i>-ing</i> forms and participles used without an auxiliary.`,
    `Find each verb’s <span class="c4">subject</span> by asking <i>who</i> or <i>what</i> + the verb. In an imperative the subject is an understood <i>you</i>. A compound predicate (<i>lived … and earned</i>) is two verbs with one subject: one clause.`,
    `Look at the start of each clause for a <span class="c3">marker</span>: a subordinating conjunction, a relative word, a question word or <i>that</i>. Check for a zero marker where <i>that</i> or <i>whom</i> could be added back.`,
    `Set the boundaries. A dependent clause runs from its marker to the end of its predicate, and it sits inside the clause it belongs to. Coordinators (<i>and, but</i>) stand between clauses, in neither one.`,
    `Apply the stand-alone test: read each clause by itself with a period. Without a marker it is <span class="c1">independent</span>; with one it is <span class="c2">dependent</span>, and dropping the marker (or rewriting the relative word) turns it back into a sentence.`,
    `Preview the job of each dependent clause: <b>noun</b> if <i>it</i> or <i>something</i> can replace it, <b>adjective</b> if it follows and describes a noun, <b>adverb</b> if it tells when, where, why, how or on what condition.`
  ] },
  example: {
    prompt: `Find and classify the clauses: <i>Because the fog was thick, we tied up at the island where Jim had hidden the canoe.</i>`,
    lines: [
      { math: `<span class="c5">was</span> · <span class="c5">tied</span> · <span class="c5">had hidden</span>`, note: "Three finite verbs (all past tense), so three clauses. Up is a particle belonging to tied up." },
      { math: `<span class="c4">fog</span> was · <span class="c4">we</span> tied · <br><span class="c4">Jim</span> had hidden`, note: "Ask who or what + verb: what was thick? the fog. Who tied up? we. Who had hidden the canoe? Jim." },
      { math: `<span class="c3">Because</span> … · <span class="c3">where</span> … · <br>(none before <i>we</i>)`, note: "Because is a subordinating conjunction; where is a relative adverb here (it follows the noun island). The clause we tied up … has no marker." },
      { math: `<span class="c2">[Because the fog was thick]</span>,`, note: "The first dependent clause ends at thick: the comma marks the end of an introductory clause." },
      { math: `<span class="c1">[we tied up at the island</span> <br><span class="c2">[where Jim had hidden <br>the canoe]</span><span class="c1">]</span>`, note: "The where-clause describes island, so it sits inside the main clause, inside the noun phrase the island." },
      { math: `We tied up at the island. ✓ <br>Because the fog was thick. ✗`, note: "Stand-alone test: only the clause without a marker works as a sentence. Where Jim had hidden the canoe. also fails as a statement." },
      { math: `The fog was thick. ✓ <br>Jim had hidden the canoe there. ✓`, note: "Drop because, and rewrite where as there, and each dependent clause becomes a sentence: the marker was the only thing making it dependent." }
    ],
    answer: `<span class="c2">[<span class="c3">Because</span> the fog was thick]</span>, <span class="c1">[we tied up at the island <span class="c2">[<span class="c3">where</span> Jim had hidden the canoe]</span>]</span>. One independent clause, two dependent clauses: an adverb clause (why) and an adjective clause (which island).`
  },
  why: `<p>The clause is the unit that punctuation rules are written for. A fragment is usually a dependent clause or a phrase punctuated as a sentence (<i>Because the fog was thick.</i>). A comma splice is two independent clauses joined by a comma alone. Whether a sentence needs a comma, a semicolon, a period or nothing at all depends on which kind of clause stands on each side, so a writer who can find clauses can apply every comma and semicolon rule in the handbook.</p>
<p>Clauses are also how sentences carry ideas. An independent clause asserts something; a dependent clause backgrounds it as time, cause, condition or description. Choosing which idea goes in the main clause (<i>Although the river rose, the town held</i> versus <i>Although the town held, the river rose</i>) is choosing what the sentence is about. Readers of dense prose (law, philosophy, Austen) untangle it clause by clause.</p>`,
  careers: [
    { role: "Editor", use: "Fixes fragments and comma splices by spotting dependent clauses punctuated as sentences and independent clauses joined by commas." },
    { role: "Paralegal or contract drafter", use: "Separates the operative main clause of a provision from its conditions ('if', 'unless', 'provided that') so the obligation is unambiguous." },
    { role: "ESL / EFL teacher", use: "Teaches learners to build complex sentences with subordinators and relative pronouns, and to avoid the 'Because …' fragments common in early writing." },
    { role: "Technical writer", use: "Moves conditions into dependent clauses at the start of a step ('If the light is red, …') so the main clause holds the action." },
    { role: "Speech-language pathologist", use: "Measures syntactic development by counting clauses per utterance and the use of subordinate clauses in a child’s speech samples." },
    { role: "Computational linguist", use: "Builds parsers and clause-segmentation tools that split text at clause boundaries for translation, summarisation and information extraction." }
  ],
  life: [
    "Fixing a text or email that starts with 'Because I was late.' and stops.",
    "Reading the conditions in a lease or terms-of-service clause before the part that tells you what you must do.",
    "Hearing which part of a long announcement is the actual instruction and which part is background.",
    "Combining two short, choppy sentences into one that shows how the ideas are related."
  ],
  fields: [
    { name: "Linguistics", use: "Syntax studies clause structure, embedding (recursion) and the finite/non-finite distinction across languages." },
    { name: "Law", use: "Statutes and contracts are read clause by clause; the scope of a dependent 'if' or 'which' clause can decide a case." },
    { name: "Computer science (natural language processing)", use: "Clause boundary detection and dependency parsing break sentences into predicate–argument units for machine reading." },
    { name: "Psychology", use: "Psycholinguistics measures how readers process embedded clauses, such as the difficulty of center-embedded relative clauses." }
  ],
  prereqWhy: {
    "eng-patterns": "Every clause is built on one of the basic sentence patterns (S–V, S–V–O, S–LV–SC …), and a noun clause can fill the object or complement slot of a pattern.",
    "eng-phrases": "A clause is what a phrase is not: a group with its own subject and finite verb. Telling verbal phrases from clauses depends on the phrase types learned there."
  },
  unlocksWhy: {
    "eng-sentence-types": "Simple, compound, complex and compound-complex sentences are named by counting exactly the independent and dependent clauses found here.",
    "eng-subordinate": "The three jobs previewed here (noun, adjective, adverb) each get their own markers, tests and comma rules there."
  },
  beyond: [
    { field: "Composition I", why: "Revising for fragments, comma splices and sentence combining all rest on finding independent and dependent clauses." },
    { field: "Introduction to English Linguistics", why: "Syntax describes clauses as constituents, with finite and non-finite clauses, complementizers and recursive embedding." },
    { field: "Advanced Composition & Rhetoric", why: "Subordination and coordination are the main tools for ranking ideas and controlling emphasis in a sentence." },
    { field: "History of the English Language", why: "Old and Middle English marked subordinate clauses differently (verb-final order, þe and þæt), and the modern relative-pronoun system grew from them." }
  ],
  mistakes: [
    { wrong: `<i>We tied up at the island. Because the fog was thick.</i> (a dependent clause punctuated as a sentence)`, fix: `<i>Because</i> makes the clause dependent, so it is a fragment. Attach it: <i>We tied up at the island because the fog was thick.</i>` },
    { wrong: `Counting <i>She opened the door and looked outside</i> as two clauses.`, fix: `There is one subject, <i>she</i>, with two verbs: a compound predicate, so one clause. Two clauses need two subjects: <i>She opened the door, and she looked outside.</i>` },
    { wrong: `Treating <i>To finish the essay on time.</i> or <i>Hoping for an extension.</i> as a sentence.`, fix: `<i>To finish</i> and <i>hoping</i> are non-finite (no tense), so these are verbal phrases, not clauses. Add a main clause: <i>Hoping for an extension, I emailed the professor.</i>` },
    { wrong: `Thinking a sentence that begins with <i>But</i> or <i>And</i> is a dependent clause.`, fix: `Coordinating conjunctions do not subordinate. <i>But that ain’t no matter</i> is an independent clause; starting a sentence with <i>but</i> is standard in edited prose, though some instructors discourage it in formal papers.` },
    { wrong: `<i>I knew, the raft was gone.</i> (treating a zero-<i>that</i> clause as a second main clause)`, fix: `<i>The raft was gone</i> is the object of <i>knew</i>: <i>I knew (that) the raft was gone.</i> A noun clause in object position takes no comma.` }
  ],
  practice: [
    { q: `How many clauses are in <i>The dog barked when the mail came</i>, and which is dependent?`, a: `Two: <i>barked</i> and <i>came</i> are finite verbs, with subjects <i>dog</i> and <i>mail</i>. <i>When the mail came</i> is dependent because of the marker <i>when</i>; <i>the dog barked</i> is independent.` },
    { q: `Is <i>hoping for a letter</i> a clause? Explain.`, a: `No. <i>Hoping</i> is a present participle, which shows no tense, and the group has no subject of its own. It is a participial phrase: <i>Hoping for a letter, she checked the mailbox.</i> (Modern grammars would call it a non-finite clause.)` },
    { q: `Bracket the clauses and name the markers: <i>The students who finished early left before the bell rang.</i>`, a: `<i>[The students [who finished early] left [before the bell rang]].</i> Three clauses: the independent clause <i>The students … left</i>; a relative clause with the marker <i>who</i> (also its subject) inside the subject; and an adverb clause with the marker <i>before</i>.` },
    { q: `Bracket every clause and show the nesting: <i>I wonder whether the man who sold us the raft knew that it leaked.</i>`, a: `<i>[I wonder [whether the man [who sold us the raft] knew [that it leaked]]].</i> Four clauses, one independent. The <i>whether</i>-clause is the object of <i>wonder</i>; inside it, the <i>who</i>-clause modifies <i>man</i> and the <i>that</i>-clause is the object of <i>knew</i>. <i>I wonder</i> alone is incomplete, which is why the object clause belongs inside the main clause.` }
  ],
  origin: `<p>The word <i>clause</i> came into English in the Middle Ages through Old French from Medieval Latin <i>clausa</i>, a close or conclusion, from Latin <i>claudere</i>, to close. Grammarians used it for a short complete statement inside a longer sentence, a sense that also survives in the clauses of laws and contracts.</p>`,
  stories: [
    { title: "I Lived Alone, in the Woods", book: "Walden", author: "Henry David Thoreau", year: 1854, kind: "Memoir", where: "Economy (opening sentence)", scene: "walden-pond", focus: ["ic", "dc", "mk"],
      tags: { ic: { name: "Independent clause", c: "c1", test: "Has a subject and finite verb and no marker: it could stand alone." }, dc: { name: "Dependent clause", c: "c2", test: "Has a subject and finite verb but is opened by a marker." }, mk: { name: "Marker", c: "c3", test: "The word that makes a clause dependent." } },
      tokens: `When_mk I_dc wrote_dc the_dc following_dc pages_dc , or_dc rather_dc the_dc bulk_dc of_dc them_dc , I_ic#i2 lived_ic alone_ic , in_ic the_ic woods_ic , a_ic mile_ic from_ic any_ic neighbor_ic , in_ic a_ic house_ic which_mk I_dc#i3 had_dc built_dc myself_dc , on_ic the_ic shore_ic of_ic Walden_ic Pond_ic , in_ic Concord_ic , Massachusetts_ic , and_ic earned_ic my_ic living_ic by_ic the_ic labor_ic of_ic my_ic hands_ic only_ic .`,
      notes: { when: "A subordinating conjunction. It opens a clause of time and makes it dependent: When I wrote the following pages cannot stand alone.", i: "Subject of the dependent clause; wrote is its finite verb (past tense).", i2: "Subject of the independent clause, the one clause that could stand alone: I lived alone … and earned my living ….", lived: "First finite verb of the main clause.", which: "A relative pronoun, the object of had built. It opens a clause describing house.", i3: "Subject of the relative clause which I had built myself.", had: "Had built is the relative clause’s finite verb string (past perfect).", and: "This and joins two verbs, lived and earned, not two clauses: no new subject follows.", earned: "Second verb of the same main clause, sharing the subject I: a compound predicate." },
      note: `Thoreau’s first sentence has three clauses. The independent clause, <i>I lived alone … and earned my living …</i>, has one subject and two finite verbs, a compound predicate, so it counts once. The two dependent clauses each have a marker: the adverb clause <i>When I wrote the following pages, or rather the bulk of them</i> and the relative clause <i>which I had built myself</i>, which sits inside the main clause describing <i>house</i>. The long string of places (<i>in the woods, a mile from any neighbor, on the shore of Walden Pond</i>) is all phrases: no verbs.` },
    { title: "You Don’t Know About Me", book: "Adventures of Huckleberry Finn", author: "Mark Twain", year: 1884, kind: "Novel", where: "Chapter I (opening sentence)", scene: "raft-river", focus: ["ic", "dc", "mk"],
      tags: { ic: { name: "Independent clause", c: "c1", test: "Could stand alone as a sentence." }, dc: { name: "Dependent clause", c: "c2", test: "Opened by a marker; cannot stand alone." }, mk: { name: "Marker", c: "c3", test: "Here a dialect subordinating conjunction." } },
      tokens: `You_ic don’t_ic know_ic about_ic me_ic without_mk you_dc#you2 have_dc read_dc a_dc book_dc by_dc the_dc name_dc of_dc The_dc Adventures_dc of_dc Tom_dc Sawyer_dc ; but that_ic#that2 ain’t_ic no_ic matter_ic .`,
      notes: { you: "Subject of the first independent clause; don’t know is its finite verb string.", without: "In Huck’s Missouri dialect without works as a subordinating conjunction meaning unless (standard: unless you have read a book …). It makes the clause after it dependent.", you2: "Subject of the dependent clause; have read is its finite verb (present perfect).", that2: "Subject of the second independent clause. The coordinator but before it does not make it dependent.", "ain’t": "A nonstandard contraction (here for isn’t), and with no matter a double negative: features of Huck’s dialect. It is still a finite verb, so the clause is complete." },
      note: `Twain opens in Huck’s own voice. The sentence holds two independent clauses, <i>You don’t know about me …</i> and <i>that ain’t no matter</i>, joined by a semicolon and <i>but</i>, and one dependent clause inside the first: <i>without you have read a book by the name of The Adventures of Tom Sawyer</i>. Standard English would write <i>unless</i>; in Huck’s dialect <i>without</i> does the same job, which shows that what makes a clause dependent is the job its first word does. <i>Ain’t</i> and the double negative are nonstandard but regular features of the dialect Twain set down; the clause structure is the same as in standard English.` },
    { title: "A Truth Universally Acknowledged", book: "Pride and Prejudice", author: "Jane Austen", year: 1813, kind: "Novel", where: "Chapter I (first two sentences)", scene: "drawing-room", focus: ["ic", "dc", "mk"],
      tags: { ic: { name: "Independent clause", c: "c1" }, dc: { name: "Dependent clause", c: "c2", test: "Has a subject and finite verb but serves another clause." }, mk: { name: "Marker", c: "c3", test: "That (twice) and the concessive however." } },
      tokens: `It_ic is_ic a_ic truth_ic universally_ic acknowledged_ic , that_mk a_dc single_dc man_dc in_dc possession_dc of_dc a_dc good_dc fortune_dc must_dc be_dc in_dc want_dc of_dc a_dc wife_dc . However_mk little_dc known_dc the_dc feelings_dc or_dc views_dc of_dc such_dc a_dc man_dc may_dc be_dc on_dc his_dc first_dc entering_dc a_dc neighbourhood_dc , this_ic truth_ic is_ic so_ic well_ic fixed_ic in_ic the_ic minds_ic of_ic the_ic surrounding_ic families_ic , that_mk#that2 he_dc is_dc considered_dc as_dc the_dc rightful_dc property_dc of_dc some_dc one_dc or_dc other_dc of_dc their_dc daughters_dc .`,
      notes: { it: "Subject of the first independent clause, It is a truth universally acknowledged.", that: "Marker of a noun clause. It is the real subject, moved to the end with it holding its place (That a single man … is a truth universally acknowledged); it can also be read as renaming truth.", must: "Must be is the finite verb of the noun clause; man is its subject.", however: "Here however is not the conjunctive adverb but a concessive marker (however little = no matter how little), opening a dependent clause.", may: "May be is the finite verb of the concessive clause; feelings or views is its compound subject, placed after the verb.", entering: "A gerund (on his first entering a neighbourhood), not a finite verb, so this is a phrase inside the clause, not a clause of its own.", this: "This truth is the subject of the second sentence’s independent clause.", that2: "Marker of a result clause completing so well fixed: so fixed that he is considered ….", considered: "Is considered is the finite verb (passive) of the result clause; he is its subject." },
      note: `Two sentences, five clauses. The first has an independent clause and a noun clause, <i>that a single man … must be in want of a wife</i>, which is the sentence’s real subject, delayed to the end with <i>it</i> holding its place. The second has three: a concessive dependent clause opened by <i>however</i> (<i>However little known … may be</i>), the independent clause <i>this truth is so well fixed in the minds of the surrounding families</i>, and a result clause opened by <i>that</i>, which completes <i>so well fixed</i>. <i>On his first entering a neighbourhood</i> looks like a clause but has no finite verb: <i>entering</i> is a gerund.` }
  ]
};
