window.ARITH = window.ARITH || {};

ARITH["fraction-ops"] = {
  title: "Operations with Fractions",
  short: "Add, subtract, multiply and divide fractions",
  grade: "Grades 4–6",
  hours: 10,
  voice: "plain",
  eyebrow: "Rational numbers · the four operations",
  hero: `<span class="m"><span class="c2"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span> + <span class="c3"><span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span> = <span class="c1"><span class="fr"><span><i>ad</i> + <i>bc</i></span><span class="c4"><i>bd</i></span></span></span></span>`,
  lede: `You can only add pieces that are the same size. Rewrite both fractions over a <span class="m c4">common denominator</span>, then add the numerators.`,
  plain: `<p>One recipe needs <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup of milk and another needs <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup. How much is that in all? Adding tops and bottoms gives <span class="m"><span class="fr"><span>5</span><span>7</span></span></span>, which is less than the <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup you started with, so it cannot be right. Thirds and quarters are different-sized pieces. First cut both into pieces of one size. <b>Twelfths</b> work: <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> is 8 twelfths, <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> is 9 twelfths, and together they make 17 twelfths, or <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups.</p>
<p>That is the idea behind adding and subtracting fractions. Find a <b>common denominator</b>, rename each fraction in that piece size, then add or subtract the <b>numerators</b>. The denominator stays the same because the piece size did not change.</p>
<p>Multiplying works differently. "Half of <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup" means <span class="m"><span class="fr"><span>1</span><span>2</span></span> × <span class="fr"><span>3</span><span>4</span></span></span>: multiply the numerators and the denominators to get <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> cup. Dividing asks "how many of these fit into that?" You answer it by multiplying by the <b>reciprocal</b>, the second fraction turned upside down.</p>`,
  formal: `<p>For integers <span class="m"><i>a</i>, <i>b</i>, <i>c</i>, <i>d</i></span> with <span class="m"><i>b</i>, <i>d</i> ≠ 0</span>, the operations on ℚ are defined by:</p>
<div class="display"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> ± <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ad</i> ± <i>bc</i></span><span><i>bd</i></span></span> &nbsp;&nbsp; <span class="fr"><span><i>a</i></span><span><i>b</i></span></span> × <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ac</i></span><span><i>bd</i></span></span> &nbsp;&nbsp; <span class="fr"><span><i>a</i></span><span><i>b</i></span></span> ÷ <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>a</i></span><span><i>b</i></span></span> × <span class="fr"><span><i>d</i></span><span><i>c</i></span></span> <span class="dim">(<i>c</i> ≠ 0)</span></div>
<p>The <b>least common denominator</b> is <span class="m c4"><i>L</i> = lcm(<i>b</i>, <i>d</i>)</span>, giving <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> + <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>a</i>(<i>L</i>/<i>b</i>) + <i>c</i>(<i>L</i>/<i>d</i>)</span><span><i>L</i></span></span></span>. The fraction <span class="m"><span class="fr"><span><i>d</i></span><span><i>c</i></span></span></span> is the <b>reciprocal</b> (multiplicative inverse) of <span class="m"><span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span>. Results are usually reduced to lowest terms by dividing numerator and denominator by their gcd.</p>`,
  legend: [
    { c: "c2", sym: `<span class="fr"><span><i>a</i></span><span><i>b</i></span></span>`, name: "First fraction", desc: "The first operand. On the lab's top bar." },
    { c: "c3", sym: `<span class="fr"><span><i>c</i></span><span><i>d</i></span></span>`, name: "Second fraction", desc: "The second operand. On the lab's lower bar." },
    { c: "c4", sym: `<i>L</i>`, name: "Common denominator", desc: "A shared slice size both fractions can be written in. The least one is lcm(b, d)." },
    { c: "c1", sym: `<i>R</i>`, name: "Result", desc: "The sum, difference, product or quotient, reduced to lowest terms." }
  ],
  steps: { title: "How to operate on fractions", items: [
    `<b>Add or subtract:</b> find the least common denominator <span class="m c4">lcm(<i>b</i>, <i>d</i>)</span>.`,
    `Rename each fraction by multiplying its numerator and denominator by the same number so the denominator is <span class="m c4"><i>L</i></span>.`,
    `Add or subtract the numerators. Keep the denominator.`,
    `<b>Multiply:</b> multiply numerators and multiply denominators. Cancel common factors first to keep numbers small.`,
    `<b>Divide:</b> keep the first fraction, change ÷ to ×, and use the reciprocal of the second.`,
    `Reduce the answer to lowest terms. Convert to a mixed number if the context calls for it.`
  ] },
  example: {
    prompt: `You are baking. The cookies need <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup of flour and the bread needs <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup. Your bag holds <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span> cups. How much flour do you use, and how much is left?`,
    lines: [
      { math: `<span class="m"><span class="c4">lcm(3, 4) = 12</span></span>`, note: "Twelfths are the smallest slice both thirds and quarters fit into." },
      { math: `<span class="m"><span class="c2"><span class="fr"><span>2</span><span>3</span></span> = <span class="fr"><span>8</span><span>12</span></span></span>, &nbsp;<span class="c3"><span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>9</span><span>12</span></span></span></span>`, note: "Multiply 2/3 by 4/4 and 3/4 by 3/3." },
      { math: `<span class="m"><span class="fr"><span>8</span><span>12</span></span> + <span class="fr"><span>9</span><span>12</span></span> = <span class="c1"><span class="fr"><span>17</span><span>12</span></span></span> = 1<span class="fr"><span>5</span><span>12</span></span></span>`, note: "Flour used." },
      { math: `<span class="m">2<span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>5</span><span>2</span></span> = <span class="fr"><span>30</span><span>12</span></span></span>`, note: "Write the bag's amount in twelfths too." },
      { math: `<span class="m"><span class="fr"><span>30</span><span>12</span></span> − <span class="fr"><span>17</span><span>12</span></span> = <span class="c1"><span class="fr"><span>13</span><span>12</span></span></span> = 1<span class="fr"><span>1</span><span>12</span></span></span>`, note: "Flour left over." }
    ],
    answer: `You use <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups and have <span class="m">1<span class="fr"><span>1</span><span>12</span></span></span> cups left.`
  },
  why: `<p>Fractions appear whenever things are shared or measured in parts: recipes, tape measures marked in sixteenths of an inch, wrench and drill sizes, time signatures in music and split bills. Working with them exactly avoids rounding errors. One third rounded to 0.33 and added three times gives 0.99 instead of 1, and over a long run of cuts or doses such small errors add up.</p>
<p>Without the common-denominator rule, sums come out wrong in ways that can look reasonable. With it, you can scale a recipe, combine measurements, or work out how many servings a container holds. Algebra is built on the same rules: adding <span class="m"><span class="fr"><span>1</span><span><i>x</i></span></span> + <span class="fr"><span>1</span><span><i>x</i> + 1</span></span></span> uses a common denominator, and solving equations constantly multiplies by reciprocals.</p>`,
  careers: [
    { role: "Carpenter", use: "Adds and subtracts measurements such as 5 3/8 in and 2 11/16 in read off a tape measure marked in sixteenths." },
    { role: "Machinist", use: "Works to fractional-inch tolerances and subtracts cut widths from stock lengths." },
    { role: "Baker", use: "Multiplies fractional ingredient amounts when scaling a recipe by 3/4 or 1 1/2." },
    { role: "Nurse", use: "Divides a prescribed dose by the strength of a tablet, such as 3/4 mg ÷ 1/4 mg per tablet = 3 tablets." },
    { role: "Musician", use: "Checks that note values in a bar, like 1/4 + 1/8 + 1/8 + 1/2, add up to the time signature." },
    { role: "Tailor", use: "Adds seam allowances such as 5/8 in to pattern measurements." }
  ],
  life: [
    "Doubling or halving a recipe with 2/3 or 3/4 cup amounts",
    "Adding lengths on a tape measure marked in eighths and sixteenths",
    "Splitting a pizza or bill into equal fractional shares",
    "Working out how many 3/4-cup servings are in a container"
  ],
  fields: [
    { name: "Engineering drafting", use: "Imperial drawings dimension parts in fractions of an inch that must be added and subtracted exactly." },
    { name: "Music theory", use: "Rhythms are fractions of a whole note that must sum to the measure." },
    { name: "Probability", use: "Probabilities of combined events are found by adding and multiplying fractions." },
    { name: "Culinary arts", use: "Recipes are scaled by multiplying every amount by the same fraction." }
  ],
  layers: {
    concept: {
      heading: "How do you calculate with fractions?",
      lede: `Operations with fractions answer questions about shared and measured parts: how much in all, how much is left, how much of a part, and how many portions fit.`,
      history: `<p><b>The problem.</b> Sharing food, land and pay fairly means dividing things that do not split evenly. The Rhind papyrus, copied by the Egyptian scribe Ahmes around 1550 BCE from an older text, includes problems on dividing 1 to 9 loaves among 10 men and on exchanging bread for beer. Egyptian scribes wrote such shares mostly as sums of unit fractions like <span class="m"><span class="fr"><span>1</span><span>3</span></span></span> and <span class="m"><span class="fr"><span>1</span><span>5</span></span></span>, which made combining them slow.</p>
<p><b>The solution.</b> In India, fractions came to be written as one number above another; they are described in the Bakhshali manuscript and by Brahmagupta (about 628 CE) and Bhaskara (about 1150). Mathematicians in North Africa added the horizontal bar. It is first known from al-Hassar of Fez, around 1200, a specialist in dividing inheritances under Islamic law, and appears soon after in the work of Fibonacci in the 13th century.</p>
<p><b>What it changed.</b> With one number over another, any two fractions can be combined by a few short rules: a common denominator to add, straight across to multiply, the reciprocal to divide. Estates, business partnerships, recipes and tape-measure readings are still worked out with the rules in this lesson.</p>`,
      sources: [
        { title: "Rhind Mathematical Papyrus (Wikipedia)", url: "https://en.wikipedia.org/wiki/Rhind_Mathematical_Papyrus" },
        { title: "Fraction (Wikipedia)", url: "https://en.wikipedia.org/wiki/Fraction" }
      ],
      examples: [
        { role: "Carpenter", scene: `Two boards of <span class="m">5<span class="fr"><span>3</span><span>8</span></span></span> in and <span class="m">2<span class="fr"><span>11</span><span>16</span></span></span> in are joined end to end. In sixteenths: <span class="m"><span class="fr"><span>86</span><span>16</span></span> + <span class="fr"><span>43</span><span>16</span></span> = <span class="fr"><span>129</span><span>16</span></span> = </span><b><span class="m">8<span class="fr"><span>1</span><span>16</span></span></span> in</b>.`, takeaway: "A tape measure is marked in sixteenths, so sixteenths are the natural common denominator." },
        { role: "Baker", scene: `A recipe uses <span class="m">2<span class="fr"><span>2</span><span>3</span></span></span> cups of flour, and you make <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> of the batch: <span class="m"><span class="fr"><span>8</span><span>3</span></span> × <span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>24</span><span>12</span></span> = </span><b>2 cups</b>.`, takeaway: "Scaling multiplies every amount by the same fraction, so the recipe keeps its balance." },
        { role: "Nurse", scene: `An order calls for <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> mg and each tablet is <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> mg: <span class="m"><span class="fr"><span>3</span><span>4</span></span> ÷ <span class="fr"><span>1</span><span>4</span></span> = <span class="fr"><span>3</span><span>4</span></span> × <span class="fr"><span>4</span><span>1</span></span> = </span><b>3 tablets</b>.`, takeaway: "Dividing a dose by a tablet strength counts how many tablets fit the order." },
        { role: "Musician", scene: `In 4/4 time, a bar holds a quarter note, two eighth notes and a half note: <span class="m"><span class="fr"><span>2</span><span>8</span></span> + <span class="fr"><span>1</span><span>8</span></span> + <span class="fr"><span>1</span><span>8</span></span> + <span class="fr"><span>4</span><span>8</span></span> = <span class="fr"><span>8</span><span>8</span></span> = 1</span>, <b>one full bar</b>.`, takeaway: "Note values are fractions, and a bar is correct when they sum to the time signature." },
        { role: "Tailor", scene: `A pattern piece is <span class="m">12<span class="fr"><span>1</span><span>2</span></span></span> in wide, plus a <span class="m"><span class="fr"><span>5</span><span>8</span></span></span> in seam allowance on each side: <span class="m">12<span class="fr"><span>4</span><span>8</span></span> + <span class="fr"><span>10</span><span>8</span></span> = </span><b><span class="m">13<span class="fr"><span>3</span><span>4</span></span></span> in</b> to cut.`, takeaway: "Forgetting one seam allowance makes a garment that does not fit." },
        { role: "Machinist", scene: `From 6 in of bar stock, a <span class="m">2<span class="fr"><span>7</span><span>16</span></span></span> in piece is cut with a <span class="m"><span class="fr"><span>1</span><span>8</span></span></span> in wide blade: <span class="m"><span class="fr"><span>96</span><span>16</span></span> − <span class="fr"><span>39</span><span>16</span></span> − <span class="fr"><span>2</span><span>16</span></span> = <span class="fr"><span>55</span><span>16</span></span> = </span><b><span class="m">3<span class="fr"><span>7</span><span>16</span></span></span> in</b> left.`, takeaway: "The width of the cut is a fraction too, and leaving it out wastes material." }
      ]
    },
    build: {
      lede: `To add or subtract, rename both fractions over a common denominator; to multiply, go straight across; to divide, multiply by the reciprocal; then reduce.`,
      intro: `<p>The model above changes with the operation. For + and −, the top bars show <span class="c2"><i>a</i>/<i>b</i></span> and <span class="c3"><i>c</i>/<i>d</i></span>, the bars below re-cut both into the <span class="c4">common denominator</span> (violet lines), and the bottom bar shows the <span class="c1">result</span>. For ×, a grid shades <span class="c2"><i>a</i>/<i>b</i></span> as columns and <span class="c3"><i>c</i>/<i>d</i></span> as rows, and the overlap is the product. For ÷, segments the size of <span class="c3"><i>c</i>/<i>d</i></span> are laid along <span class="c2"><i>a</i>/<i>b</i></span> to count how many fit.</p>`,
      stepWhy: [
        `Only same-sized pieces can be counted together. The LCM of the denominators is the smallest piece size both fractions can be cut into exactly, which keeps the numbers small.`,
        `Multiplying top and bottom by the same number multiplies by 1, so the value does not change: <span class="m"><span class="fr"><span>2</span><span>3</span></span> × <span class="fr"><span>4</span><span>4</span></span> = <span class="fr"><span>8</span><span>12</span></span></span> is still two thirds of a cup.`,
        `Once the pieces match, the numerator counts pieces and the denominator names their size. 8 twelfths and 9 twelfths make 17 twelfths; the size stays twelfths.`,
        `Taking a fraction of a fraction cuts a part into smaller parts. The denominators multiply to give the new piece size, and the numerators count how many are kept. Cancelling first removes the same factor you would remove at the end.`,
        `Dividing asks how many copies of the divisor fit. Multiplying by <i>d</i>/<i>c</i> undoes multiplying by <i>c</i>/<i>d</i>, so the reciprocal answers that question: <span class="m"><span class="fr"><span>9</span><span>4</span></span> ÷ <span class="fr"><span>3</span><span>8</span></span> = <span class="fr"><span>9</span><span>4</span></span> × <span class="fr"><span>8</span><span>3</span></span> = 6</span>.`,
        `Lowest terms make answers quicker to compare and check. A mixed number like <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> is how cups, inches and hours are usually read.`
      ],
      bridge: `<p>The baking problem follows the pattern of most everyday fraction work: rename amounts in one piece size, combine them, then subtract from what you have. Here is where the same steps show up.</p>`,
      tasks: [
        { task: "Halving or scaling a recipe", link: `Scaling is step 4: half of <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup is <span class="m"><span class="fr"><span>1</span><span>2</span></span> × <span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>3</span><span>8</span></span></span> cup, with no common denominator needed.` },
        { task: "Adding lengths on a tape measure marked in eighths and sixteenths", link: `Rename everything in sixteenths, the common denominator, as the flour amounts were renamed in twelfths.` },
        { task: "Seeing how much is left in a bag or on a board", link: `Write what you have in the same pieces and subtract, as <span class="m"><span class="fr"><span>30</span><span>12</span></span> − <span class="fr"><span>17</span><span>12</span></span> = <span class="fr"><span>13</span><span>12</span></span></span> in the worked example.` },
        { task: "Working out how many servings are in a container", link: `Divide by the serving size with step 5, as practice item 4 found 6 servings of <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> cup in <span class="m">2<span class="fr"><span>1</span><span>4</span></span></span> cups.` },
        { task: "Finding a share of a share", link: `Multiply across and cancel first, as practice item 3 found that <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> of <span class="m"><span class="fr"><span>4</span><span>9</span></span></span> of a garden is <span class="m"><span class="fr"><span>1</span><span>6</span></span></span> of it.` }
      ]
    },
    formal: {
      setup: { title: "Writing a fraction problem", items: [
        { say: `<b>Name the amounts.</b> Give each a letter and say what it stands for, with units.`, math: `<span class="m"><span class="c2"><i>c</i></span> = <span class="fr"><span>2</span><span>3</span></span></span> cup (cookies), &nbsp;<span class="m"><span class="c3"><i>b</i></span> = <span class="fr"><span>3</span><span>4</span></span></span> cup (bread), &nbsp;<span class="m"><i>F</i> = 2<span class="fr"><span>1</span><span>2</span></span></span> cups (bag)` },
        { say: `<b>Write the expressions.</b> Flour used is the sum; flour left is the bag minus the amount used.`, math: `<span class="m"><i>u</i> = <span class="c2"><i>c</i></span> + <span class="c3"><i>b</i></span></span>, &nbsp;<span class="m"><i>r</i> = <i>F</i> − <i>u</i></span>` },
        { say: `<b>Justify the common denominator.</b> Multiplying by a fraction equal to 1 changes the form, not the value. Here <span class="m">lcm(3, 4) = 12</span>.`, math: `<span class="m"><span class="fr"><span>2</span><span>3</span></span> = <span class="fr"><span>2·4</span><span>3·4</span></span> = <span class="fr"><span>8</span><span>12</span></span></span>, &nbsp;<span class="m"><span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>3·3</span><span>4·3</span></span> = <span class="fr"><span>9</span><span>12</span></span></span>, &nbsp;<span class="m">2<span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>30</span><span>12</span></span></span>` },
        { say: `<b>Compute.</b> Add and subtract numerators over the common denominator, then write mixed numbers.`, math: `<span class="m"><i>u</i> = <span class="fr"><span>8</span><span>12</span></span> + <span class="fr"><span>9</span><span>12</span></span> = <span class="c1"><span class="fr"><span>17</span><span>12</span></span></span></span>, &nbsp;<span class="m"><i>r</i> = <span class="fr"><span>30</span><span>12</span></span> − <span class="fr"><span>17</span><span>12</span></span> = <span class="c1"><span class="fr"><span>13</span><span>12</span></span></span></span>` },
        { say: `<b>Answer in a sentence.</b> State both results with units.`, math: `You use <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups and have <span class="m">1<span class="fr"><span>1</span><span>12</span></span></span> cups left.` }
      ] }
    }
  },
  prereqWhy: {
    "fractions": "You need to understand what a fraction means and how to make equivalent fractions before you can combine them.",
    "gcf-lcm": "The least common denominator is the LCM of the denominators, and reducing results uses the GCF."
  },
  unlocksWhy: {
    "proportions": "Solving a proportion means working with equal fractions, cross-multiplying and simplifying.",
    "real-numbers": "The rational numbers ℚ are defined by fractions, and their closure under these four operations is a key property of the number system."
  },
  beyond: [
    { field: "Algebra I", why: "Solving equations with fractional coefficients and clearing denominators uses these rules directly." },
    { field: "Algebra II", why: "Rational expressions are added, subtracted, multiplied and divided with exactly the same procedures." },
    { field: "Calculus", why: "Partial fractions and simplifying difference quotients depend on fluent fraction algebra." }
  ],
  mistakes: [
    { wrong: `<span class="m"><span class="fr"><span>1</span><span>2</span></span> + <span class="fr"><span>1</span><span>3</span></span> = <span class="fr"><span>2</span><span>5</span></span></span> (adding tops and bottoms).`, fix: `Use a common denominator: <span class="m"><span class="fr"><span>3</span><span>6</span></span> + <span class="fr"><span>2</span><span>6</span></span> = <span class="fr"><span>5</span><span>6</span></span></span>. A sum of two positive numbers cannot be smaller than one of them, and 2/5 is less than 1/2.` },
    { wrong: `Flipping the first fraction when dividing: <span class="m"><span class="fr"><span>2</span><span>3</span></span> ÷ <span class="fr"><span>4</span><span>5</span></span> = <span class="fr"><span>3</span><span>2</span></span> × <span class="fr"><span>4</span><span>5</span></span></span>.`, fix: `Flip only the divisor: <span class="m"><span class="fr"><span>2</span><span>3</span></span> × <span class="fr"><span>5</span><span>4</span></span> = <span class="fr"><span>10</span><span>12</span></span> = <span class="fr"><span>5</span><span>6</span></span></span>.` },
    { wrong: `Finding a common denominator before multiplying.`, fix: `It gives the right answer but adds work. For multiplication, multiply straight across: <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> × <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ac</i></span><span><i>bd</i></span></span></span>.` },
    { wrong: `Subtracting mixed numbers part by part without regrouping: <span class="m">3<span class="fr"><span>1</span><span>4</span></span> − 1<span class="fr"><span>3</span><span>4</span></span></span> written as <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span>, by taking 1/4 from 3/4 instead.`, fix: `Regroup 1 from the 3: <span class="m">3<span class="fr"><span>1</span><span>4</span></span> = 2<span class="fr"><span>5</span><span>4</span></span></span>, so <span class="m">2<span class="fr"><span>5</span><span>4</span></span> − 1<span class="fr"><span>3</span><span>4</span></span> = 1<span class="fr"><span>2</span><span>4</span></span> = 1<span class="fr"><span>1</span><span>2</span></span></span>. Or use improper fractions: <span class="m"><span class="fr"><span>13</span><span>4</span></span> − <span class="fr"><span>7</span><span>4</span></span> = <span class="fr"><span>6</span><span>4</span></span> = 1<span class="fr"><span>1</span><span>2</span></span></span>.` }
  ],
  practice: [
    { ctx: "Cooking", q: `You pour <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> cup of milk, then <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> cup more. How much milk is that?`, a: `<span class="m"><span class="fr"><span>2</span><span>8</span></span> + <span class="fr"><span>3</span><span>8</span></span> = <span class="fr"><span>5</span><span>8</span></span></span>, so <b><span class="m"><span class="fr"><span>5</span><span>8</span></span></span> cup</b>.` },
    { ctx: "Work", q: `A project was <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> done at mid-morning and <span class="m"><span class="fr"><span>5</span><span>6</span></span></span> done at lunch. What fraction of the project was done in between?`, a: `LCD 12: <span class="m"><span class="fr"><span>10</span><span>12</span></span> − <span class="fr"><span>9</span><span>12</span></span> = <span class="fr"><span>1</span><span>12</span></span></span>, so <b><span class="m"><span class="fr"><span>1</span><span>12</span></span></span> of the project</b>.` },
    { ctx: "Gardening", q: `Vegetables fill <span class="m"><span class="fr"><span>4</span><span>9</span></span></span> of a garden, and tomatoes fill <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> of the vegetable area. What fraction of the garden is tomatoes?`, a: `<span class="m"><span class="fr"><span>4</span><span>9</span></span> × <span class="fr"><span>3</span><span>8</span></span></span>. Cancel first: <span class="m"><span class="fr"><span>1</span><span>3</span></span> × <span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>1</span><span>6</span></span></span> (check: 12/72 = 1/6). <b><span class="m"><span class="fr"><span>1</span><span>6</span></span></span> of the garden</b>.` },
    { ctx: "Food", q: `A container holds <span class="m">2<span class="fr"><span>1</span><span>4</span></span></span> cups of yogurt. How many <span class="m"><span class="fr"><span>3</span><span>8</span></span></span>-cup servings is that?`, a: `<span class="m"><span class="fr"><span>9</span><span>4</span></span> ÷ <span class="fr"><span>3</span><span>8</span></span> = <span class="fr"><span>9</span><span>4</span></span> × <span class="fr"><span>8</span><span>3</span></span> = <span class="fr"><span>72</span><span>12</span></span> = 6</span> servings.` },
    { ctx: "Crafts", q: `Write an equation with a letter for the unknown, then solve: a ribbon <span class="m">3<span class="fr"><span>3</span><span>4</span></span></span> yd long is cut into pieces <span class="m"><span class="fr"><span>5</span><span>8</span></span></span> yd long. How many pieces <i>n</i> do you get?`, a: `<span class="m"><i>n</i> × <span class="fr"><span>5</span><span>8</span></span> = <span class="fr"><span>15</span><span>4</span></span></span>, so <span class="m"><i>n</i> = <span class="fr"><span>15</span><span>4</span></span> × <span class="fr"><span>8</span><span>5</span></span> = <span class="fr"><span>120</span><span>20</span></span> = 6</span>. You get <b>6 pieces</b>.` }
  ],
  origin: `Egyptian scribes of the Rhind papyrus (c. 1550 BCE) calculated with unit fractions such as 1/3 and 1/5. The Indian mathematician Brahmagupta gave general rules for fraction arithmetic in 628 CE, and the horizontal fraction bar reached Europe through Fibonacci's <i>Liber Abaci</i> (1202).`
};
