window.ARITH = window.ARITH || {};

ARITH["fraction-ops"] = {
  title: "Operations with Fractions",
  short: "Add, subtract, multiply and divide fractions",
  grade: "Grades 4–6",
  hours: 10,
  voice: "plain",
  eyebrow: "Rational numbers · the four operations",
  hero: `<span class="m"><span class="c2"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span> + <span class="c3"><span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span> = <span class="c1"><span class="fr"><span><i>ad</i> + <i>bc</i></span><span class="c4"><i>bd</i></span></span></span></span>`,
  lede: `Sums and differences of fractions are computed over a <span class="m c4">common denominator</span>; products multiply numerators and denominators; quotients multiply by the <b>reciprocal</b> of the divisor.`,
  plain: `<p>One recipe needs <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup of milk and another needs <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup. How much is that in all? Adding tops and bottoms gives <span class="m"><span class="fr"><span>5</span><span>7</span></span></span>, which is less than the <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup you started with, so it cannot be right. Thirds and quarters are different-sized pieces. First cut both into pieces of one size. <b>Twelfths</b> work: <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> is 8 twelfths, <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> is 9 twelfths, and together they make 17 twelfths, or <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups.</p>
<p>That is the idea behind adding and subtracting fractions. Find a <b>common denominator</b>, rename each fraction in that piece size, then add or subtract the <b>numerators</b>. The denominator stays the same because the piece size did not change.</p>
<p>Multiplying works differently. "Half of <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup" means <span class="m"><span class="fr"><span>1</span><span>2</span></span> × <span class="fr"><span>3</span><span>4</span></span></span>: multiply the numerators and the denominators to get <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> cup. Dividing asks "how many of these fit into that?" You answer it by multiplying by the <b>reciprocal</b>, the second fraction turned upside down.</p>`,
  formal: `<p>For integers <span class="m"><i>a</i>, <i>b</i>, <i>c</i>, <i>d</i></span> with <span class="m"><i>b</i>, <i>d</i> ≠ 0</span>, the operations on ℚ are defined by:</p>
<div class="display"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> ± <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ad</i> ± <i>bc</i></span><span><i>bd</i></span></span> &nbsp;&nbsp; <span class="fr"><span><i>a</i></span><span><i>b</i></span></span> × <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ac</i></span><span><i>bd</i></span></span> &nbsp;&nbsp; <span class="fr"><span><i>a</i></span><span><i>b</i></span></span> ÷ <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>a</i></span><span><i>b</i></span></span> × <span class="fr"><span><i>d</i></span><span><i>c</i></span></span> <span class="dim">(<i>c</i> ≠ 0)</span></div>
<p>The <b>least common denominator</b> is <span class="m c4"><i>L</i> = lcm(<i>b</i>, <i>d</i>)</span>, giving <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> + <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>a</i>(<i>L</i>/<i>b</i>) + <i>c</i>(<i>L</i>/<i>d</i>)</span><span><i>L</i></span></span></span>. The fraction <span class="m"><span class="fr"><span><i>d</i></span><span><i>c</i></span></span></span> is the <b>reciprocal</b> (multiplicative inverse) of <span class="m"><span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span>. Results are usually reduced to lowest terms by dividing numerator and denominator by their gcd.</p>`,
  legend: [
    { c: "c2", sym: `<span class="fr"><span><i>a</i></span><span><i>b</i></span></span>`, name: "First fraction", desc: "The amount you start with. In the model it is the left bar, or the columns of the grid." },
    { c: "c3", sym: `<span class="fr"><span><i>c</i></span><span><i>d</i></span></span>`, name: "Second fraction", desc: "The amount you add, take away, multiply by or divide by. It is the right bar, or the rows of the grid." },
    { c: "c4", sym: `<i>L</i>`, name: "Common denominator", desc: "One piece size both fractions fit into. The lines that re-cut both bars show it. The least one is lcm(b, d)." },
    { c: "c1", sym: `<i>R</i>`, name: "Result", desc: "The answer in lowest terms: the sum, difference, product or quotient. It is the bottom bar for + and −, and the overlap for ×." }
  ],
  steps: { title: "How to operate on fractions", items: [
    `<b>Add or subtract:</b> find the least common denominator <span class="m c4">lcm(<i>b</i>, <i>d</i>)</span>.`,
    `Rename each fraction by multiplying its numerator and denominator by the same number so the denominator is <span class="m c4"><i>L</i></span>.`,
    `Add or subtract the numerators. Keep the denominator.`,
    `<b>Multiply:</b> multiply numerators and multiply denominators. Cancel common factors first to keep numbers small.`,
    `<b>Divide:</b> keep the first fraction, change ÷ to ×, and use the reciprocal of the second.`,
    `Reduce the answer to lowest terms. Convert to a mixed number if the context calls for it.`
  ] },
  example: {
    prompt: `You are baking. The cookies need <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup of flour and the bread needs <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup. Your bag holds <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span> cups. How much flour do you use, and how much is left?`,
    lines: [
      { math: `<span class="m"><span class="c4">lcm(3, 4) = 12</span></span>`, note: "Twelfths are the smallest slice both thirds and quarters fit into." },
      { math: `<span class="m"><span class="c2"><span class="fr"><span>2</span><span>3</span></span> = <span class="fr"><span>8</span><span>12</span></span></span>, &nbsp;<span class="c3"><span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>9</span><span>12</span></span></span></span>`, note: "Multiply 2/3 by 4/4 and 3/4 by 3/3." },
      { math: `<span class="m"><span class="fr"><span>8</span><span>12</span></span> + <span class="fr"><span>9</span><span>12</span></span> = <span class="c1"><span class="fr"><span>17</span><span>12</span></span></span> = 1<span class="fr"><span>5</span><span>12</span></span></span>`, note: "Flour used." },
      { math: `<span class="m">2<span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>5</span><span>2</span></span> = <span class="fr"><span>30</span><span>12</span></span></span>`, note: "Write the bag's amount in twelfths too." },
      { math: `<span class="m"><span class="fr"><span>30</span><span>12</span></span> − <span class="fr"><span>17</span><span>12</span></span> = <span class="c1"><span class="fr"><span>13</span><span>12</span></span></span> = 1<span class="fr"><span>1</span><span>12</span></span></span>`, note: "Flour left over." }
    ],
    answer: `You use <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups and have <span class="m">1<span class="fr"><span>1</span><span>12</span></span></span> cups left.`
  },
  why: `<p>Fractions appear whenever things are shared or measured in parts: recipes, tape measures marked in sixteenths of an inch, wrench and drill sizes, time signatures in music and split bills. Working with them exactly avoids rounding errors. One third rounded to 0.33 and added three times gives 0.99 instead of 1, and over a long run of cuts or doses such small errors add up.</p>
<p>Without the common-denominator rule, sums come out wrong in ways that can look reasonable. With it, you can scale a recipe, combine measurements, or work out how many servings a container holds. Algebra is built on the same rules: adding <span class="m"><span class="fr"><span>1</span><span><i>x</i></span></span> + <span class="fr"><span>1</span><span><i>x</i> + 1</span></span></span> uses a common denominator, and solving equations constantly multiplies by reciprocals.</p>`,
  careers: [
    { role: "Carpenter", use: "Adds and subtracts measurements such as 5 3/8 in and 2 11/16 in read off a tape measure marked in sixteenths." },
    { role: "Machinist", use: "Works to fractional-inch tolerances and subtracts cut widths from stock lengths." },
    { role: "Baker", use: "Multiplies fractional ingredient amounts when scaling a recipe by 3/4 or 1 1/2." },
    { role: "Nurse", use: "Divides a prescribed dose by the strength of a tablet, such as 3/4 mg ÷ 1/4 mg per tablet = 3 tablets." },
    { role: "Musician", use: "Checks that note values in a bar, like 1/4 + 1/8 + 1/8 + 1/2, add up to the time signature." },
    { role: "Tailor", use: "Adds seam allowances such as 5/8 in to pattern measurements." }
  ],
  life: [
    "Doubling or halving a recipe with 2/3 or 3/4 cup amounts",
    "Adding lengths on a tape measure marked in eighths and sixteenths",
    "Splitting a pizza or bill into equal fractional shares",
    "Working out how many 3/4-cup servings are in a container"
  ],
  fields: [
    { name: "Engineering drafting", use: "Imperial drawings dimension parts in fractions of an inch that must be added and subtracted exactly." },
    { name: "Music theory", use: "Rhythms are fractions of a whole note that must sum to the measure." },
    { name: "Probability", use: "Probabilities of combined events are found by adding and multiplying fractions." },
    { name: "Culinary arts", use: "Recipes are scaled by multiplying every amount by the same fraction." }
  ],
  layers: {
    nudge: "Not yet. Check the piece size, and which fraction you flipped.",
    concept: {
      lede: `Fraction math answers four questions about parts: how much in all, how much is left, how much of a part, and how many fit.`,
      heading: "What are operations with fractions?",
      question: { text: "How much?", sub: `Fractions answer four everyday questions: how much in all, how much is left, how much is a part of a part, and how many fit. The model above works all four. Watch it, then try each idea yourself.`,
        figure: { sym: `<i>R</i>`, value: "11", cap: "the answer's top number", echo: "num" } },
      ideasTitle: "Four ideas, all in the model",
      objects: ["cup", "cups", "flour", "scoop", "scoops", "tablet", "tablets", "board", "boards", "loaf", "loaves", "note", "notes", "bar", "pieces", "piece", "thirds", "quarters", "twelfths", "eighths", "sevenths"],
      walk: { title: "Add it together: flour for two recipes",
        lead: `One situation, step by step. Try each question before you show the next line.`,
        prompt: `You bake cookies and bread on the same day. The cookies need <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup of flour. The bread needs <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup. How much flour do you need in all?`,
        demo: { kind: "fraction", n: 17, d: 12, mixed: true, cap: "cups of flour", alt: "Two bars, each cut into 12 equal parts. Eight parts fill in for the cookies' 2/3 cup, nine more fill in for the bread's 3/4 cup, and the total reads 1 5/12 cups." },
        lines: [
          { math: `<span class="m"><span class="c2"><span class="fr"><span>2</span><span>3</span></span></span> + <span class="c3"><span class="fr"><span>3</span><span>4</span></span></span></span>`, note: `Two amounts of flour. Thirds and quarters are different-sized pieces.`, frame: 0 },
          { math: `<span class="m"><span class="c2"><span class="fr"><span>2</span><span>3</span></span></span> + <span class="c3"><span class="fr"><span>3</span><span>4</span></span></span> ≠ <span class="fr"><span>5</span><span>7</span></span></span>`, note: `A shortcut adds the tops and the bottoms. It gives <span class="m"><span class="fr"><span>5</span><span>7</span></span></span> cup, less than the bread's <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup alone. So it can't be right.`, frame: 0 },
          { math: `<span class="m c4">lcm(3, 4) = 12</span>`, note: `Find one piece size that both fit into. Thirds and quarters both cut evenly into twelfths. This is the common denominator.`, frame: 0 },
          { math: `<span class="m"><span class="c2"><span class="fr"><span>2</span><span>3</span></span></span> = <span class="fr"><span>2 × 4</span><span>3 × 4</span></span> = <span class="c2"><span class="fr"><span>8</span><span>12</span></span></span></span>`, note: `Cut each third into 4 pieces. Two thirds become 8 twelfths. It is the same amount of flour.`, frame: 8 },
          { math: `<span class="m"><span class="c3"><span class="fr"><span>3</span><span>4</span></span></span> = <span class="fr"><span>3 × 3</span><span>4 × 3</span></span> = <span class="c3"><span class="fr"><span>9</span><span>12</span></span></span></span>`, note: `Cut each quarter into 3 pieces. Three quarters become 9 twelfths.`, frame: 8 },
          { math: `<span class="m"><span class="fr"><span>8</span><span>12</span></span> + <span class="fr"><span>9</span><span>12</span></span> = <span class="c1"><span class="fr"><span>17</span><span>12</span></span></span></span>`, note: `Now the pieces match. Add the tops: 8 + 9 = 17. The bottom stays 12, because the piece size did not change.`, frame: 17 },
          { math: `<span class="m"><span class="c1"><span class="fr"><span>17</span><span>12</span></span></span> = <span class="c1">1<span class="fr"><span>5</span><span>12</span></span></span></span>`, note: `Twelve twelfths make one cup, with 5 twelfths left over.`, frame: 18 }
        ],
        predict: [null,
          { ask: `A friend adds the tops and the bottoms: 2 + 3 over 3 + 4 makes <span class="m"><span class="fr"><span>5</span><span>7</span></span></span> cup. Is that right?`, choices: [
            { t: "No. 5/7 cup is less than the 3/4 cup of bread alone", ok: true },
            { t: "Yes. Add the tops, then add the bottoms", why: "Adding the bottoms changes the piece size. Sevenths are neither thirds nor quarters." },
            { t: "Yes, once you reduce it", why: "5/7 does not reduce. It is still less than 3/4 cup, so it is too small." }
          ], hint: `Two amounts together can't be less than one of them alone.` },
          { ask: `Thirds and quarters need one piece size. What is the smallest number that both 3 and 4 divide into evenly?`, parts: [{ label: "smallest shared number", ans: 12 }], hint: `Count by 4s: 4, 8, 12. Which one does counting by 3s also reach?` },
          { ask: `Cut each third into 4 twelfths. How many twelfths is <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup?`, parts: [{ label: "twelfths", ans: 8 }], hint: `2 thirds, with 4 twelfths in each.` },
          { ask: `To write <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> in twelfths, what do you do?`, choices: [
            { t: "Multiply the top and the bottom by 3", ok: true },
            { t: "Multiply only the bottom by 3", why: "That gives 3/12, a much smaller amount. Change the top and the bottom by the same number." },
            { t: "Add 8 to the bottom", why: "That also gives 3/12, far less than 3/4. Multiply the top and the bottom instead." }
          ], hint: `4 × 3 = 12. Do the same to the top.` },
          { ask: `Now the pieces match. How many twelfths is <span class="m"><span class="fr"><span>8</span><span>12</span></span></span> + <span class="m"><span class="fr"><span>9</span><span>12</span></span></span>?`, parts: [{ label: "twelfths", ans: 17 }], hint: `Add the tops. The bottom stays 12.` },
          { ask: `Twelve twelfths make one cup. Write <span class="m"><span class="fr"><span>17</span><span>12</span></span></span> as whole cups and twelfths.`, parts: [{ label: "whole cups", ans: 1 }, { label: "twelfths left", ans: 5 }], hint: `Take 12 out of 17. How many are left?` }],
        answer: `You need <span class="m c1">1<span class="fr"><span>5</span><span>12</span></span></span> cups of flour in all, a little less than <span class="m">1<span class="fr"><span>1</span><span>2</span></span></span> cups.` },
      ideas: [
        { c: "c4", title: "Cut both to one size", term: "common denominator", text: `You can only add pieces of one size. Thirds and quarters both cut evenly into twelfths, so twelfths work for both.`,
          demo: { kind: "fraction", n: 2, d: 3, split: 4, alt: "A bar cut into thirds with two shaded, then every third cut into 4: 2/3 becomes 8/12, the same amount." }, try: { label: "Add 1/2 and 1/3", lab: "op:0,b:2,a:1,d:3,c:1" } },
        { c: "c1", title: "Add the tops, keep the bottom", term: "numerator", text: `Once the pieces match, add the tops. 3 eighths and 2 eighths make 5 eighths. The bottom names the piece size, so it stays 8.`,
          demo: { kind: "fraction", n: 5, d: 8, alt: "A bar cut into eighths. Five eighths fill in one at a time, and the total reads 5/8." }, try: { label: "Add 3/8 and 1/4", lab: "op:0,b:8,a:3,d:4,c:1" } },
        { c: "c1", title: "A part of a part", term: "product", text: `Half of <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup is <span class="m"><span class="fr"><span>1</span><span>2</span></span></span> × <span class="m"><span class="fr"><span>3</span><span>4</span></span></span>. Multiply the tops, then the bottoms: <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> cup. No common denominator needed.`,
          demo: { kind: "fraction", n: 3, d: 8, alt: "A bar cut into eighths with three shaded: 3/8, which is half of 3/4." }, try: { label: "Take 1/2 of 3/4", lab: "op:2,b:2,a:1,d:4,c:3" } },
        { c: "c3", title: "How many fit?", term: "reciprocal", text: `Dividing asks how many scoops fit. <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup holds three <span class="m"><span class="fr"><span>1</span><span>4</span></span></span>-cup scoops. Flip the second fraction, then multiply.`,
          demo: { kind: "fraction", n: 3, d: 4, cap: "quarter-cup scoops", alt: "A bar cut into quarters. Three quarter-cup scoops fill in one at a time to make 3/4 cup, so 3 scoops fit." }, try: { label: "Divide 3/4 by 1/4", lab: "op:3,b:4,a:3,d:4,c:1" } }
      ],
      timelineTitle: "People have shared things in parts for thousands of years",
      timelineLead: `Bakers, heirs and merchants all needed fair shares. The way we write a fraction today, one number over a bar over another, took about three thousand years to settle. It is the same form the model above shows.`,
      timeline: [
        { when: "About 1550 BCE", what: `In Egypt, the scribe Ahmose copies the Rhind papyrus. Its first problems share 1, 2, 6, 7, 8 and 9 loaves among 10 men.` },
        { when: "From about 400 CE", what: `In India, fractions are written as one number above another, with no bar. The Bakhshali manuscript, Brahmagupta (about 628) and Bhaskara (about 1150) describe them.` },
        { when: "About 1200", what: `Al-Hassar of Fez, in Morocco, an expert on dividing inheritances, writes the bar between top and bottom. It is the line in every fraction in the model.` },
        { when: "1202", what: `Leonardo of Pisa, known as Fibonacci, uses the fraction bar in <i>Liber Abaci</i>, a book of arithmetic for merchants: currency, measures, profit and interest.` }
      ],
      history: `<p><b>The problem.</b> Sharing food, land and pay fairly means dividing things that do not split evenly. The Rhind papyrus, copied by the Egyptian scribe Ahmose around 1550 BCE from an older text, opens with problems that share 1, 2, 6, 7, 8 and 9 loaves among 10 men, and later ones exchange bread for beer. Egyptian scribes wrote such shares as sums of unit fractions like <span class="m"><span class="fr"><span>1</span><span>3</span></span></span> and <span class="m"><span class="fr"><span>1</span><span>5</span></span></span>, which made combining them slow.</p>
<p><b>The solution.</b> In India, fractions came to be written as one number above another. They are described in the Bakhshali manuscript and by Brahmagupta (about 628) and Bhaskara (about 1150). The horizontal bar is first known from al-Hassar of Fez, around 1200, a specialist in dividing inheritances under Islamic law. It appears soon after in the work of Fibonacci, whose <i>Liber Abaci</i> (1202) taught merchants to work with currency, measures and profit.</p>
<p><b>What it changed.</b> With one number over another, any two fractions can be combined by a few short rules: a common denominator to add, straight across to multiply, the reciprocal to divide. Estates, business partnerships, recipes and tape-measure readings are still worked out with the rules in this lesson.</p>`,
      sources: [
        { title: "Rhind Mathematical Papyrus (Wikipedia)", url: "https://en.wikipedia.org/wiki/Rhind_Mathematical_Papyrus" },
        { title: "Fraction: history (Wikipedia)", url: "https://en.wikipedia.org/wiki/Fraction" },
        { title: "Abu Bakr al-Hassar (Wikipedia)", url: "https://en.wikipedia.org/wiki/Al-Hassar" },
        { title: "Liber Abaci (Wikipedia)", url: "https://en.wikipedia.org/wiki/Liber_Abaci" }
      ],
      matters: { title: "Why fractions need rules", text: `<p>Fractions are how people <b>share and measure</b> things that don't come out even.</p><ul class="why-chips"><li><b>Recipes</b> in cups</li><li><b>Lengths</b> in inches</li><li><b>Doses</b> in tablets</li></ul><p>Each operation has <b>its own rule</b>. Use the right rule and the answer is exact. Use the wrong one and the answer can <b>look fine and still be wrong</b>.</p>` },
      stakes: { title: "Where fraction math goes wrong", lead: `Most slips come from using one operation's rule for another.`, items: [
        { role: "Kitchen", text: `Adding tops and bottoms: <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> + <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> written as <span class="m"><span class="fr"><span>5</span><span>7</span></span></span> cup. That is less than the <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> cup you started with.` },
        { role: "Pharmacy", text: `Flipping the wrong fraction: <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> mg ÷ <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> mg done as <span class="m"><span class="fr"><span>4</span><span>3</span></span></span> × <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> gives <span class="m"><span class="fr"><span>1</span><span>3</span></span></span> tablet. The order needs 3 tablets.` },
        { role: "Workshop", text: `Subtracting mixed numbers without regrouping: <span class="m">3<span class="fr"><span>1</span><span>4</span></span></span> − <span class="m">1<span class="fr"><span>3</span><span>4</span></span></span> written as <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span> in. The right answer is <span class="m">1<span class="fr"><span>1</span><span>2</span></span></span> in.` }
      ], try: { label: "See 2/3 + 3/4 in the model", lab: "op:0,b:3,a:2,d:4,c:3" } },
      examplesTitle: "Where you will meet it",
      examples: [
        { role: "Carpenter", figure: "8 1/16 in", scene: `Two boards of <span class="m">5<span class="fr"><span>3</span><span>8</span></span></span> in and <span class="m">2<span class="fr"><span>11</span><span>16</span></span></span> in are joined end to end. In sixteenths: <span class="m"><span class="fr"><span>86</span><span>16</span></span> + <span class="fr"><span>43</span><span>16</span></span> = <span class="fr"><span>129</span><span>16</span></span> = </span><b><span class="m">8<span class="fr"><span>1</span><span>16</span></span></span> in</b>.`, takeaway: "A tape measure is marked in sixteenths, so sixteenths are the natural common denominator." },
        { role: "Baker", figure: "2 cups", scene: `A recipe uses <span class="m">2<span class="fr"><span>2</span><span>3</span></span></span> cups of flour, and you make <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> of the batch: <span class="m"><span class="fr"><span>8</span><span>3</span></span> × <span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>24</span><span>12</span></span> = </span><b>2 cups</b>.`, takeaway: "Scaling multiplies every amount by the same fraction, so the recipe keeps its balance." },
        { role: "Nurse", figure: "3 tablets", try: { label: "Divide 3/4 by 1/4", lab: "op:3,b:4,a:3,d:4,c:1" }, scene: `An order calls for <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> mg and each tablet is <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> mg: <span class="m"><span class="fr"><span>3</span><span>4</span></span> ÷ <span class="fr"><span>1</span><span>4</span></span> = <span class="fr"><span>3</span><span>4</span></span> × <span class="fr"><span>4</span><span>1</span></span> = </span><b>3 tablets</b>.`, takeaway: "Dividing a dose by a tablet strength counts how many tablets fit the order." },
        { role: "Musician", figure: "1 full bar", scene: `In 4/4 time, a bar holds a quarter note, two eighth notes and a half note: <span class="m"><span class="fr"><span>2</span><span>8</span></span> + <span class="fr"><span>1</span><span>8</span></span> + <span class="fr"><span>1</span><span>8</span></span> + <span class="fr"><span>4</span><span>8</span></span> = <span class="fr"><span>8</span><span>8</span></span> = 1</span>, <b>one full bar</b>.`, takeaway: "Note values are fractions, and a bar is correct when they sum to the time signature." },
        { role: "Tailor", figure: "13 3/4 in", scene: `A pattern piece is <span class="m">12<span class="fr"><span>1</span><span>2</span></span></span> in wide, plus a <span class="m"><span class="fr"><span>5</span><span>8</span></span></span> in seam allowance on each side: <span class="m">12<span class="fr"><span>4</span><span>8</span></span> + <span class="fr"><span>10</span><span>8</span></span> = </span><b><span class="m">13<span class="fr"><span>3</span><span>4</span></span></span> in</b> to cut.`, takeaway: "Forgetting one seam allowance makes a garment that does not fit." },
        { role: "Machinist", figure: "3 7/16 in", scene: `From 6 in of bar stock, a <span class="m">2<span class="fr"><span>7</span><span>16</span></span></span> in piece is cut with a <span class="m"><span class="fr"><span>1</span><span>8</span></span></span> in wide blade: <span class="m"><span class="fr"><span>96</span><span>16</span></span> − <span class="fr"><span>39</span><span>16</span></span> − <span class="fr"><span>2</span><span>16</span></span> = <span class="fr"><span>55</span><span>16</span></span> = </span><b><span class="m">3<span class="fr"><span>7</span><span>16</span></span></span> in</b> left.`, takeaway: "The width of the cut is a fraction too, and leaving it out wastes material." }
      ]
    },
    build: {
      lede: `To add or subtract, rename both fractions over a common denominator; to multiply, go straight across; to divide, multiply by the reciprocal; then reduce.`,
      task: { text: "Pick the rule that fits, then reduce.", sub: `Adding and subtracting need one piece size. Multiplying and dividing do not. Try each step in the model above as you go.`,
        figure: { sym: `<i>R</i>`, value: "11", cap: "the answer's top number, in the model", echo: "num" },
        jump: [{ label: "The method", to: "b-method" }, { label: "Everyday tasks", to: "b-tasks" }] },
      keysTitle: "What the model shows",
      intro: `<p>The model above changes with the operation. For + and −, the top bars show <span class="c2"><i>a</i>/<i>b</i></span> and <span class="c3"><i>c</i>/<i>d</i></span>, the bars below re-cut both into the <span class="c4">common denominator</span> (violet lines), and the bottom bar shows the <span class="c1">result</span>. For ×, a grid shades <span class="c2"><i>a</i>/<i>b</i></span> as columns and <span class="c3"><i>c</i>/<i>d</i></span> as rows, and the overlap is the product. For ÷, segments the size of <span class="c3"><i>c</i>/<i>d</i></span> are laid along <span class="c2"><i>a</i>/<i>b</i></span> to count how many fit.</p>`,
      keyTry: [{ label: "Set the first to 5/6", lab: "op:0,b:6,a:5,d:4,c:1" }, { label: "Set the second to 2/3", lab: "op:0,b:2,a:1,d:3,c:2" }, { label: "Show 1/4 + 1/6 in twelfths", lab: "op:0,b:4,a:1,d:6,c:1" }, { label: "Switch to ×", lab: "op:2,b:3,a:2,d:4,c:3" }],
      objects: ["cup", "cups", "oil", "board", "strip", "veneer", "flour", "bag", "coffee", "pot", "pots", "pizza", "cells", "cell", "pieces", "piece", "twelfths", "eighths", "twentieths", "scoop", "scoops"],
      goalsIntro: `Three of the steps have a move for you to make in the model. Make the move, then press <b>Check my move</b>. A move also ticks itself off as soon as the model shows it.`,
      stepWhy: [
        `Only same-sized pieces can be counted together. The LCM of the denominators is the smallest piece size both fractions can be cut into exactly, which keeps the numbers small.`,
        `Multiplying top and bottom by the same number multiplies by 1, so the value does not change: <span class="m"><span class="fr"><span>2</span><span>3</span></span> × <span class="fr"><span>4</span><span>4</span></span> = <span class="fr"><span>8</span><span>12</span></span></span> is still two thirds of a cup.`,
        `Once the pieces match, the numerator counts pieces and the denominator names their size. 8 twelfths and 9 twelfths make 17 twelfths; the size stays twelfths.`,
        `Taking a fraction of a fraction cuts a part into smaller parts. The denominators multiply to give the new piece size, and the numerators count how many are kept. Cancelling first removes the same factor you would remove at the end.`,
        `Dividing asks how many copies of the divisor fit. Multiplying by <i>d</i>/<i>c</i> undoes multiplying by <i>c</i>/<i>d</i>, so the reciprocal answers that question: <span class="m"><span class="fr"><span>9</span><span>4</span></span> ÷ <span class="fr"><span>3</span><span>8</span></span> = <span class="fr"><span>9</span><span>4</span></span> × <span class="fr"><span>8</span><span>3</span></span> = 6</span>.`,
        `Lowest terms make answers quicker to compare and check. A mixed number like <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> is how cups, inches and hours are usually read.`
      ],
      stepTry: [{ label: "Show 2/3 + 3/4", lab: "op:0,b:3,a:2,d:4,c:3" }, { label: "Show 3/8 + 1/4", lab: "op:0,b:8,a:3,d:4,c:1" }, null, null, null, { label: "Show 1/6 + 1/3", lab: "op:0,b:6,a:1,d:3,c:1" }],
      stepGoal: [null, null,
        { key: "num", eq: 23, text: `Set the model to <span class="m"><span class="fr"><span>2</span><span>5</span></span></span> + <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> yourself. Read the common denominator, then add the tops.`, after: `Twentieths fit both: <span class="m"><span class="fr"><span>8</span><span>20</span></span> + <span class="fr"><span>15</span><span>20</span></span> = <span class="fr"><span>23</span><span>20</span></span></span>. The bottom stays 20.`, notYet: `Not yet. Set the first fraction to 2/5, the second to 3/4, and the sign to +.` },
        { key: "den", eq: 35, text: `Find <span class="m"><span class="fr"><span>3</span><span>5</span></span></span> × <span class="m"><span class="fr"><span>4</span><span>7</span></span></span> in the model.`, after: `Multiply straight across: 3 × 4 = 12 on top, 5 × 7 = 35 below. The answer is <span class="m"><span class="fr"><span>12</span><span>35</span></span></span>.`, notYet: `Not yet. Set the first fraction to 3/5, the second to 4/7, and the sign to ×.` },
        { key: "num", eq: 15, text: `How many <span class="m"><span class="fr"><span>2</span><span>9</span></span></span>-cup scoops fit in <span class="m"><span class="fr"><span>5</span><span>6</span></span></span> cup? Set up <span class="m"><span class="fr"><span>5</span><span>6</span></span></span> ÷ <span class="m"><span class="fr"><span>2</span><span>9</span></span></span> in the model.`, after: `Flip the second and multiply: <span class="m"><span class="fr"><span>5</span><span>6</span></span> × <span class="fr"><span>9</span><span>2</span></span> = <span class="fr"><span>45</span><span>12</span></span> = <span class="fr"><span>15</span><span>4</span></span> = 3<span class="fr"><span>3</span><span>4</span></span></span> scoops.`, notYet: `Not yet. Set the first fraction to 5/6, the second to 2/9, and the sign to ÷.` },
        null],
      matters: { title: "Why Each Operation Has Its Own Rule", text: `<p>The four operations ask four different questions. A rule that answers one can give a wrong answer to another, and the wrong answer often <b>looks reasonable</b>.</p><ul class="why-chips"><li><b>Add</b> and <b>subtract</b>: one piece size first</li><li><b>Multiply</b>: straight across</li><li><b>Divide</b>: flip the second</li></ul><p>A method makes you <b>name the operation first</b>. Then you pick its rule, work it, and reduce. Each step is short enough to check.</p>` },
      bridge: `<p>The flour in the walk used the add rule: one piece size, then add the tops. Each task below uses one of the four rules. Name the operation first, then work it.</p>`,
      tasksTitle: "Everyday tasks: solve them",
      tasks: [
        { task: "Halving a recipe", check: { q: `A recipe needs <span class="m"><span class="fr"><span>2</span><span>3</span></span></span> cup of oil. You make half the recipe. How much oil do you need?`, parts: [{ label: "top", ans: 1 }, { label: "bottom", ans: 3 }], hint: `Half of means × <span class="m"><span class="fr"><span>1</span><span>2</span></span></span>. Multiply the tops, then the bottoms, then reduce.` }, figure: "1/3 cup",
          demo: { kind: "fraction", n: 1, d: 3, split: 2, alt: "A bar cut into thirds with one third shaded, then every third cut in half: 2/6 is the same amount as 1/3." },
          lines: [{ math: `<span class="m"><span class="fr"><span>1</span><span>2</span></span> × <span class="fr"><span>2</span><span>3</span></span></span>`, note: "Half of an amount means times one half." }, { math: `<span class="m"><span class="fr"><span>1 × 2</span><span>2 × 3</span></span> = <span class="fr"><span>2</span><span>6</span></span></span>`, note: "Multiply the tops, then the bottoms." }, { math: `<span class="m"><span class="fr"><span>2</span><span>6</span></span> = <span class="fr"><span>1</span><span>3</span></span></span>`, note: "Divide the top and the bottom by 2. You need 1/3 cup." }],
          predict: [null, { ask: `What is 2 × 3 on the bottom?`, parts: [{ label: "bottom", ans: 6 }], hint: `The bottoms multiply, the same as the tops.` }, null],
          try: { label: "Show 1/2 × 2/3", lab: "op:2,b:2,a:1,d:3,c:2" }, link: `This is step 4: multiply straight across. Unlike the flour in the walk, no common denominator is needed.` },
        { task: "Adding lengths on a tape measure", check: { q: `A shelf board is <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> in thick. You glue on a strip of veneer <span class="m"><span class="fr"><span>1</span><span>8</span></span></span> in thick. How thick is it now?`, parts: [{ label: "top", ans: 7 }, { label: "bottom", ans: 8 }], hint: `Write <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> in eighths first.` }, figure: "7/8 in",
          demo: { kind: "fraction", n: 3, d: 4, split: 2, alt: "A bar cut into quarters with three shaded, then every quarter cut in half: 3/4 becomes 6/8." },
          lines: [{ math: `<span class="m c4">lcm(4, 8) = 8</span>`, note: "Eighths fit both. A quarter is two eighths." }, { math: `<span class="m"><span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>6</span><span>8</span></span></span>`, note: "Multiply the top and the bottom by 2." }, { math: `<span class="m"><span class="fr"><span>6</span><span>8</span></span> + <span class="fr"><span>1</span><span>8</span></span> = <span class="fr"><span>7</span><span>8</span></span></span>`, note: "Add the tops. The board is 7/8 in thick." }],
          predict: [null, { ask: `<span class="m"><span class="fr"><span>3</span><span>4</span></span></span> is how many eighths?`, parts: [{ label: "eighths", ans: 6 }], hint: `Each quarter is 2 eighths.` }, null],
          try: { label: "Show 3/4 + 1/8", lab: "op:0,b:4,a:3,d:8,c:1" }, link: `Steps 1 to 3, as in the walk: one piece size, then add the tops. A tape measure is marked in eighths and sixteenths, so those are the usual common denominators.` },
        { task: "Seeing how much is left in a bag", check: { q: `Your flour bag held <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span> cups. The cookies and bread used <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups. How much flour is left?`, parts: [{ label: "whole cups", ans: 1 }, { label: "twelfths", ans: 1 }], hint: `Write <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span> in twelfths: <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span> = <span class="m"><span class="fr"><span>5</span><span>2</span></span></span> = <span class="m"><span class="fr"><span>30</span><span>12</span></span></span>.` }, figure: "1 1/12 cups",
          demo: { kind: "fraction", n: 13, d: 12, mixed: true, alt: "Two bars cut into twelfths. Thirteen twelfths fill in, one whole bar and one more piece, and the total reads 1 1/12." },
          lines: [{ math: `<span class="m">2<span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>5</span><span>2</span></span> = <span class="fr"><span>30</span><span>12</span></span></span>`, note: "Write the bag in twelfths too." }, { math: `<span class="m"><span class="fr"><span>30</span><span>12</span></span> − <span class="fr"><span>17</span><span>12</span></span> = <span class="fr"><span>13</span><span>12</span></span></span>`, note: "Subtract the tops. The piece size stays twelfths." }, { math: `<span class="m"><span class="fr"><span>13</span><span>12</span></span> = 1<span class="fr"><span>1</span><span>12</span></span></span>`, note: "Twelve twelfths make a cup, with 1 twelfth over." }],
          predict: [null, { ask: `What is <span class="m"><span class="fr"><span>30</span><span>12</span></span></span> − <span class="m"><span class="fr"><span>17</span><span>12</span></span></span>, in twelfths?`, parts: [{ label: "twelfths", ans: 13 }], hint: `Subtract the tops: 30 − 17.` }, null],
          link: `It finishes the flour from the walk on the Concept tab. The pieces are still twelfths, and step 3 is now a subtraction.` },
        { task: "Working out how many portions are in a bag", check: { q: `A bag holds <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> lb of coffee. Each pot uses <span class="m"><span class="fr"><span>1</span><span>8</span></span></span> lb. How many pots can you brew?`, parts: [{ label: "pots", ans: 6 }], hint: `Divide by <span class="m"><span class="fr"><span>1</span><span>8</span></span></span>: multiply by <span class="m"><span class="fr"><span>8</span><span>1</span></span></span>.` }, figure: "6 pots",
          demo: { kind: "fraction", n: 6, d: 8, alt: "A bar cut into eighths. Six eighths fill in one at a time, one per pot, the same amount as 3/4." },
          lines: [{ math: `<span class="m"><span class="fr"><span>3</span><span>4</span></span> ÷ <span class="fr"><span>1</span><span>8</span></span></span>`, note: "How many 1/8 lb portions fit in 3/4 lb?" }, { math: `<span class="m"><span class="fr"><span>3</span><span>4</span></span> × <span class="fr"><span>8</span><span>1</span></span> = <span class="fr"><span>24</span><span>4</span></span></span>`, note: "Keep the first, flip the second, multiply." }, { math: `<span class="m"><span class="fr"><span>24</span><span>4</span></span> = 6</span>`, note: "You can brew 6 pots." }],
          predict: [null, { ask: `What is 3 × 8 on top?`, parts: [{ label: "top", ans: 24 }], hint: `3 eights.` }, null],
          try: { label: "Show 3/4 ÷ 1/8", lab: "op:3,b:4,a:3,d:8,c:1" }, link: `Step 5: dividing asks how many fit, and the reciprocal answers it.` },
        { task: "Finding a share of a share", check: { q: `<span class="m"><span class="fr"><span>3</span><span>4</span></span></span> of a pizza is left. You eat <span class="m"><span class="fr"><span>1</span><span>3</span></span></span> of what is left. What fraction of the whole pizza did you eat?`, parts: [{ label: "top", ans: 1 }, { label: "bottom", ans: 4 }], hint: `<span class="m"><span class="fr"><span>1</span><span>3</span></span></span> of <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> means <span class="m"><span class="fr"><span>1</span><span>3</span></span></span> × <span class="m"><span class="fr"><span>3</span><span>4</span></span></span>.` }, figure: "1/4 pizza",
          demo: { kind: "array", rows: 3, cols: 4, unit: "cell", alt: "A grid of 3 rows and 4 columns fills in row by row and makes 12 equal cells, so the new piece size is twelfths." },
          lines: [{ math: `<span class="m"><span class="fr"><span>1</span><span>3</span></span> × <span class="fr"><span>3</span><span>4</span></span></span>`, note: "Of means times." }, { math: `<span class="m"><span class="fr"><span>1 × 3</span><span>3 × 4</span></span> = <span class="fr"><span>3</span><span>12</span></span></span>`, note: "Cut the pizza 3 by 4 ways: 12 cells. You ate 3 of them." }, { math: `<span class="m"><span class="fr"><span>3</span><span>12</span></span> = <span class="fr"><span>1</span><span>4</span></span></span>`, note: "Divide the top and the bottom by 3." }],
          predict: [null, { ask: `How many cells does a 3 by 4 grid have?`, parts: [{ label: "cells", ans: 12 }], hint: `3 rows of 4.` }, null],
          try: { label: "Show 1/3 × 3/4", lab: "op:2,b:3,a:1,d:4,c:3" }, link: `Steps 4 and 6: multiply across, then reduce. In the model, × shades the overlap of two strips the same way.` }
      ]
    },
    formal: {
      question: { text: "How are the four operations on fractions defined?", sub: `You can pick the rule for each operation and work it. Here are the words a textbook uses for the same ideas, and how to write a fraction problem out in full.`,
        figure: { sym: `<i>q</i>`, value: "12", cap: "denominator of the result, lowest terms", echo: "den" },
        jump: [{ label: "Vocabulary", to: "f-vocab" }, { label: "Where it goes wrong", to: "f-mist" }, { label: "Writing it out", to: "f-setup" }, { label: "Practice", to: "f-prac" }] },
      vocabTitle: "From your words to the textbook's",
      vocabIntro: `<p>Each card is an idea you already used in the Concept and Intermediate tabs, with its proper name and its exact meaning.</p>`,
      vocab: [
        { c: "c2", sym: `<span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span>`, term: "Numerator and denominator", def: `In <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span> with <span class="m"><i>b</i> ≠ 0</span>, the integer <i>a</i> is the numerator and <i>b</i> the denominator. The denominator names the size of the parts; the numerator counts them.`, was: "the top and the bottom" },
        { c: "c4", sym: `lcm(<i>b</i>, <i>d</i>)`, term: "Least common denominator", def: `The least common multiple of the denominators: the smallest positive integer divisible by both <i>b</i> and <i>d</i>.`, was: "one piece size both fit into" },
        { c: "c4", sym: `<span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span> = <span class="m"><span class="fr"><span><i>ak</i></span><span><i>bk</i></span></span></span>`, term: "Equivalent fractions", def: `Fractions that name the same rational number: <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> = <span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span> exactly when <span class="m"><i>ad</i> = <i>bc</i></span>. Multiplying numerator and denominator by the same nonzero <i>k</i> gives an equivalent fraction.`, was: "cutting every piece into smaller ones" },
        { c: "c1", sym: `<span class="m"><span class="fr"><span><i>ac</i></span><span><i>bd</i></span></span></span>`, term: "Product", def: `The result of multiplication: <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> · <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ac</i></span><span><i>bd</i></span></span></span>. In a word problem, “of” after a fraction usually signals a product.`, was: "a part of a part" },
        { c: "c3", sym: `<span class="m"><span class="fr"><span><i>d</i></span><span><i>c</i></span></span></span>`, term: "Reciprocal (multiplicative inverse)", def: `For <span class="m"><span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span> with <span class="m"><i>c</i>, <i>d</i> ≠ 0</span>, the fraction <span class="m"><span class="fr"><span><i>d</i></span><span><i>c</i></span></span></span>, since their product is 1. Zero has no reciprocal.`, was: "the second fraction flipped" },
        { c: "c1", sym: `<span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span> ÷ <span class="m"><span class="fr"><span><i>c</i></span><span><i>d</i></span></span></span>`, term: "Quotient", def: `The number <i>q</i> with <span class="m"><i>q</i> · <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>a</i></span><span><i>b</i></span></span></span>, defined for <span class="m"><i>c</i> ≠ 0</span>. It equals <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> · <span class="fr"><span><i>d</i></span><span><i>c</i></span></span></span>.`, was: "how many fit" },
        { c: "c1", sym: `gcd(<i>p</i>, <i>q</i>) = 1`, term: "Lowest terms", def: `A fraction <span class="m"><span class="fr"><span><i>p</i></span><span><i>q</i></span></span></span> is in lowest terms when <span class="m">gcd(<i>p</i>, <i>q</i>) = 1</span>. Dividing numerator and denominator by their gcd reduces any fraction to lowest terms.`, was: "reducing the answer" }
      ],
      matters: { title: "Why the exact words matter", text: `<p>“Divide by one half” and “divide in half” sound alike. They are <b>different operations</b> with different answers.</p><ul class="why-chips"><li><span class="m"><span class="fr"><span>3</span><span>4</span></span> ÷ <span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>3</span><span>2</span></span></span></li><li><span class="m"><span class="fr"><span>3</span><span>4</span></span> ÷ 2 = <span class="fr"><span>3</span><span>8</span></span></span></li><li>One answer is <b>4 times</b> the other</li></ul><p>Reading the words exactly tells you which fraction is the <b>divisor</b>, and so which one to flip.</p>` },
      mistakesTitle: "Where formal answers go wrong",
      mistakesLead: `Most wrong answers use one operation's rule for another: adding denominators, flipping the wrong fraction, or skipping a regroup.`,
      setupIntro: `<p>The flour from the Concept walk, written the way a textbook would. It adds one more question: how much is left in the bag.</p>`,
      setup: { title: "Writing a fraction problem", items: [
        { say: `<b>Name the amounts.</b> Give each a letter and say what it stands for, with units.`, math: `<span class="m"><span class="c2"><i>x</i></span> = <span class="fr"><span>2</span><span>3</span></span></span> cup (cookies), &nbsp;<span class="m"><span class="c3"><i>y</i></span> = <span class="fr"><span>3</span><span>4</span></span></span> cup (bread), &nbsp;<span class="m"><i>F</i> = 2<span class="fr"><span>1</span><span>2</span></span></span> cups (bag)` },
        { say: `<b>Write the expressions.</b> Flour used is the sum; flour left is the bag minus the amount used.`, math: `<span class="m"><i>u</i> = <span class="c2"><i>x</i></span> + <span class="c3"><i>y</i></span></span>, &nbsp;<span class="m"><i>r</i> = <i>F</i> − <i>u</i></span>` },
        { say: `<b>Justify the common denominator.</b> Multiplying by <span class="m"><span class="fr"><span><i>k</i></span><span><i>k</i></span></span> = 1</span> keeps the value and changes only the form. Here <span class="m c4">lcm(3, 4) = 12</span>.`, math: `<span class="m"><span class="fr"><span>2</span><span>3</span></span> = <span class="fr"><span>2·4</span><span>3·4</span></span> = <span class="fr"><span>8</span><span>12</span></span></span>, &nbsp;<span class="m"><span class="fr"><span>3</span><span>4</span></span> = <span class="fr"><span>3·3</span><span>4·3</span></span> = <span class="fr"><span>9</span><span>12</span></span></span>, &nbsp;<span class="m">2<span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>30</span><span>12</span></span></span>` },
        { say: `<b>Compute.</b> Add and subtract numerators over the common denominator.`, math: `<span class="m"><i>u</i> = <span class="fr"><span>8</span><span>12</span></span> + <span class="fr"><span>9</span><span>12</span></span> = <span class="c1"><span class="fr"><span>17</span><span>12</span></span></span></span>, &nbsp;<span class="m"><i>r</i> = <span class="fr"><span>30</span><span>12</span></span> − <span class="fr"><span>17</span><span>12</span></span> = <span class="c1"><span class="fr"><span>13</span><span>12</span></span></span></span>` },
        { say: `<b>Answer in a sentence.</b> State both results with units, as mixed numbers.`, math: `You use <span class="m">1<span class="fr"><span>5</span><span>12</span></span></span> cups and have <span class="m">1<span class="fr"><span>1</span><span>12</span></span></span> cups left.` }
      ] },
      practiceTip: `Type your answer and press Check. For a fraction, type the top and the bottom in lowest terms. Stuck? Each one has a hint.`,
      practiceDone: "All 5 solved. You can add, subtract, multiply and divide fractions the formal way.",
      checks: [
        { hint: `Write <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> in eighths, then add the tops.`, parts: [{ label: "numerator", ans: 5 }, { label: "denominator", ans: 8 }] },
        { hint: `The LCD of 4 and 6 is 12. Subtract <span class="m"><span class="fr"><span>9</span><span>12</span></span></span> from <span class="m"><span class="fr"><span>10</span><span>12</span></span></span>.`, parts: [{ label: "numerator", ans: 1 }, { label: "denominator", ans: 12 }] },
        { hint: `“Of” means times. Cancel common factors before you multiply.`, parts: [{ label: "numerator", ans: 1 }, { label: "denominator", ans: 6 }] },
        { hint: `Write <span class="m">2<span class="fr"><span>1</span><span>4</span></span></span> as <span class="m"><span class="fr"><span>9</span><span>4</span></span></span>, then multiply by the reciprocal of <span class="m"><span class="fr"><span>3</span><span>8</span></span></span>.`, parts: [{ label: "servings", ans: 6 }] },
        { hint: `Solve <span class="m"><i>n</i> × <span class="fr"><span>5</span><span>8</span></span> = <span class="fr"><span>15</span><span>4</span></span></span> by multiplying both sides by <span class="m"><span class="fr"><span>8</span><span>5</span></span></span>.`, parts: [{ label: "pieces n", ans: 6 }] }
      ]
    }
  },
  prereqWhy: {
    "fractions": "You need to understand what a fraction means and how to make equivalent fractions before you can combine them.",
    "gcf-lcm": "The least common denominator is the LCM of the denominators, and reducing results uses the GCF."
  },
  unlocksWhy: {
    "proportions": "Solving a proportion means working with equal fractions, cross-multiplying and simplifying.",
    "real-numbers": "The rational numbers ℚ are defined by fractions, and their closure under these four operations is a key property of the number system."
  },
  beyond: [
    { field: "Algebra I", why: "Solving equations with fractional coefficients and clearing denominators uses these rules directly." },
    { field: "Algebra II", why: "Rational expressions are added, subtracted, multiplied and divided with exactly the same procedures." },
    { field: "Calculus", why: "Partial fractions and simplifying difference quotients depend on fluent fraction algebra." }
  ],
  mistakes: [
    { wrong: `<span class="m"><span class="fr"><span>1</span><span>2</span></span> + <span class="fr"><span>1</span><span>3</span></span> = <span class="fr"><span>2</span><span>5</span></span></span> (adding tops and bottoms).`, fix: `Use a common denominator: <span class="m"><span class="fr"><span>3</span><span>6</span></span> + <span class="fr"><span>2</span><span>6</span></span> = <span class="fr"><span>5</span><span>6</span></span></span>. A sum of two positive numbers cannot be smaller than one of them, and 2/5 is less than 1/2.` },
    { wrong: `Flipping the first fraction when dividing: <span class="m"><span class="fr"><span>2</span><span>3</span></span> ÷ <span class="fr"><span>4</span><span>5</span></span> = <span class="fr"><span>3</span><span>2</span></span> × <span class="fr"><span>4</span><span>5</span></span></span>.`, fix: `Flip only the divisor: <span class="m"><span class="fr"><span>2</span><span>3</span></span> × <span class="fr"><span>5</span><span>4</span></span> = <span class="fr"><span>10</span><span>12</span></span> = <span class="fr"><span>5</span><span>6</span></span></span>.` },
    { wrong: `Finding a common denominator before multiplying.`, fix: `It gives the right answer but adds work. For multiplication, multiply straight across: <span class="m"><span class="fr"><span><i>a</i></span><span><i>b</i></span></span> × <span class="fr"><span><i>c</i></span><span><i>d</i></span></span> = <span class="fr"><span><i>ac</i></span><span><i>bd</i></span></span></span>.` },
    { wrong: `Subtracting mixed numbers part by part without regrouping: <span class="m">3<span class="fr"><span>1</span><span>4</span></span> − 1<span class="fr"><span>3</span><span>4</span></span></span> written as <span class="m">2<span class="fr"><span>1</span><span>2</span></span></span>, by taking 1/4 from 3/4 instead.`, fix: `Regroup 1 from the 3: <span class="m">3<span class="fr"><span>1</span><span>4</span></span> = 2<span class="fr"><span>5</span><span>4</span></span></span>, so <span class="m">2<span class="fr"><span>5</span><span>4</span></span> − 1<span class="fr"><span>3</span><span>4</span></span> = 1<span class="fr"><span>2</span><span>4</span></span> = 1<span class="fr"><span>1</span><span>2</span></span></span>. Or use improper fractions: <span class="m"><span class="fr"><span>13</span><span>4</span></span> − <span class="fr"><span>7</span><span>4</span></span> = <span class="fr"><span>6</span><span>4</span></span> = 1<span class="fr"><span>1</span><span>2</span></span></span>.` }
  ],
  practice: [
    { ctx: "Cooking", q: `You pour <span class="m"><span class="fr"><span>1</span><span>4</span></span></span> cup of milk, then <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> cup more. How much milk is that?`, a: `<span class="m"><span class="fr"><span>2</span><span>8</span></span> + <span class="fr"><span>3</span><span>8</span></span> = <span class="fr"><span>5</span><span>8</span></span></span>, so <b>5/8 cup</b>.` },
    { ctx: "Work", q: `A project was <span class="m"><span class="fr"><span>3</span><span>4</span></span></span> done at mid-morning and <span class="m"><span class="fr"><span>5</span><span>6</span></span></span> done at lunch. What fraction of the project was done in between?`, a: `LCD 12: <span class="m"><span class="fr"><span>10</span><span>12</span></span> − <span class="fr"><span>9</span><span>12</span></span> = <span class="fr"><span>1</span><span>12</span></span></span>, so <b>1/12 of the project</b>.` },
    { ctx: "Gardening", q: `Vegetables fill <span class="m"><span class="fr"><span>4</span><span>9</span></span></span> of a garden, and tomatoes fill <span class="m"><span class="fr"><span>3</span><span>8</span></span></span> of the vegetable area. What fraction of the garden is tomatoes?`, a: `<span class="m"><span class="fr"><span>4</span><span>9</span></span> × <span class="fr"><span>3</span><span>8</span></span></span>. Cancel first: <span class="m"><span class="fr"><span>1</span><span>3</span></span> × <span class="fr"><span>1</span><span>2</span></span> = <span class="fr"><span>1</span><span>6</span></span></span> (check: 12/72 = 1/6). <b><span class="m"><span class="fr"><span>1</span><span>6</span></span></span> of the garden</b>.` },
    { ctx: "Food", q: `A container holds <span class="m">2<span class="fr"><span>1</span><span>4</span></span></span> cups of yogurt. How many <span class="m"><span class="fr"><span>3</span><span>8</span></span></span>-cup servings is that?`, a: `<span class="m"><span class="fr"><span>9</span><span>4</span></span> ÷ <span class="fr"><span>3</span><span>8</span></span> = <span class="fr"><span>9</span><span>4</span></span> × <span class="fr"><span>8</span><span>3</span></span> = <span class="fr"><span>72</span><span>12</span></span> = 6</span> servings.` },
    { ctx: "Crafts", q: `Write an equation with a letter for the unknown, then solve: a ribbon <span class="m">3<span class="fr"><span>3</span><span>4</span></span></span> yd long is cut into pieces <span class="m"><span class="fr"><span>5</span><span>8</span></span></span> yd long. How many pieces <i>n</i> do you get?`, a: `<span class="m"><i>n</i> × <span class="fr"><span>5</span><span>8</span></span> = <span class="fr"><span>15</span><span>4</span></span></span>, so <span class="m"><i>n</i> = <span class="fr"><span>15</span><span>4</span></span> × <span class="fr"><span>8</span><span>5</span></span> = <span class="fr"><span>120</span><span>20</span></span> = 6</span>. You get <b>6 pieces</b>.` }
  ],
  origin: `Egyptian scribes of the Rhind papyrus (about 1550 BCE) shared loaves using sums of unit fractions such as 1/3 and 1/5. Indian texts, from the Bakhshali manuscript to Brahmagupta (about 628) and Bhaskara (about 1150), wrote one number above another. The horizontal bar is first known from al-Hassar of Fez (about 1200) and appears in Fibonacci's <i>Liber Abaci</i> (1202).`
};
