/* Glossary: Mathematics. Spec: web/GLOSSARY-SPEC.md. */
DB.addGlossary("mathematics", [
  { w: "root", field: "arithmetic", node: "roots", pos: "n", ipa: "/rut/",
    senses: ["A number that, used as a factor a given number of times, gives a given number: 3 is a square root of 9 (3 · 3 = 9) and the cube root of 27 (√9, ∛27).",
      "A solution of an equation, or a zero of a polynomial: the roots of <i>x</i>² − 5<i>x</i> + 6 = 0 are 2 and 3."], forms: ["roots"] },
  { w: "degree", field: "algebra-2", node: "a2-poly-graphs", pos: "n", ipa: "/dɪˈɡri/",
    senses: ["The highest exponent of the variable in a polynomial: 4<i>x</i>³ − <i>x</i> + 2 has degree 3.", "A unit of angle measure, 1/360 of a full turn (°)."], forms: ["degrees"] },
  { w: "function", field: "algebra-1", node: "a1-functions", pos: "n", ipa: "/ˈfʌŋkʃən/",
    senses: ["A rule that assigns to each input exactly one output, written <i>f</i>(<i>x</i>); the inputs form the domain and the outputs the range."], forms: ["functions"] },
  { w: "interval", field: "algebra-1", node: "a1-compound", pos: "n", ipa: "/ˈɪntɚvəl/",
    senses: ["The set of all real numbers between two endpoints, written in interval notation: [2, 5) means 2 ≤ <i>x</i> &lt; 5; a bracket includes an endpoint and a parenthesis excludes it."], forms: ["intervals"] },
  { w: "scale", field: "geometry", node: "g-dilations", pos: "n", ipa: "/skeɪl/",
    senses: ["<b>Scale factor</b>: the ratio of a length in the image to the matching length in the original, under a dilation or in a scale drawing. A factor greater than 1 enlarges; between 0 and 1 it reduces."], forms: ["scales"] },
  { w: "factor", field: "arithmetic", node: "factors", pos: "n", ipa: "/ˈfæktɚ/",
    senses: ["A number or expression that divides another exactly: 3 and 4 are factors of 12, and (<i>x</i> − 2) is a factor of <i>x</i>² − 4."], forms: ["factors"] },
  { w: "power", field: "arithmetic", node: "exponents", pos: "n", ipa: "/ˈpaʊɚ/",
    senses: ["A product of equal factors, written with an exponent: 2⁵ = 2 · 2 · 2 · 2 · 2 is the fifth power of 2.", "The exponent itself, as in <i>raised to the power 5</i>."], forms: ["powers"] },
  { w: "variable", field: "pre-algebra", node: "pa-variables", pos: "n", ipa: "/ˈvɛriəbəl/", syl: "var·i·a·ble",
    senses: ["A letter or symbol that stands for a number that can change or is not yet known."], forms: ["variables"] },
  { w: "measure", field: "geometry", node: "g-angles", pos: "n", ipa: "/ˈmɛʒɚ/",
    senses: ["The size of an angle in degrees, written m∠<i>A</i>; also the length of a segment."], forms: ["measures"] },
  { w: "period", field: "trigonometry", node: "trig-sinusoids", pos: "n", ipa: "/ˈpɪriəd/",
    senses: ["The length of the shortest interval over which a periodic function repeats: sin <i>x</i> has period 2π."], forms: ["periods"] },
  /* Arithmetic */
  { w: "natural number", field: "arithmetic", node: "counting", pos: "n", ipa: "/ˈnætʃɚəl ˈnʌmbɚ/",
    senses: ["One of the counting numbers 1, 2, 3, …, the set ℕ. Many texts, especially in set theory and computer science, also count 0 as natural and write ℕ = {0, 1, 2, …}, so check a book's convention: 7 is natural under both, 0 under only the second."],
    forms: ["natural numbers"], see: ["whole number", "successor"] },
  { w: "whole number", field: "arithmetic", node: "counting", pos: "n", ipa: "/ˈhoʊl ˈnʌmbɚ/",
    senses: ["One of the numbers 0, 1, 2, 3, …: the natural numbers together with 0, sometimes written 𝕎. 0 and 15 are whole numbers; −2 and ½ are not."],
    forms: ["whole numbers"], see: ["natural number", "integer"] },
  { w: "successor", field: "arithmetic", node: "counting", pos: "n", ipa: "/səkˈsɛsɚ/", syl: "suc·ces·sor",
    senses: ["The natural number that comes right after a given one, <i>n</i> + 1: the successor of 9 is 10 and the successor of 99 is 100. Every natural number has a successor, so the counting numbers never run out."],
    origin: "Latin <i>successor</i> ‘one who follows’, from <i>succedere</i> ‘to come after’",
    forms: ["successors"], see: ["successor function"] },
  { w: "successor function", field: "arithmetic", node: "counting", pos: "n", ipa: "/səkˈsɛsɚ ˈfʌŋkʃən/",
    senses: ["The function <i>S</i>(<i>n</i>) = <i>n</i> + 1 on the natural numbers, taken as basic in the Peano axioms: it is one-to-one (different inputs give different outputs) and never returns the starting element. Addition can be built from it: <i>a</i> + 0 = <i>a</i> and <i>a</i> + <i>S</i>(<i>b</i>) = <i>S</i>(<i>a</i> + <i>b</i>), so 3 + 2 = <i>S</i>(<i>S</i>(3)) = 5."],
    forms: ["successor functions"], see: ["successor", "Peano axioms", "function"] },
  { w: "Peano axioms", field: "arithmetic", node: "counting", pos: "n", ipa: "/peɪˈɑnoʊ ˈæksiəmz/",
    senses: ["A short list of axioms that characterise the natural numbers: there is a starting element; every number has a successor; the successor function is one-to-one and never gives the starting element; and the axiom of induction holds. All of whole-number arithmetic can be derived from them."],
    origin: "after the Italian mathematician Giuseppe Peano, who published them in 1889",
    see: ["successor function", "mathematical induction"] },
  { w: "cardinality", field: "arithmetic", node: "counting", pos: "n", ipa: "/ˌkɑrdəˈnæləti/", syl: "car·di·nal·i·ty",
    senses: ["The number of elements in a set, written |<i>A</i>|. A finite set <i>A</i> has cardinality <i>n</i> when its elements can be matched one-to-one with {1, 2, …, <i>n</i>}: |{red, green, blue}| = 3."],
    origin: "from <i>cardinal</i> (number), Latin <i>cardinalis</i> ‘principal’, from <i>cardo</i> ‘hinge’",
    forms: ["cardinalities"], see: ["one-to-one correspondence"] },
  { w: "one-to-one correspondence", field: "arithmetic", node: "counting", pos: "n", ipa: "/ˈwʌn tə ˈwʌn ˌkɔrəˈspɑndəns/",
    senses: ["A pairing of the elements of two sets in which each element of either set is matched with exactly one element of the other (a <i>bijection</i>). Counting five apples pairs them with {1, 2, 3, 4, 5}; two sets have the same cardinality exactly when such a pairing exists."],
    forms: ["one-to-one correspondences"], see: ["cardinality"] },
  { w: "mathematical induction", field: "arithmetic", node: "counting", pos: "n", ipa: "/ˌmæθəˈmætɪkəl ɪnˈdʌkʃən/",
    senses: ["A method of proof for statements about every natural number: prove the statement for the starting value (base case), then prove that whenever it holds for <i>n</i> it also holds for <i>n</i> + 1 (inductive step). Example: 1 + 2 + ⋯ + <i>n</i> = <i>n</i>(<i>n</i> + 1)/2 holds for <i>n</i> = 1, and adding <i>n</i> + 1 to both sides carries it from <i>n</i> to <i>n</i> + 1.",
      "The Peano axiom behind this method: any set that contains the starting element and contains the successor of each of its members contains every natural number."],
    see: ["Peano axioms", "successor"] },

  { w: "digit", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ˈdɪdʒɪt/", syl: "dig·it",
    senses: ["One of the ten symbols 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 used to write numbers in base ten. The number 4,306 is written with four digits."],
    origin: "Latin <i>digitus</i> ‘finger, toe’, from counting on the fingers",
    forms: ["digits"], see: ["numeral", "place value"] },
  { w: "numeral", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ˈnumɚəl/", syl: "nu·mer·al",
    senses: ["A written symbol or string of symbols that names a number, as distinct from the number itself: 12, XII and twelve are three numerals for one number."],
    origin: "Late Latin <i>numeralis</i> ‘of number’, from <i>numerus</i> ‘number’",
    forms: ["numerals"], see: ["digit"] },
  { w: "place value", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ˈpleɪs ˌvælju/",
    senses: ["The amount a digit stands for because of its position: the digit times the power of ten for its place. In 4,306 the 3 has place value 3 × 10² = 300; each place is worth ten times the place to its right."],
    forms: ["place values"], confused: [["face value", "the digit itself, ignoring its position"]], see: ["face value", "base ten", "digit"] },
  { w: "face value", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ˈfeɪs ˌvælju/",
    senses: ["The value of a digit on its own, regardless of where it stands: in 4,306 the 3 has face value 3 but place value 300."],
    forms: ["face values"], see: ["place value"] },
  { w: "base ten", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ˈbeɪs ˈtɛn/",
    senses: ["The decimal positional system, in which each place is worth ten times the place to its right and the digits 0–9 are used: 507 means 5 × 10² + 0 × 10¹ + 7 × 10⁰. Every positive whole number has exactly one base-ten numeral with a nonzero leading digit."],
    see: ["place value", "expanded form", "digit"] },
  { w: "expanded form", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ɪkˈspændɪd ˈfɔrm/",
    senses: ["A number written as the sum of the place values of its digits: 4,306 = 4,000 + 300 + 6, or, with powers of ten, 4 × 10³ + 3 × 10² + 0 × 10¹ + 6 × 10⁰."],
    see: ["standard form", "place value"] },
  { w: "standard form", field: "arithmetic", node: "place-value", pos: "n", ipa: "/ˈstændɚd ˈfɔrm/",
    senses: ["A number written the usual way, as a string of digits: the standard form of 4,000 + 300 + 6 is 4,306.",
      "In other settings the phrase names other agreed layouts: in algebra a line in standard form is <i>Ax</i> + <i>By</i> = <i>C</i>, and in British usage it means scientific notation, as in 4.306 × 10³."],
    see: ["expanded form"] },

  { w: "number line", field: "arithmetic", node: "number-line", pos: "n", ipa: "/ˈnʌmbɚ ˌlaɪn/",
    senses: ["A straight line on which each number is a point, with 0 marked, equal spacing for equal differences, and larger numbers to the right. On it, 3 &lt; 7 because 3 lies to the left of 7, and the distance between them is 4."],
    forms: ["number lines"], see: ["distance", "inequality"] },
  { w: "inequality", field: "arithmetic", node: "number-line", pos: "n", ipa: "/ˌɪnɪˈkwɑləti/", syl: "in·e·qual·i·ty",
    senses: ["A statement that compares two quantities with &lt;, &gt;, ≤, ≥ or ≠: 3 &lt; 7 (3 is less than 7) and <i>x</i> ≥ 2 are inequalities. The open side of &lt; or &gt; faces the larger number."],
    forms: ["inequalities"], see: ["number line", "trichotomy", "interval"] },
  { w: "trichotomy", field: "arithmetic", node: "number-line", pos: "n", ipa: "/traɪˈkɑtəmi/", syl: "tri·chot·o·my",
    senses: ["<b>Trichotomy law</b>: for any two real numbers <i>a</i> and <i>b</i>, exactly one of <i>a</i> &lt; <i>b</i>, <i>a</i> = <i>b</i>, <i>a</i> &gt; <i>b</i> is true. For 5 and 8, only 5 &lt; 8 holds."],
    origin: "Greek <i>trikha</i> ‘in three’ + <i>-tomia</i> ‘cutting’",
    forms: ["trichotomies"], see: ["total order", "transitive property"] },
  { w: "transitive property", field: "arithmetic", node: "number-line", pos: "n", ipa: "/ˈtrænsətɪv ˈprɑpɚti/",
    senses: ["The rule that a relation carries through a middle term: if <i>a</i> &lt; <i>b</i> and <i>b</i> &lt; <i>c</i>, then <i>a</i> &lt; <i>c</i> (2 &lt; 5 and 5 &lt; 9 give 2 &lt; 9). Equality is transitive too: if <i>a</i> = <i>b</i> and <i>b</i> = <i>c</i>, then <i>a</i> = <i>c</i>."],
    see: ["trichotomy", "total order"] },
  { w: "midpoint", field: "arithmetic", node: "number-line", pos: "n", ipa: "/ˈmɪdˌpɔɪnt/", syl: "mid·point",
    senses: ["The number halfway between two numbers <i>a</i> and <i>b</i>, equal to (<i>a</i> + <i>b</i>) ÷ 2: the midpoint of 3 and 11 is 7, which is 4 from each.",
      "In geometry, the point that divides a segment into two segments of equal length."],
    forms: ["midpoints"], see: ["number line", "distance"] },
  { w: "distance", field: "arithmetic", node: "number-line", pos: "n", ipa: "/ˈdɪstəns/", syl: "dis·tance",
    senses: ["The length of the gap between two points on a number line, |<i>a</i> − <i>b</i>|, which is the larger minus the smaller and is never negative: the distance between 3 and 7 is 4, and so is the distance between 7 and 3."],
    forms: ["distances"], see: ["absolute value", "number line"] },
  { w: "total order", field: "arithmetic", node: "number-line", pos: "n", ipa: "/ˈtoʊtəl ˈɔrdɚ/",
    senses: ["An ordering of a set in which every two elements can be compared and the comparison is consistent: it obeys trichotomy (exactly one of <i>a</i> &lt; <i>b</i>, <i>a</i> = <i>b</i>, <i>a</i> &gt; <i>b</i>) and is transitive. The usual &lt; is a total order on the whole numbers, integers and reals; it lets every set of numbers be placed on a single line."],
    forms: ["total orders"], see: ["trichotomy", "transitive property"] },

  { w: "addend", field: "arithmetic", node: "addition", pos: "n", ipa: "/ˈædɛnd/", syl: "ad·dend",
    senses: ["Any of the numbers being added: in 3 + 4 = 7, the addends are 3 and 4."],
    origin: "short for Latin <i>addendum</i> ‘thing to be added’, from <i>addere</i> ‘to add’",
    forms: ["addends"], see: ["sum"] },
  { w: "sum", field: "arithmetic", node: "addition", pos: "n", ipa: "/sʌm/",
    senses: ["The result of adding numbers: the sum of 3 and 4 is 7. For sets, the sum of the sizes of two disjoint sets is the size of their union."],
    origin: "Latin <i>summa</i> ‘the top, the total’; Romans added columns upward and wrote the total at the top",
    forms: ["sums"], see: ["addend"] },
  { w: "carry", field: "arithmetic", node: "addition", pos: "v", ipa: "/ˈkæri/", syl: "car·ry",
    senses: ["In column addition, to move a full group of ten from one place to the next place to the left when the digits in a place add to 10 or more: in 58 + 27, the ones give 15, so write 5 and carry 1 ten to the tens column, giving 85."],
    forms: ["carries", "carried", "carrying"], see: ["regrouping", "place value"] },
  { w: "regrouping", field: "arithmetic", node: "addition", pos: "n", ipa: "/riˈɡrupɪŋ/", syl: "re·group·ing",
    senses: ["Exchanging ten units of one place for one unit of the next place, or the reverse, without changing the number's value. It is the idea behind carrying in addition (15 ones become 1 ten and 5 ones) and borrowing in subtraction (1 ten becomes 10 ones, so 53 is treated as 4 tens and 13 ones)."],
    see: ["carry", "borrow", "place value"] },

  { w: "round", field: "arithmetic", node: "rounding", pos: "v", ipa: "/raʊnd/",
    senses: ["To replace a number by the nearest multiple of a chosen place value (ten, hundred, a tenth, …): 4,372 rounded to the nearest hundred is 4,400 because it lies past the halfway point 4,350. The digit just right of the rounding place decides: 0–4 round down, 5–9 round up."],
    forms: ["rounds", "rounded", "rounding"], see: ["estimate", "rounding error", "round half to even"] },
  { w: "estimate", field: "arithmetic", node: "rounding", pos: "n", ipa: "/ˈɛstəmət/", syl: "es·ti·mate",
    senses: ["An approximate value, usually found by computing with rounded numbers: 4,372 + 2,815 is about 4,400 + 2,800 = 7,200, an estimate that shows the exact sum 7,187 is reasonable."],
    origin: "Latin <i>aestimare</i> ‘to value, appraise’",
    forms: ["estimates"], see: ["round"] },
  { w: "estimate", field: "arithmetic", node: "rounding", pos: "v", ipa: "/ˈɛstəˌmeɪt/", syl: "es·ti·mate",
    senses: ["To find an approximate value, usually by rounding first and then calculating with the easier numbers: estimate 38 × 61 as 40 × 60 = 2,400 (the exact product is 2,318)."],
    origin: "Latin <i>aestimare</i> ‘to value, appraise’",
    forms: ["estimates", "estimated", "estimating"], see: ["round"] },
  { w: "rounding error", field: "arithmetic", node: "rounding", pos: "n", ipa: "/ˈraʊndɪŋ ˌɛrɚ/",
    senses: ["The difference between a rounded value and the exact value, |round(<i>x</i>) − <i>x</i>|. Rounding 4,372 to the nearest hundred gives error 28; rounding to the nearest multiple of <i>u</i> never errs by more than <i>u</i>/2."],
    forms: ["rounding errors"], see: ["round"] },
  { w: "round half to even", field: "arithmetic", node: "rounding", pos: "n", ipa: "/ˈraʊnd ˈhæf tə ˈivən/",
    senses: ["A tie-breaking rule for rounding that sends a number exactly halfway between two neighbours to the one whose last kept digit is even: 4,350 → 4,400 but 4,250 → 4,200, and 2.5 → 2 but 3.5 → 4. Also called <i>banker's rounding</i>, it avoids the upward bias of always rounding halves up and is the default in IEEE 754 floating-point arithmetic."],
    see: ["round", "rounding error"] },

  { w: "product", field: "arithmetic", node: "multiplication", pos: "n", ipa: "/ˈprɑdʌkt/", syl: "prod·uct",
    senses: ["The result of multiplying numbers: the product of 4 and 6 is 24. For sets, <i>a</i> × <i>b</i> counts the ordered pairs that can be formed from sets of sizes <i>a</i> and <i>b</i>."],
    origin: "Latin <i>productum</i> ‘something brought forth’, from <i>producere</i>",
    forms: ["products"], confused: [["factor", "one of the numbers being multiplied, not the result"]], see: ["factor", "multiplicand", "partial product"] },
  { w: "multiplicand", field: "arithmetic", node: "multiplication", pos: "n", ipa: "/ˌmʌltəplɪˈkænd/", syl: "mul·ti·pli·cand",
    senses: ["The number that is multiplied by another (the multiplier). Read as “<i>a</i> groups of <i>b</i>”, <i>a</i> × <i>b</i> has multiplicand <i>b</i>: in 4 × 6 for 4 bags of 6 marbles, 6 is the multiplicand. Conventions differ between books, and since multiplication is commutative both numbers are usually just called factors."],
    origin: "Latin <i>multiplicandus</i> ‘to be multiplied’",
    forms: ["multiplicands"], see: ["multiplier", "factor", "product"] },
  { w: "multiplier", field: "arithmetic", node: "multiplication", pos: "n", ipa: "/ˈmʌltəˌplaɪɚ/", syl: "mul·ti·pli·er",
    senses: ["The number by which another is multiplied; in 4 × 6 read as 4 groups of 6, the 4 counts the groups and is the multiplier."],
    forms: ["multipliers"], see: ["multiplicand", "factor"] },
  { w: "partial product", field: "arithmetic", node: "multiplication", pos: "n", ipa: "/ˈpɑrʃəl ˈprɑdʌkt/",
    senses: ["One of the smaller products made by splitting the factors by place value, which add up to the full product: 23 × 47 = 20 × 40 + 20 × 7 + 3 × 40 + 3 × 7 = 800 + 140 + 120 + 21 = 1,081. The method rests on the distributive property."],
    forms: ["partial products"], see: ["product", "distributive property"] },
  { w: "zero property", field: "arithmetic", node: "multiplication", pos: "n", ipa: "/ˈzɪroʊ ˈprɑpɚti/",
    senses: ["<b>Zero property of multiplication</b>: any number times 0 is 0, <i>a</i> × 0 = 0 (so 857 × 0 = 0). It follows from the distributive, identity and additive inverse laws. Not to be confused with the <i>zero-product property</i> of algebra: if <i>ab</i> = 0, then <i>a</i> = 0 or <i>b</i> = 0."],
    see: ["product", "identity element"] },

  { w: "minuend", field: "arithmetic", node: "subtraction", pos: "n", ipa: "/ˈmɪnjuˌɛnd/", syl: "min·u·end",
    senses: ["The number from which another is subtracted: in 9 − 4 = 5, the minuend is 9."],
    origin: "Latin <i>minuendus</i> ‘to be made smaller’, from <i>minuere</i> ‘to lessen’",
    forms: ["minuends"], see: ["subtrahend", "difference"] },
  { w: "subtrahend", field: "arithmetic", node: "subtraction", pos: "n", ipa: "/ˈsʌbtrəˌhɛnd/", syl: "sub·tra·hend",
    senses: ["The number being subtracted: in 9 − 4 = 5, the subtrahend is 4."],
    origin: "Latin <i>subtrahendus</i> ‘to be drawn away’, from <i>subtrahere</i> ‘to take away’",
    forms: ["subtrahends"], see: ["minuend", "difference"] },
  { w: "difference", field: "arithmetic", node: "subtraction", pos: "n", ipa: "/ˈdɪfɚəns/", syl: "dif·fer·ence",
    senses: ["The result of subtracting one number from another: the difference 9 − 4 is 5, the unique number <i>d</i> with <i>d</i> + 4 = 9. It answers both “how many are left?” and “how many more?”."],
    forms: ["differences"], see: ["minuend", "subtrahend", "inverse operation"] },
  { w: "borrow", field: "arithmetic", node: "subtraction", pos: "v", ipa: "/ˈbɑroʊ/", syl: "bor·row",
    senses: ["In column subtraction, to take one unit from the next place to the left and turn it into ten units of the current place when the top digit is too small: in 53 − 28, 3 − 8 is impossible, so borrow a ten to make 13 − 8 = 5, leaving 4 − 2 = 2 tens, so the answer is 25. The minuend's value does not change."],
    forms: ["borrows", "borrowed", "borrowing"], see: ["regrouping", "carry"] },
  { w: "inverse operation", field: "arithmetic", node: "subtraction", pos: "n", ipa: "/ˈɪnvɝs ˌɑpəˈreɪʃən/",
    senses: ["An operation that undoes another: subtraction undoes addition (7 + 5 − 5 = 7) and division undoes multiplication (6 × 3 ÷ 3 = 6). A subtraction can be checked with its inverse: 9 − 4 = 5 because 5 + 4 = 9."],
    forms: ["inverse operations"], see: ["difference", "additive inverse"] },

  { w: "commutative property", field: "arithmetic", node: "properties", pos: "n", ipa: "/kəˈmjutətɪv ˈprɑpɚti/",
    senses: ["The law that the order of two operands does not change the result: <i>a</i> + <i>b</i> = <i>b</i> + <i>a</i> and <i>ab</i> = <i>ba</i>, as in 3 + 5 = 5 + 3 and 3 × 5 = 5 × 3. Subtraction and division are not commutative: 9 − 4 ≠ 4 − 9."],
    origin: "from <i>commute</i>, Latin <i>commutare</i> ‘to exchange’",
    see: ["associative property", "distributive property"] },
  { w: "associative property", field: "arithmetic", node: "properties", pos: "n", ipa: "/əˈsoʊʃiˌeɪtɪv ˈprɑpɚti/",
    senses: ["The law that grouping does not change the result when the same operation is repeated: (<i>a</i> + <i>b</i>) + <i>c</i> = <i>a</i> + (<i>b</i> + <i>c</i>) and (<i>ab</i>)<i>c</i> = <i>a</i>(<i>bc</i>), so (2 + 7) + 3 = 2 + (7 + 3) = 12. Subtraction and division are not associative: (8 − 4) − 2 = 2 but 8 − (4 − 2) = 6."],
    see: ["commutative property", "distributive property"] },
  { w: "distributive property", field: "arithmetic", node: "properties", pos: "n", ipa: "/dɪˈstrɪbjətɪv ˈprɑpɚti/",
    senses: ["The law linking multiplication and addition: <i>a</i>(<i>b</i> + <i>c</i>) = <i>ab</i> + <i>ac</i>, so 6 × 14 = 6 × 10 + 6 × 4 = 60 + 24 = 84. It underlies the multiplication algorithms and, read right to left, factoring in algebra."],
    see: ["partial product", "commutative property", "associative property"] },
  { w: "identity element", field: "arithmetic", node: "properties", pos: "n", ipa: "/aɪˈdɛntəti ˈɛləmənt/",
    senses: ["A number that leaves every number unchanged under an operation: 0 is the additive identity (<i>a</i> + 0 = <i>a</i>) and 1 is the multiplicative identity (<i>a</i> · 1 = <i>a</i>), as in 8 + 0 = 8 and 8 × 1 = 8."],
    forms: ["identity elements"], see: ["additive inverse", "multiplicative inverse"] },
  { w: "multiplicative inverse", field: "arithmetic", node: "properties", pos: "n", ipa: "/ˌmʌltəˈplɪkətɪv ɪnˈvɝs/",
    senses: ["For a nonzero number <i>a</i>, the number 1/<i>a</i> whose product with <i>a</i> is the identity 1, also called the reciprocal: 5 × 1/5 = 1. It exists in the rationals ℚ and reals ℝ for every number except 0, but not within the integers (1/5 ∉ ℤ)."],
    forms: ["multiplicative inverses"], see: ["additive inverse", "identity element", "field"] },
  { w: "field", field: "arithmetic", node: "properties", pos: "n", ipa: "/fild/",
    senses: ["A set with an addition and a multiplication that obey the commutative, associative and distributive laws, have identities 0 and 1 (with 0 ≠ 1), and give every element an additive inverse and every nonzero element a multiplicative inverse. The rationals ℚ and reals ℝ are fields; the integers ℤ are not, since 2 has no integer reciprocal."],
    forms: ["fields"], see: ["identity element", "additive inverse", "multiplicative inverse"] },

  { w: "dividend", field: "arithmetic", node: "division", pos: "n", ipa: "/ˈdɪvəˌdɛnd/", syl: "div·i·dend",
    senses: ["The number being divided: in 12 ÷ 3 = 4, the dividend is 12. In the division algorithm, dividend = divisor × quotient + remainder."],
    origin: "Latin <i>dividendum</i> ‘thing to be divided’, from <i>dividere</i>",
    forms: ["dividends"], see: ["divisor", "quotient", "remainder"] },
  { w: "divisor", field: "arithmetic", node: "division", pos: "n", ipa: "/dɪˈvaɪzɚ/", syl: "di·vi·sor",
    senses: ["The number by which another is divided: in 12 ÷ 3 = 4, the divisor is 3.",
      "A number that divides another exactly, with remainder 0; the same as a factor: the divisors of 12 are 1, 2, 3, 4, 6 and 12."],
    origin: "Latin <i>divisor</i> ‘one who divides’, from <i>dividere</i>",
    forms: ["divisors"], see: ["dividend", "quotient", "factor"] },
  { w: "quotient", field: "arithmetic", node: "division", pos: "n", ipa: "/ˈkwoʊʃənt/", syl: "quo·tient",
    senses: ["The result of a division: 12 ÷ 3 has quotient 4. When the division is not exact, the whole-number quotient counts the complete groups: 14 ÷ 3 has quotient 4 and remainder 2."],
    origin: "Latin <i>quotiens</i> ‘how many times’",
    forms: ["quotients"], see: ["dividend", "divisor", "remainder", "division algorithm"] },
  { w: "remainder", field: "arithmetic", node: "division", pos: "n", ipa: "/rɪˈmeɪndɚ/", syl: "re·main·der",
    senses: ["The amount left over when a whole number is divided into equal whole groups; it is always at least 0 and less than the divisor. Sharing 14 among 3 gives 4 each with remainder 2, since 14 = 3 × 4 + 2."],
    forms: ["remainders"], see: ["quotient", "division algorithm"] },
  { w: "division algorithm", field: "arithmetic", node: "division", pos: "n", ipa: "/dɪˈvɪʒən ˈælɡəˌrɪðəm/",
    senses: ["The theorem that for any integers <i>a</i> and <i>b</i> with <i>b</i> &gt; 0 there are unique integers <i>q</i> and <i>r</i> with <i>a</i> = <i>bq</i> + <i>r</i> and 0 ≤ <i>r</i> &lt; <i>b</i>: for 47 and 5, 47 = 5 × 9 + 2. Despite the name it is a statement, not a procedure; long division is one way to find <i>q</i> and <i>r</i>."],
    see: ["quotient", "remainder", "dividend", "divisor"] },
  { w: "undefined", field: "arithmetic", node: "division", pos: "aj", ipa: "/ˌʌndɪˈfaɪnd/", syl: "un·de·fined",
    senses: ["Having no value under the rules of the operation. Division by zero is undefined: 5 ÷ 0 would need a number <i>q</i> with 0 × <i>q</i> = 5, and none exists, while 0 ÷ 0 fits every <i>q</i>, so no single answer can be chosen. Likewise 3 − 8 is undefined within the whole numbers."],
    see: ["divisor", "quotient"] },

  { w: "integer", field: "arithmetic", node: "integers", pos: "n", ipa: "/ˈɪntədʒɚ/", syl: "in·te·ger",
    senses: ["A whole number or the opposite of one: a member of ℤ = {…, −3, −2, −1, 0, 1, 2, 3, …}. −7, 0 and 12 are integers; ½ and 0.3 are not. ℤ is closed under addition, subtraction and multiplication but not division."],
    origin: "Latin <i>integer</i> ‘whole, untouched’",
    forms: ["integers"], see: ["whole number", "negative number", "opposite"] },
  { w: "negative number", field: "arithmetic", node: "integers", pos: "n", ipa: "/ˈnɛɡətɪv ˈnʌmbɚ/",
    senses: ["A number less than 0, lying to the left of 0 on the number line and written with a minus sign: −3 °C is 3 degrees below zero. 0 itself is neither positive nor negative."],
    forms: ["negative numbers"], see: ["integer", "opposite", "number line"] },
  { w: "opposite", field: "arithmetic", node: "integers", pos: "n", ipa: "/ˈɑpəzɪt/", syl: "op·po·site",
    senses: ["The number the same distance from 0 on the other side of the number line: the opposite of 5 is −5, the opposite of −5 is 5, and the opposite of 0 is 0. A number plus its opposite is 0."],
    forms: ["opposites"], syn: [["additive inverse", "the same number, named by the property <i>a</i> + (−<i>a</i>) = 0"]], see: ["additive inverse", "absolute value"] },
  { w: "additive inverse", field: "arithmetic", node: "integers", pos: "n", ipa: "/ˈædətɪv ɪnˈvɝs/",
    senses: ["For a number <i>a</i>, the unique number −<i>a</i> with <i>a</i> + (−<i>a</i>) = 0: the additive inverse of 8 is −8 and of −8 is 8. Subtraction is defined by it: <i>a</i> − <i>b</i> = <i>a</i> + (−<i>b</i>), so 6 − (−4) = 6 + 4 = 10."],
    forms: ["additive inverses"], see: ["opposite", "identity element", "multiplicative inverse"] },
  { w: "absolute value", field: "arithmetic", node: "integers", pos: "n", ipa: "/ˈæbsəˌlut ˈvælju/",
    senses: ["The distance of a number from 0 on the number line, written |<i>a</i>|; it is never negative: |−6| = 6 and |6| = 6. Equivalently |<i>a</i>| = <i>a</i> if <i>a</i> ≥ 0 and −<i>a</i> if <i>a</i> &lt; 0, and |<i>a</i> − <i>b</i>| is the distance between <i>a</i> and <i>b</i>."],
    forms: ["absolute values"], see: ["distance", "opposite"] },
  { w: "closure", field: "arithmetic", node: "integers", pos: "n", ipa: "/ˈkloʊʒɚ/", syl: "clo·sure",
    senses: ["The property that an operation on members of a set always gives a member of the same set; the set is then <i>closed</i> under the operation. The integers are closed under subtraction (3 − 8 = −5 ∈ ℤ) but not under division (1 ÷ 2 ∉ ℤ); the whole numbers are not closed under subtraction."],
    forms: ["closed"], see: ["integer", "whole number"] },
  { w: "exponent", field: "arithmetic", node: "exponents", pos: "n", ipa: "/ɪkˈspoʊnənt/", syl: "ex·po·nent",
    senses: ["The small raised number in a power that says how many times the base is used as a factor: in 2<sup>5</sup> = 2 × 2 × 2 × 2 × 2 = 32 the exponent is 5.",
      "For a nonzero base the definition extends to zero and negative integers so that the laws of exponents still hold: <i>b</i><sup>0</sup> = 1 and 2<sup>−3</sup> = 1/2<sup>3</sup> = 1/8."],
    origin: "Latin <i>exponent-</i>, present participle of <i>exponere</i> ‘to put out, set forth’",
    forms: ["exponents"], see: ["base", "power"] },
  { w: "exponentiation", field: "arithmetic", node: "exponents", pos: "n", ipa: "/ˌɛkspoʊˌnɛnʃiˈeɪʃən/", syl: "ex·po·nen·ti·a·tion",
    senses: ["The operation of raising a base to an exponent, <i>b</i><sup><i>n</i></sup>. Unlike addition and multiplication it is neither commutative nor associative: 2<sup>3</sup> = 8 but 3<sup>2</sup> = 9, and a tower such as 2<sup>3<sup>2</sup></sup> is read top-down as 2<sup>9</sup>."],
    see: ["exponent", "power"] },
  { w: "base", field: "arithmetic", node: "exponents", pos: "n", ipa: "/beɪs/",
    senses: ["In a power <i>b</i><sup><i>n</i></sup>, the number <i>b</i> that is multiplied by itself: in 5<sup>3</sup> = 125 the base is 5.",
      "The number of digits a place-value system uses, so that each place is worth that many times the place to its right: in base ten 10 ones make a ten."],
    forms: ["bases"], see: ["exponent", "power"] },
  { w: "square", field: "arithmetic", node: "exponents", pos: "n", ipa: "/skwɛr/",
    senses: ["The second power of a number, the product of the number with itself: 7<sup>2</sup> = 49, so 49 is the square of 7. The name comes from the area of a square with that side length.",
      "A quadrilateral with four equal sides and four right angles."],
    forms: ["squares"], see: ["cube", "square root", "perfect square"] },
  { w: "square", field: "arithmetic", node: "exponents", pos: "v", ipa: "/skwɛr/",
    senses: ["To raise a number to the second power, that is, multiply it by itself: squaring −3 gives (−3)<sup>2</sup> = 9."],
    forms: ["squares", "squared", "squaring"], see: ["square root"] },
  { w: "cube", field: "arithmetic", node: "exponents", pos: "n", ipa: "/kjub/",
    senses: ["The third power of a number, the number used three times as a factor: 4<sup>3</sup> = 4 × 4 × 4 = 64, the volume of a cube with edge 4.",
      "A solid with six square faces, all edges equal."],
    forms: ["cubes", "cubed"], see: ["square", "power"] },

  { w: "order of operations", field: "arithmetic", node: "order-ops", pos: "n", ipa: "/ˈɔrdɚ əv ˌɑpəˈreɪʃənz/",
    senses: ["The agreed convention for evaluating an expression with several operations: grouping symbols first, then exponents, then multiplication and division from left to right, then addition and subtraction from left to right. So 3 + 4 × 2 = 3 + 8 = 11, not 14."],
    syn: [["PEMDAS", "a memory aid for the same convention"]], see: ["precedence", "grouping symbol", "left-associative"] },
  { w: "PEMDAS", field: "arithmetic", node: "order-ops", pos: "n", ipa: "/ˈpɛmdɑs/",
    senses: ["A memory aid for the order of operations: Parentheses, Exponents, Multiplication and Division, Addition and Subtraction (BODMAS in British usage). M and D share one level, as do A and S, each worked left to right: 12 ÷ 3 × 2 = 4 × 2 = 8."],
    see: ["order of operations"] },
  { w: "precedence", field: "arithmetic", node: "order-ops", pos: "n", ipa: "/ˈprɛsɪdəns/", syl: "prec·e·dence",
    senses: ["The rank of an operation in the order of operations, which decides which is performed first when no grouping symbols say otherwise: multiplication has higher precedence than addition, so 2 + 3 × 5 = 17."],
    see: ["order of operations", "left-associative"] },
  { w: "grouping symbol", field: "arithmetic", node: "order-ops", pos: "n", ipa: "/ˈɡrupɪŋ ˈsɪmbəl/",
    senses: ["A symbol that marks part of an expression to be evaluated first: parentheses ( ), brackets [ ], braces { }, a fraction bar, a radical sign or absolute-value bars. (3 + 4) × 2 = 14, and a fraction bar groups its whole numerator and denominator: (6 + 4)/2 = 5."],
    forms: ["grouping symbols"], see: ["order of operations"] },
  { w: "left-associative", field: "arithmetic", node: "order-ops", pos: "aj", ipa: "/ˌlɛft əˈsoʊʃiˌeɪtɪv/",
    senses: ["Of operations of equal precedence: grouped from the left when written in a row, so <i>a</i> − <i>b</i> + <i>c</i> means (<i>a</i> − <i>b</i>) + <i>c</i> and 12 ÷ 3 × 2 means (12 ÷ 3) × 2 = 8. Exponentiation is the exception: towers are grouped from the right."],
    see: ["precedence", "order of operations"] },

  { w: "multiple", field: "arithmetic", node: "factors", pos: "n", ipa: "/ˈmʌltəpəl/", syl: "mul·ti·ple",
    senses: ["A product of a given number and an integer: the multiples of 3 are …, −3, 0, 3, 6, 9, 12, …. In symbols, <i>n</i> is a multiple of <i>a</i> when <i>n</i> = <i>ak</i> for some integer <i>k</i>."],
    confused: [["factor", "the reverse relation: 12 is a multiple of 3, and 3 is a factor of 12"]],
    forms: ["multiples"], see: ["divisible", "factor"] },
  { w: "divisible", field: "arithmetic", node: "factors", pos: "aj", ipa: "/dɪˈvɪzəbəl/", syl: "di·vis·i·ble",
    senses: ["Of an integer: able to be divided by a given nonzero integer with remainder 0. 84 is divisible by 7 because 84 = 7 × 12; written 7 | 84."],
    forms: ["divisibility"], see: ["multiple", "divisibility rule", "factor"] },
  { w: "divisibility rule", field: "arithmetic", node: "factors", pos: "n", ipa: "/dɪˌvɪzəˈbɪlɪti ˌrul/",
    senses: ["A shortcut that tests whether an integer is divisible by a given number by looking at its digits rather than dividing: a number is divisible by 3 (or 9) when its digit sum is, so 4,617 (digit sum 18) is divisible by 9; by 4 when its last two digits form a multiple of 4."],
    forms: ["divisibility rules"], see: ["divisible"] },
  { w: "even", field: "arithmetic", node: "factors", pos: "aj", ipa: "/ˈivən/", syl: "e·ven",
    senses: ["Of an integer: divisible by 2, that is, of the form 2<i>k</i> for an integer <i>k</i>: −4, 0, 6 and 38 are even. In base ten an integer is even exactly when its last digit is 0, 2, 4, 6 or 8."],
    ant: ["odd"], see: ["odd", "divisible"] },
  { w: "odd", field: "arithmetic", node: "factors", pos: "aj", ipa: "/ɑd/",
    senses: ["Of an integer: not divisible by 2, so that it leaves remainder 1 when divided by 2; of the form 2<i>k</i> + 1: −3, 1 and 27 are odd."],
    ant: ["even"], see: ["even"] },

  { w: "modular arithmetic", field: "arithmetic", node: "modular", pos: "n", ipa: "/ˈmɑdʒəlɚ əˈrɪθmətɪk/",
    senses: ["Arithmetic on integers in which numbers that leave the same remainder after division by a fixed modulus <i>m</i> are treated as equal, so counting wraps around after <i>m</i>: mod 12, 9 + 5 = 14 ≡ 2. Sums and products may be reduced before or after the operation with the same result."],
    syn: [["clock arithmetic", "informal name, after the 12-hour clock"]], see: ["modulus", "congruent", "clock arithmetic"] },
  { w: "modulus", field: "arithmetic", node: "modular", pos: "n", ipa: "/ˈmɑdʒələs/", syl: "mod·u·lus",
    senses: ["The positive integer <i>m</i> after which modular arithmetic wraps around; remainders are taken on division by <i>m</i>. Days of the week use modulus 7: 100 days after a Monday is a Tuesday, since 100 = 7 × 14 + 2."],
    origin: "Latin <i>modulus</i> ‘small measure’, diminutive of <i>modus</i> ‘measure’",
    forms: ["moduli"], see: ["modular arithmetic", "congruent"] },
  { w: "congruent", field: "arithmetic", node: "modular", pos: "aj", ipa: "/kənˈɡruənt/", syl: "con·gru·ent",
    senses: ["<b>Congruent modulo <i>m</i></b>: of two integers <i>a</i> and <i>b</i>, having the same remainder on division by <i>m</i>, equivalently <i>m</i> | (<i>a</i> − <i>b</i>); written <i>a</i> ≡ <i>b</i> (mod <i>m</i>). 38 ≡ 14 (mod 12), since 38 − 14 = 24 = 12 × 2.",
      "In geometry, of figures: having the same size and shape."],
    origin: "Latin <i>congruent-</i>, from <i>congruere</i> ‘to agree, come together’",
    forms: ["congruence", "congruences"], see: ["modulus", "modular arithmetic"] },
  { w: "clock arithmetic", field: "arithmetic", node: "modular", pos: "n", ipa: "/ˈklɑk əˈrɪθmətɪk/",
    senses: ["An informal name for modular arithmetic, from reading times on a clock face: on a 12-hour clock, 5 hours after 9 o'clock is 2 o'clock, because 9 + 5 = 14 ≡ 2 (mod 12)."],
    register: "informal", see: ["modular arithmetic", "modulus"] },

  { w: "square root", field: "arithmetic", node: "roots", pos: "n", ipa: "/ˈskwɛr ˈrut/",
    senses: ["A number whose square is a given number: 5 and −5 are both square roots of 25. Every positive number has two square roots, opposite in sign; 0 has one; negative numbers have none among the real numbers.",
      "The non-negative one of these, written with √ (the principal square root): √25 = 5 and √20 ≈ 4.47, the side of a square of area 20."],
    forms: ["square roots"], see: ["principal square root", "perfect square", "radical", "root"] },
  { w: "perfect square", field: "arithmetic", node: "roots", pos: "n", ipa: "/ˈpɝfɪkt ˈskwɛr/",
    senses: ["An integer that is the square of an integer, <i>A</i> = <i>k</i><sup>2</sup>: 0, 1, 4, 9, 16, 25, 36, …. Its square root is a whole number; the square root of any other positive integer, such as √2, is irrational."],
    forms: ["perfect squares"], see: ["square", "square root"] },
  { w: "principal square root", field: "arithmetic", node: "roots", pos: "n", ipa: "/ˈprɪnsəpəl ˈskwɛr ˈrut/",
    senses: ["For a real number <i>A</i> ≥ 0, the unique non-negative number <i>s</i> with <i>s</i><sup>2</sup> = <i>A</i>, written √<i>A</i>: √49 = 7, not −7. So the equation <i>x</i><sup>2</sup> = 49 has two solutions, <i>x</i> = ±√49 = ±7, and √(<i>x</i><sup>2</sup>) = |<i>x</i>|."],
    forms: ["principal square roots"], see: ["square root", "radical"] },
  { w: "radical", field: "arithmetic", node: "roots", pos: "n", ipa: "/ˈrædɪkəl/", syl: "rad·i·cal",
    senses: ["The root symbol √ (the <b>radical sign</b>), or an expression written with it: √36 = 6 and ∛8 = 2 are radicals. The bar over the radicand acts as a grouping symbol: √(9 + 16) = √25 = 5."],
    origin: "Late Latin <i>radicalis</i>, from Latin <i>radix</i> ‘root’",
    forms: ["radicals"], see: ["radicand", "square root", "root"] },
  { w: "radicand", field: "arithmetic", node: "roots", pos: "n", ipa: "/ˈrædɪˌkænd/", syl: "rad·i·cand",
    senses: ["The number or expression under a radical sign: in √50 the radicand is 50, and √50 = √25 · √2 = 5√2."],
    origin: "Latin <i>radicandum</i> ‘that which is to be rooted’, from <i>radicari</i> ‘to take root’",
    forms: ["radicands"], see: ["radical"] },
  { w: "Babylonian method", field: "arithmetic", node: "roots", pos: "n", ipa: "/ˌbæbəˈloʊniən ˈmɛθəd/",
    senses: ["An iterative way to approximate √<i>A</i>: from a guess <i>x</i>, take the average of <i>x</i> and <i>A</i>/<i>x</i> as the next guess, <i>x</i><sub><i>k</i>+1</sub> = ½(<i>x</i><sub><i>k</i></sub> + <i>A</i>/<i>x</i><sub><i>k</i></sub>). For √20 from 4: ½(4 + 5) = 4.5, then about 4.4722. It is Newton's method applied to <i>x</i><sup>2</sup> − <i>A</i>."],
    see: ["square root"] },

  { w: "fraction", field: "arithmetic", node: "fractions", pos: "n", ipa: "/ˈfrækʃən/", syl: "frac·tion",
    senses: ["A number written <i>a</i>/<i>b</i> (with <i>b</i> ≠ 0) naming <i>a</i> of the <i>b</i> equal parts of a whole: 3/4 of a bar is 3 of its 4 equal pieces.",
      "The quotient <i>a</i> ÷ <i>b</i>: 3/4 is what each of 4 people gets when 3 pizzas are shared equally."],
    origin: "Latin <i>fractio</i> ‘a breaking’, from <i>frangere</i> ‘to break’",
    forms: ["fractions", "fractional"], see: ["numerator", "denominator", "rational number"] },
  { w: "numerator", field: "arithmetic", node: "fractions", pos: "n", ipa: "/ˈnumɚˌeɪtɚ/", syl: "nu·mer·a·tor",
    senses: ["The top number of a fraction, which counts how many of the equal parts are taken: in 3/4 the numerator is 3."],
    origin: "Late Latin <i>numerator</i> ‘counter’, from <i>numerare</i> ‘to count’",
    confused: [["denominator", "the bottom number, which names the size of the parts"]],
    forms: ["numerators"], see: ["denominator", "fraction"] },
  { w: "denominator", field: "arithmetic", node: "fractions", pos: "n", ipa: "/dɪˈnɑməˌneɪtɚ/", syl: "de·nom·i·na·tor",
    senses: ["The bottom number of a fraction, which says into how many equal parts the whole is divided: in 3/4 the denominator is 4. It can never be 0."],
    origin: "Medieval Latin, from Latin <i>denominare</i> ‘to name’: it names the kind of part (fourths, eighths)",
    confused: [["numerator", "the top number, which counts the parts"]],
    forms: ["denominators"], see: ["numerator", "fraction"] },
  { w: "equivalent fractions", field: "arithmetic", node: "fractions", pos: "n", ipa: "/ɪˈkwɪvələnt ˈfrækʃənz/",
    senses: ["Fractions that name the same number, obtained from one another by multiplying or dividing numerator and denominator by the same nonzero number: 3/4 = 6/8 = 9/12. Two fractions <i>a</i>/<i>b</i> and <i>c</i>/<i>d</i> are equivalent exactly when <i>ad</i> = <i>bc</i>."],
    forms: ["equivalent fraction"], see: ["fraction", "simplest form", "equivalent ratios"] },
  { w: "simplest form", field: "arithmetic", node: "fractions", pos: "n", ipa: "/ˈsɪmpləst ˈfɔrm/",
    senses: ["The form of a fraction (with positive denominator) whose numerator and denominator have no common factor except 1: 18/24 in simplest form is 3/4, found by dividing both by their greatest common factor, 6. Every rational number has exactly one."],
    syn: [["lowest terms", "the same idea; common in college texts"]], see: ["equivalent fractions", "fraction"] },
  { w: "unit fraction", field: "arithmetic", node: "fractions", pos: "n", ipa: "/ˈjunɪt ˈfrækʃən/",
    senses: ["A fraction with numerator 1, naming one equal part of a whole: 1/2, 1/3, 1/8. Any fraction <i>a</i>/<i>b</i> is <i>a</i> copies of the unit fraction 1/<i>b</i>: 3/4 = 1/4 + 1/4 + 1/4."],
    forms: ["unit fractions"], see: ["fraction"] },
  { w: "rational number", field: "arithmetic", node: "fractions", pos: "n", ipa: "/ˈræʃənəl ˈnʌmbɚ/",
    senses: ["A number that can be written as a quotient <i>a</i>/<i>b</i> of integers with <i>b</i> ≠ 0; the set of them is written ℚ. Examples: 3/4, −5 = −5/1, 0.125 = 1/8 and 0.333… = 1/3. Its decimal expansion either terminates or repeats."],
    origin: "from <i>ratio</i>: a number expressible as a ratio of integers",
    forms: ["rational numbers", "rational", "rationals"], see: ["fraction", "ratio", "repeating decimal"] },

  { w: "prime number", field: "arithmetic", node: "primes", pos: "n", ipa: "/ˈpraɪm ˈnʌmbɚ/",
    senses: ["An integer greater than 1 whose only positive divisors are 1 and itself: 2, 3, 5, 7, 11, 13, …. 2 is the only even prime, and 1 is not prime. There are infinitely many primes (Euclid)."],
    origin: "Latin <i>primus</i> ‘first’",
    forms: ["prime numbers", "prime", "primes"], see: ["composite number", "prime factorization"] },
  { w: "composite number", field: "arithmetic", node: "primes", pos: "n", ipa: "/kəmˈpɑzɪt ˈnʌmbɚ/",
    senses: ["An integer greater than 1 that is not prime, so it has a divisor other than 1 and itself: 12 = 3 × 4 is composite. A composite <i>n</i> always has a prime factor no larger than √<i>n</i>; 1 is neither prime nor composite."],
    origin: "Latin <i>compositus</i> ‘put together’",
    forms: ["composite numbers", "composite", "composites"], see: ["prime number", "factor tree"] },
  { w: "prime factorization", field: "arithmetic", node: "primes", pos: "n", ipa: "/ˈpraɪm ˌfæktɚɪˈzeɪʃən/",
    senses: ["The expression of an integer greater than 1 as a product of primes, usually written with exponents in increasing order of the primes: 360 = 2<sup>3</sup> · 3<sup>2</sup> · 5. By the Fundamental Theorem of Arithmetic it is unique apart from order."],
    forms: ["prime factorizations"], see: ["Fundamental Theorem of Arithmetic", "factor tree", "prime number"] },
  { w: "Fundamental Theorem of Arithmetic", field: "arithmetic", node: "primes", pos: "n", ipa: "/ˌfʌndəˈmɛntəl ˈθɪrəm əv əˈrɪθmətɪk/",
    senses: ["The theorem that every integer greater than 1 can be written as a product of primes, and that this product is unique except for the order of the factors: however 60 is split, it ends as 2<sup>2</sup> · 3 · 5. Uniqueness rests on Euclid's lemma."],
    see: ["prime factorization", "Euclid's lemma"] },
  { w: "Euclid's lemma", field: "arithmetic", node: "primes", pos: "n", ipa: "/ˈjuklɪdz ˈlɛmə/",
    senses: ["If a prime <i>p</i> divides a product <i>ab</i>, then <i>p</i> divides <i>a</i> or <i>p</i> divides <i>b</i>: 7 | 84 = 12 × 7 and 7 divides the factor 7. It fails for composites: 6 | 4 × 9 = 36 but 6 divides neither 4 nor 9."],
    see: ["Fundamental Theorem of Arithmetic", "prime number"] },
  { w: "factor tree", field: "arithmetic", node: "primes", pos: "n", ipa: "/ˈfæktɚ ˌtri/",
    senses: ["A diagram that finds a prime factorization by splitting a number into two factors, then splitting each composite branch again until every leaf is prime: 60 → 6 × 10 → (2 × 3) × (2 × 5), so 60 = 2<sup>2</sup> · 3 · 5. Different first splits give the same leaves."],
    forms: ["factor trees"], see: ["prime factorization", "composite number"] },
  { w: "Sieve of Eratosthenes", field: "arithmetic", node: "primes", pos: "n", ipa: "/ˈsɪv əv ˌɛrəˈtɑsθəniz/",
    senses: ["A method for listing all primes up to a bound <i>N</i>: circle 2 and cross out its other multiples, then circle the next number not crossed out and cross out its multiples, and so on. It suffices to sieve with primes up to √<i>N</i>; the numbers left are the primes."],
    see: ["prime number", "multiple"] },

  { w: "decimal", field: "arithmetic", node: "decimals", pos: "n", ipa: "/ˈdɛsəməl/", syl: "dec·i·mal",
    senses: ["A number written in base-ten place value with digits after a decimal point, each place worth one tenth of the place to its left: 3.47 = 3 + 4/10 + 7/100.",
      "As an adjective, based on ten: the decimal system."],
    origin: "Medieval Latin <i>decimalis</i>, from Latin <i>decimus</i> ‘tenth’, from <i>decem</i> ‘ten’",
    forms: ["decimals"], see: ["decimal point", "decimal place", "terminating decimal", "repeating decimal"] },
  { w: "decimal point", field: "arithmetic", node: "decimals", pos: "n", ipa: "/ˈdɛsəməl ˌpɔɪnt/",
    senses: ["The dot that separates the ones place from the tenths place in a decimal: in 12.05 the 2 is in the ones place and the 0 and 5 are tenths and hundredths. Many countries use a comma instead (12,05)."],
    forms: ["decimal points"], see: ["decimal", "decimal place"] },
  { w: "decimal place", field: "arithmetic", node: "decimals", pos: "n", ipa: "/ˈdɛsəməl ˌpleɪs/",
    senses: ["A position to the right of the decimal point (tenths, hundredths, thousandths, …), or the count of such digits: 3.142 has three decimal places, and a terminating decimal with <i>n</i> decimal places is a fraction over 10<sup><i>n</i></sup>, so 3.142 = 3142/1000."],
    forms: ["decimal places"], see: ["decimal", "decimal point"] },
  { w: "terminating decimal", field: "arithmetic", node: "decimals", pos: "n", ipa: "/ˈtɝməˌneɪtɪŋ ˈdɛsəməl/",
    senses: ["A decimal with finitely many nonzero digits after the point, such as 3/8 = 0.375. A fraction in lowest terms terminates exactly when its denominator has no prime factors other than 2 and 5."],
    forms: ["terminating decimals"], see: ["repeating decimal", "decimal"] },
  { w: "repeating decimal", field: "arithmetic", node: "decimals", pos: "n", ipa: "/rɪˈpitɪŋ ˈdɛsəməl/",
    senses: ["A decimal in which, after some point, a block of digits repeats forever, marked with a bar or dots: 1/3 = 0.333… and 5/22 = 0.2272727…. Every rational number that does not terminate repeats, and every repeating decimal is rational."],
    forms: ["repeating decimals"], see: ["terminating decimal", "rational number"] },

  { w: "mixed number", field: "arithmetic", node: "mixed-numbers", pos: "n", ipa: "/ˈmɪkst ˈnʌmbɚ/",
    senses: ["A whole number written beside a proper fraction to mean their sum: 2 ¾ means 2 + ¾ = 11/4. The juxtaposition means addition, not multiplication, and a minus sign applies to both parts: −2 ¾ = −(2 + ¾)."],
    forms: ["mixed numbers", "mixed numeral"], see: ["improper fraction", "proper fraction"] },
  { w: "improper fraction", field: "arithmetic", node: "mixed-numbers", pos: "n", ipa: "/ɪmˈprɑpɚ ˈfrækʃən/",
    senses: ["A fraction whose numerator is at least as large as its denominator (for positive parts), so its value is at least 1: 11/4 and 5/5. Dividing gives the mixed number: 11 ÷ 4 = 2 remainder 3, so 11/4 = 2 ¾."],
    forms: ["improper fractions"], ant: ["proper fraction"], see: ["mixed number", "proper fraction"] },
  { w: "proper fraction", field: "arithmetic", node: "mixed-numbers", pos: "n", ipa: "/ˈprɑpɚ ˈfrækʃən/",
    senses: ["A fraction whose numerator is smaller than its denominator (for positive parts), so its value lies between 0 and 1: 3/4 and 2/9. The fraction part of a mixed number is proper."],
    forms: ["proper fractions"], ant: ["improper fraction"], see: ["improper fraction", "mixed number"] },

  { w: "ratio", field: "arithmetic", node: "ratios", pos: "n", ipa: "/ˈreɪʃioʊ/", syl: "ra·ti·o",
    senses: ["A comparison of two quantities by division, written <i>a</i> : <i>b</i> or <i>a</i>/<i>b</i> (<i>b</i> ≠ 0), saying how much of one there is for each amount of the other: 2 cups of concentrate to 5 cups of water is the ratio 2 : 5. Order matters: 2 : 5 is not 5 : 2."],
    origin: "Latin <i>ratio</i> ‘reckoning, calculation’, from <i>reri</i> ‘to reckon, think’",
    forms: ["ratios"], see: ["rate", "equivalent ratios", "rational number"] },
  { w: "rate", field: "arithmetic", node: "ratios", pos: "n", ipa: "/reɪt/",
    senses: ["A ratio of two quantities measured in different units, whose unit is the quotient of the two units: 150 miles in 3 hours is a rate of 150 mi : 3 h, or 50 mi/h."],
    forms: ["rates"], see: ["ratio", "unit rate"] },
  { w: "unit rate", field: "arithmetic", node: "ratios", pos: "n", ipa: "/ˈjunɪt ˌreɪt/",
    senses: ["A rate rescaled so the second quantity is 1, found by dividing: $3.48 for 12 ounces is a unit rate of $0.29 per ounce. Unit rates make it easy to compare prices or speeds."],
    forms: ["unit rates"], see: ["rate", "ratio"] },
  { w: "equivalent ratios", field: "arithmetic", node: "ratios", pos: "n", ipa: "/ɪˈkwɪvələnt ˈreɪʃioʊz/",
    senses: ["Ratios obtained from one another by multiplying or dividing both parts by the same nonzero number, so they describe the same mix: 2 : 5 = 4 : 10 = 6 : 15. <i>a</i> : <i>b</i> and <i>c</i> : <i>d</i> are equivalent exactly when <i>ad</i> = <i>bc</i>."],
    forms: ["equivalent ratio"], see: ["ratio", "equivalent fractions"] },
  { w: "greatest common factor", field: "arithmetic", node: "gcf-lcm", pos: "n", ipa: "/ˈɡreɪtəst ˈkɑmən ˈfæktɚ/",
    senses: ["The largest integer that divides each of two or more integers (not all zero), abbreviated GCF and also called the greatest common divisor, gcd: the factors of 12 are 1, 2, 3, 4, 6, 12 and of 18 are 1, 2, 3, 6, 9, 18, so gcd(12, 18) = 6. For positive integers, gcd(<i>a</i>, <i>b</i>) · lcm(<i>a</i>, <i>b</i>) = <i>ab</i>."],
    syn: [["greatest common divisor","the usual name in number theory, written gcd"]],
    confused: [["least common multiple","the smallest number both divide, not the largest number dividing both"]],
    forms: ["greatest common factors", "GCF", "gcd"], see: ["least common multiple", "Euclidean algorithm", "relatively prime"] },
  { w: "least common multiple", field: "arithmetic", node: "gcf-lcm", pos: "n", ipa: "/ˈlist ˈkɑmən ˈmʌltəpəl/",
    senses: ["The smallest positive integer that is a multiple of each of two or more nonzero integers, abbreviated LCM: counting by 6s (6, 12, 18, 24) and by 8s (8, 16, 24) first meet at 24, so lcm(6, 8) = 24. In prime factorizations it takes each prime to its highest power."],
    confused: [["greatest common factor","the largest number dividing both, not the smallest number both divide"]],
    forms: ["least common multiples", "LCM", "lcm"], see: ["greatest common factor", "least common denominator"] },
  { w: "Euclidean algorithm", field: "arithmetic", node: "gcf-lcm", pos: "n", ipa: "/juˈklɪdiən ˈælɡərɪðəm/",
    senses: ["A method for finding the greatest common factor by repeated division: if <i>a</i> = <i>bq</i> + <i>r</i> with 0 ≤ <i>r</i> &lt; <i>b</i>, then gcd(<i>a</i>, <i>b</i>) = gcd(<i>b</i>, <i>r</i>), and the last nonzero remainder is the answer. For 48 and 18: 48 = 2 · 18 + 12, 18 = 1 · 12 + 6, 12 = 2 · 6 + 0, so gcd(48, 18) = 6."],
    origin: "Named after Euclid of Alexandria, who describes it in Book VII of the <i>Elements</i> (c. 300 BC); it is one of the oldest algorithms still in everyday use.",
    forms: ["Euclidean algorithms", "Euclid's algorithm"], see: ["greatest common factor", "Bezout's identity"] },
  { w: "relatively prime", field: "arithmetic", node: "gcf-lcm", pos: "aj", ipa: "/ˈrɛlətɪvli ˈpraɪm/",
    senses: ["Of two integers: having no common factor except 1, so that their greatest common factor is 1. Neither number needs to be prime: 8 and 15 are relatively prime, while 8 and 14 are not (both are even)."],
    syn: [["coprime","the same meaning; common in number theory"]],
    see: ["greatest common factor"] },
  { w: "Bezout's identity", field: "arithmetic", node: "gcf-lcm", pos: "n", ipa: "/beɪˈzuz aɪˈdɛntəti/",
    senses: ["Bézout's identity: for integers <i>a</i> and <i>b</i>, not both zero, there are integers <i>x</i> and <i>y</i> with <i>ax</i> + <i>by</i> = gcd(<i>a</i>, <i>b</i>). For 12 and 18: 12 · (−1) + 18 · 1 = 6. The extended Euclidean algorithm finds such <i>x</i> and <i>y</i>."],
    origin: "Named after the French mathematician Étienne Bézout (1730–1783), who proved a version for polynomials; the integer statement was known earlier, to Claude-Gaspard Bachet de Méziriac (1624).",
    forms: ["Bézout's identity", "Bezout identity", "Bézout's lemma"], see: ["Euclidean algorithm", "greatest common factor", "relatively prime"] },

  { w: "scientific notation", field: "arithmetic", node: "sci-notation", pos: "n", ipa: "/ˌsaɪənˈtɪfɪk noʊˈteɪʃən/",
    senses: ["A way of writing a nonzero number as <i>c</i> × 10<sup><i>n</i></sup>, where the coefficient satisfies 1 ≤ |<i>c</i>| &lt; 10 and <i>n</i> is an integer: 149,600,000,000 = 1.496 × 10<sup>11</sup> and 0.00052 = 5.2 × 10<sup>−4</sup>. To multiply, multiply the coefficients and add the exponents, then renormalise the coefficient."],
    forms: ["E notation"], see: ["coefficient", "significant figures", "order of magnitude"] },
  { w: "coefficient", field: "arithmetic", node: "sci-notation", pos: "n", ipa: "/ˌkoʊəˈfɪʃənt/", syl: "co·ef·fi·cient",
    senses: ["In scientific notation, the number <i>c</i> with 1 ≤ |<i>c</i>| &lt; 10 that multiplies the power of ten: in 1.496 × 10<sup>11</sup> the coefficient is 1.496.",
      "In algebra, a numerical factor multiplying a variable part of a term: in 4<i>x</i><sup>3</sup> − 7<i>x</i>, the coefficient of <i>x</i><sup>3</sup> is 4 and the coefficient of <i>x</i> is −7."],
    origin: "New Latin <i>coefficiens</i>, from Latin <i>co-</i> ‘together’ + <i>efficiens</i> ‘bringing about’: a quantity that acts together with another.",
    forms: ["coefficients"], see: ["scientific notation", "variable"] },
  { w: "significant figures", field: "arithmetic", node: "sci-notation", pos: "n", ipa: "/sɪɡˈnɪfɪkənt ˈfɪɡjɚz/",
    senses: ["The digits of a measured value that carry information about its precision: all nonzero digits, zeros between them, and trailing zeros after a decimal point, but not leading zeros. 0.00340 has three significant figures (3, 4 and the final 0), which scientific notation shows directly: 3.40 × 10<sup>−3</sup>."],
    syn: [["significant digits","the same meaning"]],
    forms: ["significant figure", "significant digits", "sig figs"], see: ["scientific notation", "coefficient"] },
  { w: "order of magnitude", field: "arithmetic", node: "sci-notation", pos: "n", ipa: "/ˈɔrdɚ əv ˈmæɡnəˌtud/",
    senses: ["The power of ten in a number's scientific notation, a rough measure of its size: 1.496 × 10<sup>11</sup> has order of magnitude 11. For <i>x</i> ≠ 0 it equals ⌊log<sub>10</sub>|<i>x</i>|⌋.",
      "A factor of about ten: a quantity 1,000 times larger than another is three orders of magnitude larger."],
    forms: ["orders of magnitude"], see: ["scientific notation", "power"] },

  { w: "percent", field: "arithmetic", node: "percents", pos: "n", ipa: "/pɚˈsɛnt/", syl: "per·cent",
    senses: ["A ratio expressed as a number of parts per hundred, written with the sign %: <i>p</i>% means <i>p</i>/100, so 35% = 35/100 = 0.35. Percents above 100 and below 1 are valid: 250% = 2.5 and 0.4% = 0.004."],
    origin: "From Latin <i>per centum</i> ‘by the hundred’, through Italian <i>per cento</i>; the % sign grew out of handwritten abbreviations of <i>per cento</i>.",
    confused: [["percentage point","the arithmetic difference between two percents, not a relative change"]],
    forms: ["percents", "per cent", "percentage"], see: ["percent equation", "percent change", "percentage point"] },
  { w: "percent equation", field: "arithmetic", node: "percents", pos: "n", ipa: "/pɚˈsɛnt ɪˈkweɪʒən/",
    senses: ["The equation <i>A</i> = (<i>p</i>/100) · <i>B</i> linking a part <i>A</i>, a whole <i>B</i> and a percent <i>p</i>; knowing any two gives the third. 20% of 45 is (20/100) · 45 = 9, and 9 is what percent of 45? <i>p</i> = 100 · 9/45 = 20."],
    forms: ["percent equations"], see: ["percent"] },

  { w: "common denominator", field: "arithmetic", node: "fraction-ops", pos: "n", ipa: "/ˈkɑmən dɪˈnɑməˌneɪtɚ/",
    senses: ["A denominator shared by two or more fractions after they are rewritten as equivalent fractions; any common multiple of the original denominators works. To add 2/3 + 3/4, rewrite both over 12: 8/12 + 9/12 = 17/12."],
    forms: ["common denominators"], see: ["least common denominator", "least common multiple"] },
  { w: "least common denominator", field: "arithmetic", node: "fraction-ops", pos: "n", ipa: "/ˈlist ˈkɑmən dɪˈnɑməˌneɪtɚ/",
    senses: ["The smallest common denominator of two or more fractions, equal to the least common multiple of their denominators, abbreviated LCD: for 1/6 + 3/8 it is lcm(6, 8) = 24, giving 4/24 + 9/24 = 13/24."],
    forms: ["least common denominators", "LCD"], see: ["common denominator", "least common multiple"] },
  { w: "reciprocal", field: "arithmetic", node: "fraction-ops", pos: "n", ipa: "/rɪˈsɪprəkəl/", syl: "re·cip·ro·cal",
    senses: ["The number that multiplies a given nonzero number to give 1, its multiplicative inverse: the reciprocal of 3/4 is 4/3 and of 5 is 1/5. Zero has no reciprocal. Dividing by a fraction is multiplying by its reciprocal: 2/3 ÷ 3/4 = 2/3 × 4/3 = 8/9."],
    origin: "From Latin <i>reciprocus</i> ‘returning, going back and forth’; turning a fraction upside down and back again returns the original.",
    syn: [["multiplicative inverse","the formal name used in algebra"]],
    forms: ["reciprocals"], see: ["common denominator"] },

  { w: "percent change", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/pɚˈsɛnt ˈtʃeɪndʒ/",
    senses: ["The change in a quantity as a percent of its original value: 100 · (<i>V</i><sub>1</sub> − <i>V</i><sub>0</sub>)/<i>V</i><sub>0</sub>. From 40 to 50 is a 25% increase, but from 50 back to 40 is a 20% decrease, because the original value differs."],
    confused: [["percentage point","a plain difference of two percents: 4% to 5% is 1 percentage point but a 25% change"]],
    forms: ["percent changes", "percent increase", "percent decrease", "percentage change"], see: ["percent", "percentage point"] },
  { w: "percentage point", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/pɚˈsɛntɪdʒ ˌpɔɪnt/",
    senses: ["A unit for the arithmetic difference between two percents: a rate that rises from 4% to 5% has risen 1 percentage point, which is a 25% increase in the rate."],
    forms: ["percentage points"], see: ["percent change", "percent"] },
  { w: "simple interest", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/ˈsɪmpəl ˈɪntrəst/",
    senses: ["Interest computed on the principal alone, so the same amount is added each period: <i>I</i> = <i>Prt</i> and <i>A</i> = <i>P</i>(1 + <i>rt</i>). $1,000 at 5% for 3 years earns 1000 · 0.05 · 3 = $150. It grows linearly in time."],
    confused: [["compound interest","earns interest on earlier interest as well"]],
    see: ["compound interest", "principal"] },
  { w: "compound interest", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/ˈkɑmpaʊnd ˈɪntrəst/",
    senses: ["Interest that is added to the balance each period, so later interest is earned on earlier interest: <i>A</i> = <i>P</i>(1 + <i>r</i>/<i>n</i>)<sup><i>nt</i></sup> for <i>n</i> compounding periods a year, or <i>A</i> = <i>Pe</i><sup><i>rt</i></sup> when compounded continuously. $1,000 at 5% compounded yearly for 3 years grows to 1000 · 1.05<sup>3</sup> ≈ $1,157.63. It grows exponentially in time."],
    confused: [["simple interest","earns interest on the principal only"]],
    see: ["simple interest", "principal"] },
  { w: "principal", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/ˈprɪnsəpəl/", syl: "prin·ci·pal",
    senses: ["The original amount of money deposited or borrowed, on which interest is computed, written <i>P</i>: in <i>A</i> = <i>P</i>(1 + <i>rt</i>), a $1,000 deposit is the principal."],
    confused: [["principle","a basic rule or law, not a sum of money"]],
    forms: ["principals"], see: ["simple interest", "compound interest"] },
  { w: "discount", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/ˈdɪskaʊnt/", syl: "dis·count",
    senses: ["A reduction from a price, often stated as a percent of the original price; a discount at rate <i>d</i> multiplies the price by 1 − <i>d</i>. 30% off $80 leaves 80 × 0.70 = $56."],
    forms: ["discounts", "discounted"], see: ["markup", "percent change"] },
  { w: "markup", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/ˈmɑrkˌʌp/", syl: "mark·up",
    senses: ["An increase added to a cost to set a selling price, often stated as a percent of the cost; a markup at rate <i>r</i> multiplies the cost by 1 + <i>r</i>. A 25% markup on a $40 item gives 40 × 1.25 = $50."],
    forms: ["markups", "mark-up"], see: ["discount", "percent change"] },
  { w: "sales tax", field: "arithmetic", node: "percent-apps", pos: "n", ipa: "/ˈseɪlz ˌtæks/",
    senses: ["A tax charged as a percent of a purchase price; at rate <i>s</i> the total is <i>x</i>(1 + <i>s</i>). A $50 purchase with 8% sales tax costs 50 × 1.08 = $54."],
    forms: ["sales taxes"], see: ["markup", "percent"] },

  { w: "mean", field: "arithmetic", node: "averages", pos: "n", ipa: "/min/",
    senses: ["The sum of a set of data values divided by how many there are, written <i>x̄</i>: the mean of 2, 3, 3, 5, 12 is 25/5 = 5. The deviations from the mean sum to zero, so it is the data's balance point; it is pulled toward extreme values."],
    syn: [["arithmetic mean","the full name, distinguishing it from geometric and other means"], ["average","the everyday word, usually meaning the mean"]],
    confused: [["median","the middle value in order, which resists extreme values"]],
    forms: ["means", "arithmetic mean"], see: ["median", "mode", "average", "outlier"] },
  { w: "median", field: "arithmetic", node: "averages", pos: "n", ipa: "/ˈmidiən/", syl: "me·di·an",
    senses: ["The middle value of a data set listed in order, or the mean of the two middle values when the count is even: the median of 2, 3, 3, 5, 12 is 3, and of 1, 4, 6, 9 it is (4 + 6)/2 = 5. Extreme values barely move it, which is why incomes and house prices are usually reported by median."],
    origin: "From Latin <i>medianus</i> ‘of the middle’, from <i>medius</i> ‘middle’.",
    confused: [["mean","the sum divided by the count, which uses every value and is pulled by outliers"]],
    forms: ["medians"], see: ["mean", "mode", "outlier"] },
  { w: "mode", field: "arithmetic", node: "averages", pos: "n", ipa: "/moʊd/",
    senses: ["A value that occurs most often in a data set: the mode of 2, 3, 3, 5, 12 is 3. A data set can have one mode, several, or none when every value occurs equally often."],
    origin: "From French <i>mode</i>, Latin <i>modus</i> ‘measure, manner’; the statistical sense was introduced by Karl Pearson in 1895.",
    forms: ["modes", "modal"], see: ["mean", "median"] },
  { w: "range", field: "arithmetic", node: "averages", pos: "n", ipa: "/reɪndʒ/",
    senses: ["In statistics, the largest data value minus the smallest, a simple measure of spread: the range of 2, 3, 3, 5, 12 is 12 − 2 = 10.",
      "The set of all outputs of a function: the range of <i>f</i>(<i>x</i>) = <i>x</i><sup>2</sup> on the real numbers is all <i>y</i> ≥ 0."],
    forms: ["ranges"], see: ["outlier", "function"] },
  { w: "outlier", field: "arithmetic", node: "averages", pos: "n", ipa: "/ˈaʊtˌlaɪɚ/", syl: "out·li·er",
    senses: ["A data value far from the rest of the data. In commute times of 22, 25, 24, 23 and 90 minutes, 90 is an outlier: it pulls the mean up to 36.8 while the median stays at 24."],
    forms: ["outliers"], see: ["mean", "median", "range"] },
  { w: "average", field: "arithmetic", node: "averages", pos: "n", ipa: "/ˈævrɪdʒ/", syl: "av·er·age",
    senses: ["A single number that represents a typical value of a data set, a measure of center; in everyday use it nearly always means the mean: the average of 4, 7 and 10 is 21/3 = 7.",
      "More broadly, any of the measures of center (mean, median or mode), so a stated ‘average’ should say which one it is."],
    origin: "From Middle French <i>avarie</i> and Italian <i>avaria</i>, ‘damage to a ship or its cargo’; the loss was shared out evenly among the owners, which gave the sense of an even share.",
    forms: ["averages"], see: ["mean", "median", "mode"] },

  { w: "proportion", field: "arithmetic", node: "proportions", pos: "n", ipa: "/prəˈpɔrʃən/", syl: "pro·por·tion",
    senses: ["An equation stating that two ratios are equal, <i>a</i>/<i>b</i> = <i>c</i>/<i>d</i> with <i>b</i>, <i>d</i> ≠ 0; if three of the four numbers are known, the fourth follows. If 9 gallons drive 252 miles, then 9/252 = <i>x</i>/420 gives <i>x</i> = 15 gallons for 420 miles."],
    origin: "From Latin <i>proportio</i>, from the phrase <i>pro portione</i> ‘according to its share’.",
    forms: ["proportions"], see: ["cross product", "directly proportional", "constant of proportionality"] },
  { w: "cross product", field: "arithmetic", node: "proportions", pos: "n", ipa: "/ˈkrɔs ˌprɑdəkt/",
    senses: ["In a proportion <i>a</i>/<i>b</i> = <i>c</i>/<i>d</i>, either of the diagonal products <i>ad</i> and <i>bc</i>; the proportion holds exactly when they are equal (multiply both sides by <i>bd</i>). For 3/4 = 6/8: 3 · 8 = 24 = 4 · 6.",
      "In vector algebra, a different operation: the vector <b>u</b> × <b>v</b> perpendicular to two vectors in space."],
    forms: ["cross products", "cross-multiplication", "cross-multiply"], see: ["proportion"] },
  { w: "constant of proportionality", field: "arithmetic", node: "proportions", pos: "n", ipa: "/ˈkɑnstənt əv prəˌpɔrʃəˈnæləti/",
    senses: ["The fixed nonzero number <i>k</i> in a direct variation <i>y</i> = <i>kx</i>, equal to <i>y</i>/<i>x</i> for every pair, or in an inverse variation <i>xy</i> = <i>k</i>. A car that drives 252 miles on 9 gallons has <i>k</i> = 252/9 = 28 miles per gallon."],
    forms: ["constants of proportionality"], see: ["directly proportional", "inversely proportional", "proportion"] },
  { w: "directly proportional", field: "arithmetic", node: "proportions", pos: "aj", ipa: "/dɪˈrɛktli prəˈpɔrʃənəl/",
    senses: ["Of two quantities: related by <i>y</i> = <i>kx</i> for a constant <i>k</i> ≠ 0, so that doubling one doubles the other and <i>y</i>/<i>x</i> is the same for every pair. Fuel used is directly proportional to distance at a steady rate."],
    confused: [["inversely proportional","doubling one halves the other: <i>xy</i> is constant"]],
    forms: ["proportional", "direct variation"], see: ["constant of proportionality", "inversely proportional"] },
  { w: "inversely proportional", field: "arithmetic", node: "proportions", pos: "aj", ipa: "/ɪnˈvɝsli prəˈpɔrʃənəl/",
    senses: ["Of two quantities: related by <i>xy</i> = <i>k</i> for a constant <i>k</i> ≠ 0, so that doubling one halves the other. If 6 workers take 4 days, 12 workers take 2 days (6 · 4 = 12 · 2 = 24)."],
    confused: [["directly proportional","doubling one doubles the other: <i>y</i>/<i>x</i> is constant"]],
    forms: ["inverse variation"], see: ["constant of proportionality", "directly proportional"] },

  { w: "real number", field: "arithmetic", node: "real-numbers", pos: "n", ipa: "/ˈril ˈnʌmbɚ/",
    senses: ["Any number that corresponds to a point on the number line, rational or irrational; the set is written ℝ. −3, 0.75, √2 and π are all real numbers. ℝ is a complete ordered field."],
    forms: ["real numbers", "reals"], see: ["irrational number", "completeness", "dense", "countable"] },
  { w: "irrational number", field: "arithmetic", node: "real-numbers", pos: "n", ipa: "/ɪˈræʃənəl ˈnʌmbɚ/",
    senses: ["A real number that cannot be written as a quotient <i>p</i>/<i>q</i> of integers; its decimal expansion neither terminates nor repeats. √2 = 1.41421356… and π = 3.14159265… are irrational, and √<i>n</i> for a positive integer <i>n</i> is irrational unless <i>n</i> is a perfect square."],
    origin: "From Latin <i>irrationalis</i>, used to translate Greek <i>alogos</i> ‘without ratio’: such a length has no ratio of whole numbers to a unit length.",
    forms: ["irrational numbers", "irrational", "irrationals"], see: ["real number", "dense"] },
  { w: "dense", field: "arithmetic", node: "real-numbers", pos: "aj", ipa: "/dɛns/",
    senses: ["Of a set of numbers: having a member between any two distinct real numbers, however close. The rationals are dense in ℝ (between 0.1 and 0.11 lies 0.105), and so are the irrationals."],
    forms: ["denser", "density"], see: ["real number", "irrational number"] },
  { w: "completeness", field: "arithmetic", node: "real-numbers", pos: "n", ipa: "/kəmˈplitnəs/", syl: "com·plete·ness",
    senses: ["The property of the real numbers that every nonempty set bounded above has a least upper bound in the set of reals; it is what leaves no gaps on the number line. The rationals lack it: {<i>x</i> ∈ ℚ : <i>x</i><sup>2</sup> &lt; 2} has no least upper bound in ℚ, while in ℝ its least upper bound is √2."],
    forms: ["complete", "completeness axiom"], see: ["real number", "dense"] },
  { w: "countable", field: "arithmetic", node: "real-numbers", pos: "aj", ipa: "/ˈkaʊntəbəl/", syl: "count·a·ble",
    senses: ["Of an infinite set: able to be listed as a first, second, third, … element, that is, matched one to one with the natural numbers. The integers and the rationals are countable; Georg Cantor proved in 1874 that the real numbers are uncountable."],
    forms: ["uncountable", "countably"], see: ["real number"] },

  { w: "unit", field: "arithmetic", node: "units", pos: "n", ipa: "/ˈjunɪt/", syl: "u·nit",
    senses: ["A fixed, agreed quantity used as a standard of measurement, such as the metre, kilogram or second; a measurement is a number times a unit, as in 60 kg. Units multiply, divide and cancel like algebraic factors: miles ÷ hours gives miles per hour."],
    forms: ["units", "SI unit"], see: ["conversion factor", "dimensional analysis", "measure"] },
  { w: "conversion factor", field: "arithmetic", node: "units", pos: "n", ipa: "/kənˈvɝʒən ˈfæktɚ/",
    senses: ["A ratio of two equal quantities expressed in different units, so its value is 1: 5280 ft / 1 mi. Multiplying by it changes the units without changing the quantity: 3 mi × (5280 ft / 1 mi) = 15,840 ft. For area or volume, square or cube the factor."],
    forms: ["conversion factors"], see: ["dimensional analysis", "unit"] },
  { w: "dimensional analysis", field: "arithmetic", node: "units", pos: "n", ipa: "/dɪˈmɛnʃənəl əˈnæləsɪs/",
    senses: ["Converting units by multiplying by conversion factors chosen so that unwanted units cancel: 60 mi/h × (5280 ft / 1 mi) × (1 h / 3600 s) = 88 ft/s.",
      "Checking that an equation is dimensionally consistent, with every term having the same dimension (length, mass, time and so on); a wrong final unit signals a setup error."],
    syn: [["factor-label method","the same conversion technique, the name used in many chemistry courses"]],
    see: ["conversion factor", "unit"] }
]);
